### ISSUE TITLE
Upload mime-type

### ISSUE THREAD

**Issue by 383bd03d** [payloadcms/payload#1183]
If you specify a mime type other than belongs to images in collection upload config, for example `mimeTypes: ["application/geo+json"],`, and upload file via admin you'll get mimetype error, because .geojson file uploads as octet-stream mimetype, but upload via api endpoint works fine

Console error: `[11:10:18] ERROR (payload): ValidationError: The following field is invalid: mimeType`

**Comment by denolfe** [comment]
Thank you for the report @383bd03d. Some changes were made recently regarding mimeType detection. What version of Payload are you seeing this behavior on?

**Comment by 383bd03d** [comment]
"payload": "^1.0.20"

**Comment by 383bd03d** [comment]
I updated to 1.1.4 but the error remains, also I using s3 upload plugin and file successfully has been uploaded to aws

**Comment by jmikrut** [comment]
Hey @383bd03d - we just changed a bunch of stuff on the backend. Give it a shot again, will you?

**Comment by 383bd03d** [comment]
Hi! I've update payload and get new error
`TypeError: Cannot read property 'mime' of undefined`

**Comment by jmikrut** [comment]
@383bd03d can you share more information about your error? 

- The full error stack trace
- The file mime type that you are uploading
- The mime type restrictions you have in place on your upload itself
- If you can, share the file as well

**Comment by TimHal** [comment]
I can confirm this bug

> The full error stack trace

```
[09:33:49] ERROR (payload): FileUploadError: There was a problem while uploading the file.
    at new ExtendableError (/home/node/node_modules/payload/src/errors/APIError.ts:26:11)
    at new APIError (/home/node/node_modules/payload/src/errors/APIError.ts:43:5)
    at new FileUploadError (/home/node/node_modules/payload/src/errors/FileUploadError.ts:6:5)
    at generateFileData (/home/node/node_modules/payload/src/uploads/generateFileData.ts:122:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at create (/home/node/node_modules/payload/src/collections/operations/create.ts:98:55)
    at createHandler (/home/node/node_modules/payload/src/collections/requestHandlers/create.ts:15:17)
TypeError: Cannot read property 'mime' of undefined
    at generateFileData (/home/node/node_modules/payload/src/uploads/generateFileData.ts:86:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at create (/home/node/node_modules/payload/src/collections/operations/create.ts:98:55)
    at createHandler (/home/node/node_modules/payload/src/collections/requestHandlers/create.ts:15:17)
[09:34:06] ERROR (payload): FileUploadError: There was a problem while uploading the file.
    at new ExtendableError (/home/node/node_modules/payload/src/errors/APIError.ts:26:11)
    at new APIError (/home/node/node_modules/payload/src/errors/APIError.ts:43:5)
    at new FileUploadError (/home/node/node_modules/payload/src/errors/FileUploadError.ts:6:5)
    at generateFileData (/home/node/node_modules/payload/src/uploads/generateFileData.ts:122:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at create (/home/node/node_modules/payload/src/collections/operations/create.ts:98:55)
    at createHandler (/home/node/node_modules/payload/src/collections/requestHandlers/create.ts:15:17)
TypeError: Cannot read property 'mime' of undefined
    at generateFileData (/home/node/node_modules/payload/src/uploads/generateFileData.ts:86:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at create (/home/node/node_modules/payload/src/collections/operations/create.ts:98:55)
    at createHandler (/home/node/node_modules/payload/src/collections/requestHandlers/create.ts:15:17)
```

> The file mime type that you are uploading

```
file --mime-type test-1.svg 
test-1.svg: image/svg+xml
```

> The mime type restrictions you have in place on your upload itself

No restrictions in place right now, I previously tried `"image/*"` and `"image/svg+xml"`, rising the same error as above.

> If you can, share the file as well

I have tested many files which I can not share, but any .svg file works really. 
One freely available example which provokes the bug can be found [here](https://worldvectorlogo.com/de/logo/test-1)


Node Version: v14.20.1
NPM Version: 6.14.17
Payload Version: 1.1.10

**Comment by TimHal** [comment]
Changing line 86 of `generateFileData.ts` to
```
        const mime = bufferInfo?.mime ?? file.mimetype;
```
should resolve the problem I think. However, I can not confirm this 100% as it is not possible for me to build and test the project on my machine right now.

**Comment by jmikrut** [comment]
@TimHal looks like you're right! I was able to reproduce with an SVG. I've just deployed a fix.

Thanks everyone!

**Comment by 383bd03d** [comment]
Why did you hardcode mime only for svg files?

**Comment by jmikrut** [comment]
@383bd03d because they are the only file type I know of that will report a different mime type based on if there is an XML tag present at the top of the file

**Comment by 383bd03d** [comment]
[odessa-obl.geojson.zip](https://github.com/payloadcms/payload/files/9831073/odessa-obl.geojson.zip)
Here's a sample geojson file, I think it could be a similar to a committed fixed that consist from svg+xml, could it be dynamic for another mime types, like application/geo+json ?

**Comment by 383bd03d** [comment]
Also in my case I use s3 upload, and when I get error from payload admin, file successfully uploads to s3
