### ISSUE TITLE
Globals not referencing collections with relationship fields in them.

### ISSUE THREAD

**Issue by ronan18** [payloadcms/payload#1306]
# Bug Report

## Current Behavior

I'm trying to reference a collection from a global. Instead of building the server, the cli spits out an error:
node_modules/payload/dist/fields/config/sanitize.js:36
                    throw new errors_1.InvalidFieldRelationship(field, relationship);
                    ^

InvalidFieldRelationship: Field Piece has invalid relationship ' WrittenPieces'.
    at new ExtendableError (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/errors/APIError.js:22:15)
    at new APIError (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/errors/APIError.js:38:9)
    at new InvalidFieldRelationship (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/errors/InvalidFieldRelationship.js:9:9)
    at /Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/fields/config/sanitize.js:36:27
    at Array.forEach (<anonymous>)
    at /Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/fields/config/sanitize.js:34:27
    at Array.map (<anonymous>)
    at sanitizeFields (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/fields/config/sanitize.js:16:19)
    at /Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/globals/config/sanitize.js:61:57
    at Array.map (<anonymous>)
    at sanitizeGlobals (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/globals/config/sanitize.js:14:38)
    at sanitizeConfig (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/config/sanitize.js:35:58)
    at buildConfig (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/config/build.js:19:35)
    at Object.<anonymous> (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/payload.config.js:10:25)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._compile (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.newLoader [as .js] (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfig (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/config/load.js:35:18)
    at init (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/init.js:48:41)
    at initSync (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/init.js:125:22)
    at Payload.init (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/node_modules/payload/dist/index.js:154:29)
    at Object.<anonymous> (/Users/ronanfuruta/Desktop/Dev/Client/halfway-there-cms/server.js:13:9)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  status: 500,
  data: null,
  isPublic: false,
  isOperational: true
}

Node.js v18.12.0

This error only shows up if I'm referencing a collection that has reference fields inside of it. If I reference a collection that doesn't have relationships it works as expected. 

## Expected Behavior

I expect the global to be able to reference the collection.

### Global collection:
```
const FeaturedArticle = {
    slug: 'featuredArticle',
    versions: {
        drafts: true
    },
    fields: [
        {name: "test",
    type: "text",
},
      {
        name: "piece",
        type: "relationship",
        relationTo: "writtenPieces",
        hasMany: false,
        required: true,
        maxDepth: 3
      }
    ],
    access: {
        read: ({ req }) => {
          // If there is a user logged in,
          // let them retrieve all documents
          if (req.user) return true;
    
          // If there is no user,
          // restrict the documents that are returned
       
          return {
            _status: {
              equals: 'published',
            },
          };
        },
      },
};

export default FeaturedArticle;
```

### Written Piece collection:
```
const WrittenPieces = {
    slug: 'writtenPieces',
    admin: {
      useAsTitle: 'title',
      listSearchableFields: ['content'],
      group: 'Content'
    },
    access: {
        read: ({ req }) => {
          // If there is a user logged in,
          // let them retrieve all documents
          if (req.user) return true;
    
          // If there is no user,
          // restrict the documents that are returned
     
          return {
            _status: {
              equals: 'published',
            },
          };
        },
      },
    versions: {
        drafts: true,
        maxPerDoc: 5
    },
    fields: [
        {
          label: "Banner Image",
            name: 'image',
            type: 'upload',
            relationTo: 'media',
           
        },
      {
      
        name: 'title',
        type: 'text',
        required: true,
      },
      {
        label: "Unique Slug",
        name: 'slug',
        type: 'text',
        required: true,
        index: true,
        admin: {
         
        validate: async (val, { operation }) => {
        var urlPattern = /^[a-zA-Z0-9_-]*$/
        if (!urlPattern.test(val)) {
          return 'Slug must be URL safe'
         }
          const response = await fetch(`http://localhost:3111/writtenPieces/${val}`);
          if (response.ok) {
          return 'This value is allready in use';

           
          }
          return true;
  
        },
      },
      {
        name: 'content',
        type: 'richText',
        required: true,
        admin: {
            elements: ["h1", "h2", "link", "indent", "ol", "ul"],
        }
      },
      {
        name: 'author',
        type: 'relationship',
        required: true,
        relationTo: 'authors'
      },
      {
        name: 'publishedAt',
        type: 'date',
        label: 'Published At',
        admin: {
          date: {
            // All config options above should be placed here
            pickerAppearance: 'dateOnly',
          }
        }
      },
      {
        name: "tags",
        type: "array",
        admin: {
        
        },
        fields: [{
            name: "tag",
            type: "relationship",
            relationTo: "tags",
            required: true
        }]

      }

    ]
  }
  
  export default WrittenPieces;
```

**Comment by ronan18** [comment]
update: if I change the collection from 'writtenPieces' to 'written-pieces' it resolves the error. It must hav to do with this issue: #1316

**Comment by jmikrut** [comment]
Hey @ronan18 — yes, this is the same issue. I'm going to close this one in favor of the other one. Thank you for the report!
