### ISSUE TITLE
How to import ESM from node_modules in a collection config?

### ISSUE THREAD

**Issue by Razunter** [payloadcms/payload#1439]
# Bug Report

Trying to import [slugify](https://github.com/sindresorhus/slugify) in a collection config, getting ESM import error.

## Current Behavior

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/www/html/node_modules/@sindresorhus/slugify/index.js from /var/www/html/src/collections/NewsPosts.ts not supported.
Instead change the require of index.js in /var/www/html/src/collections/NewsPosts.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> (/var/www/html/node_modules/ts-node/dist/index.js:851:20)
    at Object.newLoader [as .js] (/var/www/html/node_modules/pirates/lib/index.js:141:7)
    at Object.<anonymous> (/var/www/html/src/collections/NewsPosts.ts:42:33)
    at Module._compile (/var/www/html/node_modules/pirates/lib/index.js:136:24)
    at m._compile (/var/www/html/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> (/var/www/html/node_modules/ts-node/dist/index.js:859:16)
    at Object.newLoader [as .ts] (/var/www/html/node_modules/pirates/lib/index.js:141:7)
    at Object.<anonymous> (/var/www/html/src/payload.config.ts:34:35)
    at Module._compile (/var/www/html/node_modules/pirates/lib/index.js:136:24)
    at m._compile (/var/www/html/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> (/var/www/html/node_modules/ts-node/dist/index.js:859:16)
    at Object.newLoader [as .ts] (/var/www/html/node_modules/pirates/lib/index.js:141:7)
    at loadConfig (/var/www/html/node_modules/payload/dist/config/load.js:35:18)
    at init (/var/www/html/node_modules/payload/dist/init.js:48:41)
    at initSync (/var/www/html/node_modules/payload/dist/init.js:125:22)
    at Payload.init (/var/www/html/node_modules/payload/dist/index.js:154:29)
    at Object.<anonymous> (/var/www/html/src/server.ts:39:19)
    at m._compile (/var/www/html/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> (/var/www/html/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/var/www/html/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/var/www/html/node_modules/ts-node/dist/bin.js:54:12)
    at main (/var/www/html/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/var/www/html/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

Dynamic import doesn't work either.

## Steps to Reproduce
```
import slugify from '@sindresorhus/slugify'

...

    hooks: {
        beforeChange: [async ({data}) => {
            if (!data.slug) {
                data.slug = slugify(data.title)
                return data
            }
        }]
    }
```

## Detailed Description

Typescript, `"payload": "^1.1.26"`, node 18

**Comment by denolfe** [comment]
Payload, along with most in the ecosystem, does not support ESM modules. You'll need to downgrade to a version of slugify that is compatible with CommonJS. It looks like anything before 2.0 would work.

More detail on that package in particular:
https://github.com/sindresorhus/slugify/issues/67
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
