### ISSUE TITLE
Error: Unexpected end of JSON input when switching locales on blocks containing rich text

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#147]
# Bug Report

Bit of a long and complicated explanation but should have a simple solution. Adding a block of rich text, saving, switching locale and then saving without adding any content causes a problem in JSON.parse because it tries to evaluate undefined.

## Expected Behavior

When added new content to a block localised at a field level, the document should save even when no content has been added.

## Current Behavior

Data passed to the API is undefined and JSON.parse tries to evaluate it.

## Possible Solution

If the request data from a rich text field would fail to evaluate as JSON then that field should be skipped as if it were not there?

## Steps to Reproduce

1. Setup payload with more than 1 locale.
2. Create a collection with 1 block field
3. Create a block that just contains 1 **localized** richText field
4. Add a new entry to that collection under a locale containing 1 block and a bit of richText content
5. Switch locale
6. Hit save without interacting

## Detailed Description

Payload version: 0.6.2

![image](https://user-images.githubusercontent.com/3854592/115561762-d8ea0c00-a2f0-11eb-8ff3-7f4236d242ba.png)

[13:18:00] ERROR (payload): SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/fields/traverseFields.ts:97:37
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/fields/traverseFields.ts:69:10)
    at /Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/fields/traverseFields.ts:225:13
    at Array.forEach (<anonymous>)
    at /Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/fields/traverseFields.ts:221:57
    at Array.forEach (<anonymous>)
    at Object.traverseFields [as default] (/Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/fields/traverseFields.ts:69:10)
    at Payload.performFieldOperations (/Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/fields/performFieldOperations.ts:75:17)
    at Payload.update (/Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/collections/operations/update.ts:177:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Payload.update (/Users/richard/Code/Brightvision/bv-web-v2/node_modules/payload/src/collections/requestHandlers/update.ts:13:17)

**Comment by richardvanbergen** [comment]
Wonderful! Thank you @jmikrut 🙏 🙏 🙏
