### ISSUE TITLE
TypeError error when using camelcase for Upload Collection slug

### ISSUE THREAD

**Issue by nluciano233** [payloadcms/payload#1511]
# Bug Report

If you create am Upload Collection that has a camel cased slug name (es. questionsMedia) you will receive a TypeError when trying to run the server. The issue goes away when writing the slug name all in lowercase.

1. Create an upload collection with the following code:
```
import { CollectionConfig } from 'payload/types';

const QuestionsMedia: CollectionConfig = {
  slug: 'questionsMedia',
  upload: {
    staticURL: '/media/questions',
    staticDir: 'media/questions',
    adminThumbnail: 'thumbnail',
    mimeTypes: ['image/*'],
  },
  fields: [
    {
      type: 'text',
      name: 'alt'
    }
  ],
};

export default QuestionsMedia;
```
2. In a new collection, add an upload field and reference to the QuestionsMedia collection. The field looks like this:
```
        {
          type: 'upload',
          relationTo: 'questionsMedia',
          name: 'answerPhoto',
        },
```
3. You will receive this error:
```
[14:41:47] INFO (payload): Starting Payload...
TypeError: Cannot read properties of undefined (reading 'graphQL')
    at upload (/home/lclx/Odin/youtestplus/node_modules/payload/src/graphql/schema/buildObjectType.ts:152:52)
    at /home/lclx/Odin/youtestplus/node_modules/payload/src/graphql/schema/buildObjectType.ts:523:12
    at Array.reduce (<anonymous>)
    at fields (/home/lclx/Odin/youtestplus/node_modules/payload/src/graphql/schema/buildObjectType.ts:514:26)
    at resolveThunk (/home/lclx/Odin/youtestplus/node_modules/graphql/type/definition.js:480:40)
    at defineFieldMap (/home/lclx/Odin/youtestplus/node_modules/graphql/type/definition.js:692:18)
    at GraphQLObjectType.getFields (/home/lclx/Odin/youtestplus/node_modules/graphql/type/definition.js:633:27)
    at collectReferencedTypes (/home/lclx/Odin/youtestplus/node_modules/graphql/type/schema.js:366:81)
    at collectReferencedTypes (/home/lclx/Odin/youtestplus/node_modules/graphql/type/schema.js:368:9)
    at new GraphQLSchema (/home/lclx/Odin/youtestplus/node_modules/graphql/type/schema.js:153:7)
    at registerSchema (/home/lclx/Odin/youtestplus/node_modules/payload/src/graphql/registerSchema.ts:75:20)
    at init (/home/lclx/Odin/youtestplus/node_modules/payload/src/init.ts:72:19)
    at initSync (/home/lclx/Odin/youtestplus/node_modules/payload/src/init.ts:154:7)
    at Payload.init (/home/lclx/Odin/youtestplus/node_modules/payload/src/index.ts:125:13)
    at Object.<anonymous> (/home/lclx/Odin/youtestplus/src/server.ts:13:9)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/lclx/Odin/youtestplus/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> (/home/lclx/Odin/youtestplus/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at main (/home/lclx/Odin/youtestplus/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/home/lclx/Odin/youtestplus/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
[nodemon] app crashed - waiting for file changes before starting...
```

## Other Details
The error is not here if we don't use camelcase in the Upload Collection slug, so my guess is that the issue is how Payload handles camelcase for this type of collections.

"payload": "^1.1.24",
browser: Brave Browser

**Comment by denolfe** [comment]
Related to #1322 which was reverted by #1325 because it had more implications than expected.

The easiest workaround here is to actually use kebab case for slugs. I'll leave this open to ensure it gets addressed.
