### ISSUE TITLE
Failed to load resource on server.

### ISSUE THREAD

**Issue by aljubaer** [payloadcms/payload#159]
# Bug Report

Hi there,

I’ve just started with Payload. I’ve hosted a simple Todo starter on a Plesk server using Docker and it is up and running here, 
[http://my-domain:8081/admin/]()
However, while creating a new user it is looking for resources from localhost and gets this error. 
POST https://localhost:8081/api/users/first-register net::ERR_CONNECTION_REFUSED

## Expected Behavior

Should call `http://my-domain:8081/api/users/first-register` 
and load the dashboard.

## Current Behavior

Get this error
`POST https://localhost:8081/api/users/first-register net::ERR_CONNECTION_REFUSED`

## Detailed Description

My server config is like this.
`const PORT = process.env.PORT || 8081
const HOST_NAME = process.env.HOST_NAME || 'localhost'

export default buildConfig({
  serverURL: `https://${HOST_NAME}:${PORT}`,
  admin: {
    user: Users.slug,
  },
  collections: [
    TodoLists,
    Users,
    CustomTodo
  ],
});`

And my console log:

`[11:32:19] INFO (payload): Starting Payload...
[11:32:20] INFO (payload): Payload Api URL: http://my-domain:8081
[11:32:20] INFO (payload): Payload Admin URL:http://my-domain:8081
App is running on port 8081
[11:32:20] INFO (payload): Connected to Mongo server successfully!
[11:32:20] INFO (payload): E-mail configured with mock configuration
[11:32:20] INFO (payload): Log into mock email provider at https://ethereal.email
[11:32:20] INFO (payload): Mock email account username: j3oeudpshuv4ebum@ethereal.email
[11:32:20] INFO (payload): Mock email account password: dXPrKuUHGQccrMPcdh
[11:42:04] ERROR (payload): NotFound: The requested resource was not found.
    at new ExtendableError (/app/node_modules/payload/src/errors/APIError.ts:26:11)
    at new APIError (/app/node_modules/payload/src/errors/APIError.ts:43:5)
    at new NotFound (/app/node_modules/payload/src/errors/NotFound.ts:6:5)
    at Payload.findByID (/app/node_modules/payload/src/collections/operations/findByID.ts:88:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Payload.findByID (/app/node_modules/payload/src/collections/requestHandlers/findByID.ts:19:17)
`

Payload version: `0.6.6`

**Comment by denolfe** [comment]
@aljubaer Thanks for the report.

Do you have the Dockerfile that is actually being deploying and with what commands? If I had to guess, this is likely due to how Docker handles networking resolution. I'd try changing the `HOST_NAME` to `0.0.0.0` or `127.0.0.1` and see if that makes a difference.

**Comment by aljubaer** [comment]
@denolfe 
Thanks for your quick reply.
Yes, I am using Dockerfile,
`FROM node:14`
`WORKDIR /app`
`COPY package*.json ./`
`RUN npm install`
`COPY . .`
`RUN npm run build`
`ENV PORT=8081`
`EXPOSE 8081`
`CMD ["npm", "start"]`

I also changed HOST_NAME to `127.0.0.1` but still getting the same error. One thing to mention URLs with "..../admin/...." are working fine but the APIs with "..../api/...." aren't updating according to HOST. They always remain localhost.

**Comment by DanRibbens** [comment]
It looks like your env variable is falling back to localhost. It isn't available because it needs to whitelisted for webpack by Payload using PAYLOAD_PUBLIC_ as a prefix on the env var.

The docs explain it here: https://payloadcms.com/docs/admin/webpack#admin-environment-vars

**Comment by aljubaer** [comment]
@DanRibbens Thanks. I solved the issue by removing env vars and hardcoding them.
