### ISSUE TITLE
Issue with versions & autosave for Globals

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#1698]
# Bug Report
When hitting "Publish Changes", the following error occurs:
`
[22:56:30] ERROR (payload): TypeError: Cannot read properties of null (reading 'updatedAt')
    at getLatestGlobalVersion (C:\Users\johan\Programming\SBRENT-Payload\node_modules\payload\src\versions\getLatestGlobalVersion.ts:28:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at update (C:\Users\johan\Programming\SBRENT-Payload\node_modules\payload\src\globals\operations\update.ts:86:16)
    at handler (C:\Users\johan\Programming\SBRENT-Payload\node_modules\payload\src\globals\requestHandlers\update.ts:18:22)

`

## Other Details
Payload v1.3.4

**Comment by jmikrut** [comment]
Hey @johannesschaffer — thank you for the report! This is fixed in the above PR and will be merged / released shortly.
