### ISSUE TITLE
Since 1.6.0: Local API `findGlobal` fails.

### ISSUE THREAD

**Issue by adiba** [payloadcms/payload#2018]
# Bug Report
The following code (in `seed.ts`) worked on `1.5.9`, but failed on `1.6.0`:
```js
await payload.findGlobal({
    slug: 'contact_details'
});
```
The error:
```
TypeError: Cannot read properties of undefined (reading 'localization')
    at findOneLocal (C:\Users\...\node_modules\payload\src\globals\operations\local\findOne.ts:28:29)
    at Payload.BasePayload.findGlobal (C:\Users\...\node_modules\payload\src\payload.ts:342:12)
    at C:\Users\...\src\seed.ts:53:59
    at step (C:\Users\...\src\seed.ts:33:23)
    at Object.next (C:\Users\...\src\seed.ts:14:53)
    at C:\Users\...\src\seed.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\...\src\seed.ts:4:12)
    at createPages (C:\Users\...\src\seed.ts:68:12)
    at Object.<anonymous> (C:\Users\...\src\seed.ts:71:1)
```

**Comment by ametis70** [comment]
I have the same issue with `paload.updateGlobal`. Passing `locale` seems to fix the issue in my case, but it still fails afterwards because  `payload.globals.config` does not exist: 

```
/home/node/app/node_modules/payload/dist/globals/operations/local/update.js:13
    const globalConfig = payload.globals.config.find((config) => config.slug === globalSlug);
                                         ^

TypeError: Cannot read properties of undefined (reading 'config')
    at updateLocal (/home/node/app/node_modules/payload/dist/globals/operations/local/update.js:13:42)
    at BasePayload.updateGlobal (/home/node/app/node_modules/payload/dist/payload.js:130:20)
    at /home/node/app/dist/seed/seeder.js:55:60
    at step (/home/node/app/dist/seed/seeder.js:33:23)
    at Object.next (/home/node/app/dist/seed/seeder.js:14:53)
    at /home/node/app/dist/seed/seeder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/node/app/dist/seed/seeder.js:4:12)
    at seed (/home/node/app/dist/seed/seeder.js:52:33)
    at Object.<anonymous> (/home/node/app/dist/seed/seeder.js:68:1)
```

**Comment by ametis70** [comment]
Oh, I just realized that `payload.init()` returns a promise in `^1.6.0`, so it should be awaited before calling `payload.updateGlobal`. That fixed my issue, but I don't know if it applies to `findGlobal` too. You can try that too @adiba if you're not doing that already. If this is the case, maybe a warning could be printed if payload wasn't initialized yet

**Comment by adiba** [comment]
Yes, true, I noticed that too, thank you!
Unfortunately, that's a breaking change...
A warning would indeed be helpful.

**Comment by jmikrut** [comment]
Hey all, yes, @ametis70 is correct. The `payload.init` method is now async and has been documented as a breaking change, including how to migrate, in our [changelog](https://github.com/payloadcms/payload/blob/master/CHANGELOG.md) and on the [GitHub release](https://github.com/payloadcms/payload/releases/tag/v1.6.1) page.

However, I will leave this issue open until we try and recreate the original issue in this thread. Will report back shortly!

**Comment by PatrikKozak** [comment]
Hey @adiba, @ametis70, @jmikrut - I was able to recreate the original issue. I tested it out and as mentioned by @ametis70 and @jmikrut - awaiting `payload.init()` will solve the original issue. If you have any other questions, let us know!
