### ISSUE TITLE
Payload version upgrade problem

### ISSUE THREAD

**Issue by dberhane** [payloadcms/payload#2044]
# Bug Report

I just upgraded Payloadcms from version 1.3.0 to 1.6.6 and I am getting the following error message when I run payloadcms. I am getting the error attached below.

It looks like the latest version does not support field names with empty spaces?

/payloadcms/learn-payload/node_modules/graphql/type/assertName.js:31
      throw new _GraphQLError.GraphQLError(
            ^
GraphQLError: Names must only contain [_a-zA-Z0-9] but "article url" does not.
    at assertName (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/assertName.js:31:13)
    at /home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/definition.js:798:40
    at mapValue (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/jsutils/mapValue.js:16:19)
    at defineFieldMap (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/definition.js:772:33)
    at GraphQLObjectType._fields (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/definition.js:691:26)
    at GraphQLObjectType.getFields (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/definition.js:710:27)
    at collectReferencedTypes (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/schema.js:387:51)
    at collectReferencedTypes (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/schema.js:388:9)
    at new GraphQLSchema (/home/db/projects/payloadcms/learn-payload/node_modules/graphql/type/schema.js:179:7)
    at registerSchema (/home/db/projects/payloadcms/learn-payload/node_modules/payload/src/graphql/registerSchema.ts:75:20)

## Steps to Reproduce

1. Edited package.json file and updated Payloadcms from version 1.3.0 to 1.6.6 
2. yarn install
3. yarn dev (generates the above error)

**Comment by jmikrut** [comment]
Hey @dberhane — I can give some info here.

I'm honestly surprised that the field name `article url` ever worked at all - field names should be camel-cased. GraphQL is pretty strict with how their names are generated.

One note is that in 1.2.0, we released changes to the way that GraphQL field names are generated. We used to rely on the "label" of collections, globals, and fields - but now rely on the slug / name itself. There are escape hatches that you can use if you want to preserve your name and have GraphQL still work, by defining the GraphQL names manually.

See here for more info:
https://github.com/payloadcms/payload/blob/master/CHANGELOG.md#-breaking-changes-1

But this is expected behavior. I would personally change the name of your field, and if necessary, run a simple migration script to transform your documents into a shape with more consistent / expected field names.

Here's an example of a migration script you could look at as a starter point:
https://github.com/payloadcms/payload/discussions/434

**Comment by dberhane** [comment]
Thank you @jmikrut for your prompt response. I am not using Graphql at the moment, just using the REST API. Is there a way of disabling it?
