### ISSUE TITLE
Opening versions for a collection document crashes the admin UI

### ISSUE THREAD

**Issue by calvinl** [payloadcms/payload#2228]
# Bug Report

After following the migration steps outlined in the changelog (going from `1.5.4` to `1.6.16`), I was able to get the admin UI up and running (with some deep debugging related to the new way payload.config is treated with `tsconfig`), but ran into one last issue I'm stumped about. When I click on the `N versions` link inside of a collection document, the admin UI crashes with the following error:

```js
index.js:13 Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at Table (index.js:13:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

Stepping into the the line of code via inspector I see the following (code pasted below):
<img width="737" alt="Screen Shot 2023-03-02 at 11 31 08 PM" src="https://user-images.githubusercontent.com/490687/222631865-a9f79724-9594-4327-b00f-757e7f0844fc.png">

```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Table = void 0;
const react_1 = __importDefault(require("react"));
const TableColumns_1 = require("../TableColumns");
require("./index.scss");
const baseClass = 'table';
const Table = ({ data }) => {
    const { columns, } = (0, TableColumns_1.useTableColumns)();
    const activeColumns = columns.filter((col) => col.active);
    if (!activeColumns || activeColumns.length === 0) {
        return (react_1.default.createElement("div", null, "No columns selected"));
    }
    return (react_1.default.createElement("div", { className: baseClass },
        react_1.default.createElement("table", { cellPadding: "0", cellSpacing: "0" },
            react_1.default.createElement("thead", null,
                react_1.default.createElement("tr", null, activeColumns.map((col, i) => (react_1.default.createElement("th", { key: i, id: `heading-${col.accessor}` }, col.components.Heading))))),
            react_1.default.createElement("tbody", null, data && data.map((row, rowIndex) => (react_1.default.createElement("tr", { key: rowIndex, className: `row-${rowIndex + 1}` }, columns.map((col, colIndex) => {
                const { active } = col;
                if (!active)
                    return null;
                return (react_1.default.createElement("td", { key: colIndex, className: `cell-${col.accessor}` }, col.components.renderCell(row, row[col.accessor])));
            }))))))));
};
exports.Table = Table;
exports.default = exports.Table;
//# sourceMappingURL=index.js.map
```

## Steps to Reproduce

Honestly, I'm not sure. I can say that this lives in an nx monorepo which has presented some problems but most have been manageable. More details below

## Other Details

The issue I had previous to this was similar, in that the payload config wasn't loading properly on the client-side admin UI. There was an issue with my tsconfig which caused the import here: [https://github.com/payloadcms/payload/blob/master/src/admin/Root.tsx#L3](https://github.com/payloadcms/payload/blob/master/src/admin/Root.tsx#L3) to show up as `incomingConfig.default` rather than `incomingConfig`, which is a promise that needs to be `await`ed. After resolving that, I haven't been able to figure this one out, but wondering if it could be a similar issue? 

Here is my tsconfig:

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "strict": false,
    "outDir": "../../dist",
    "rootDir": "./src",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "jsx": "react"
  },
  "exclude": ["./test/**/*", "jest.config.ts", "build"],
  "include": ["src"],
  "ts-node": {
    "swc": true
  }
}

```

**Comment by jacobsfletch** [comment]
@calvinl a fix for this is incoming shortly! Thank you for the fine detail here, it's very helpful 🙌
