### ISSUE TITLE
useListDrawer throw an error

### ISSUE THREAD

**Issue by qasimali09** [payloadcms/payload#2292]
formatFields.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
    at formatFields (formatFields.js:5:1)
    at DrawerContent.js:68:1
    at mountState (react-dom.development.js:16986:1)
    at Object.useState (react-dom.development.js:17699:1)
    at useState (react.development.js:1622:1)
    at ListDrawerContent (DrawerContent.js:68:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)

**Comment by JarrodMFlesch** [comment]
What version of payload are you on? I believe this is fixed on latest

**Comment by qasimali09** [comment]
> What version of payload are you on? I believe this is fixed on latest

I latest version

**Comment by JarrodMFlesch** [comment]
@qasimali09 this will has been fixed and will be available in the next release 👍
