### ISSUE TITLE
New collections error generating payload types or run dev

### ISSUE THREAD

**Issue by pcbal** [payloadcms/payload#2319]
# Bug Report

After new update to 1.6.19 adding collections like categories, tags etc conflicts with plugins sucha s seo, nested-docs etc.

## Steps to Reproduce
Update payload to latest. Add collections Categories.ts and Tags.ts update payload.config try to generate types.

Terminal output before (error) and after (working) removing new collections.
`❯ yarn dev
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts`
[21:39:38] INFO (payload): Connected to Mongo server successfully!
[21:39:38] INFO (payload): Starting Payload...
TypeError: Cannot read properties of undefined (reading 'slug')
    at /home/bal/projects/payload/master/back/node_modules/@payloadcms/plugin-seo/src/index.ts:77:34
    at Array.map (<anonymous>)
    at /home/bal/projects/payload/master/back/node_modules/@payloadcms/plugin-seo/src/index.ts:76:38
    at /home/bal/projects/payload/master/back/node_modules/payload/src/config/build.ts:16:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/bal/projects/payload/master/back/node_modules/payload/src/config/build.ts:15:35
    at buildConfig (/home/bal/projects/payload/master/back/node_modules/payload/src/config/build.ts:13:32)
    at loadConfig (/home/bal/projects/payload/master/back/node_modules/payload/src/config/load.ts:26:32)
    at BasePayload.init (/home/bal/projects/payload/master/back/node_modules/payload/src/payload.ts:187:21)
    at getPayload (/home/bal/projects/payload/master/back/node_modules/payload/src/payload.ts:411:22)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/server.ts`
[21:40:41] INFO (payload): Connected to Mongo server successfully!
[21:40:41] INFO (payload): Starting Payload...
[21:40:48] INFO (payload): Payload Admin URL: /admin
[21:40:49] INFO (payload): Server listening on port 8000
webpack built 4e083168bace052d2efe in 4946ms
webpack compiled successfully
`

1.
2.
3.

**Comment by pcbal** [comment]
> 

May be closed. Import method from import  {Tags}  from './collections/Tags' to import  Tags  from './collections/Tags' solved the issue.
