### ISSUE TITLE
"Error: Cannot set headers after they are sent to the client" happens if I use "payload.authenticate" middleware and make network request in handler using fetch/axios.

### ISSUE THREAD

**Issue by ArnabXD** [payloadcms/payload#2328]
# Bug Report

I was trying to proxy google places autocomplete api for authenticated users, and I am facing this error :

```log
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (D:\node\truck\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (D:\node\truck\node_modules\express\lib\response.js:174:12)
    at ServerResponse.json (D:\node\truck\node_modules\express\lib\response.js:278:15)
    at D:\node\truck\src\handlers\autocomplete.ts:31:19
    at step (D:\node\truck\src\handlers\autocomplete.ts:33:23)
    at Object.next (D:\node\truck\src\handlers\autocomplete.ts:14:53)
    at fulfilled (D:\node\truck\src\handlers\autocomplete.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

If I don't make the places api call (and remove properties from response) or disable the `payload.authenticate` middleware then it is working fine, I can't call the api and use `payload.authenticate` middleware together.

### Code :
```ts
// File path - /handlers/autocomplete.ts
import { Handler } from "express";
import qs from "querystring";
import axios from "axios";

export const autocomplete: Handler = async (req, res) => {
  if (!req.user) {
    res.status(401).json({
      errors: [{ message: "You are not authorized to perform this action" }],
    });
    return;
  }

  if (!req.query.input) {
    res.json({
      errors: [{ message: "Please provide a valid input" }],
    });
    return;
  }

  const query = qs.stringify({
    input: req.query.input as string,
    key: process.env.PLACES_API_KEY,
  });

  // I tried both axios and fetch (node 18)
  const { data } = await axios.get(
    "https://maps.googleapis.com/maps/api/place/autocomplete/json?" + query
  );

  res.status(200).json({
    ...data,
    message: "success",
  });
};
```
```ts
// File path -  server.ts
require("dotenv").config();

import express from "express";
import payload from "payload";
import { autocomplete } from "./handlers/autocomplete";

const app = express();

// Redirect root to Admin panel
app.get("/", (_, res) => {
  res.redirect("/admin");
});

const start = async () => {
  // Initialize Payload
  await payload.init({
    secret: process.env.PAYLOAD_SECRET,
    mongoURL: process.env.MONGODB_URI,
    express: app,
    onInit: async () => {
      payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`);
    },
  });

  // 
  app.get("/api/autocomplete", payload.authenticate, autocomplete);

  app.listen(process.env.PORT || 3000);
};

start();
```

# Environment
- System : Win11
- NodeJS : `16.19.1`, `18.11.0`
- Payload : `1.6.19`

## Steps to Reproduce

1. 
2.
3.

**Comment by ArnabXD** [comment]
I noticed `payload.authenticate` is already being used under the hood somewhere while making rest call on `/api/autocomplete` so I just stopped adding it again as a middleware and everything works fine.

**Comment by DanRibbens** [comment]
It sounds like you resolved your own issue, so I'm going to close this.

What you found is correct, any requests going to your Payload `/api` gets the default middleware that Payload uses, including authentication.

Alternatively you could do the same thing in your Payload config if you wanted by using custom endpoints with the `root` option to bypass middleware: https://payloadcms.com/docs/rest-api/overview#custom-endpoints
