### ISSUE TITLE
"Cast to ObjectId failed" error when trying to reset password via local or REST API

### ISSUE THREAD

**Issue by hjbugajski** [payloadcms/payload#2805]
### Link to reproduction

https://github.com/hjbugajski/payload/tree/bug/reset-password

### To Reproduce

1. Run the test [created here](https://github.com/hjbugajski/payload/blob/bug/reset-password/test/_community/int.spec.ts#L74).

or

1. Create new project using `npx create-payload-app` and install `payload@1.8.6` or above.
2. Create initial user.
3. Add an `afterChange` hook in the `Users` collection to reset the password on save.
    ```typescript
    const afterChangeHook: CollectionAfterChangeHook = async ({ doc, operation, req, }) => {
      if (operation === "update") {
        const { email } = doc;

        try {
          const token = await req.payload.forgotPassword({
            collection: "users",
            data: {
              email,
            },
            disableEmail: true,
            req,
          });

          // failing here
          await req.payload.resetPassword({
            collection: "users",
            data: {
              password: "password",
              token,
            },
            overrideAccess: true,
            req,
          });
        } catch (error) {
          console.error(error);
        }
      }
    };
    ````
4. Edit the user's email address.
5. Check the logs in the docker container.

### Describe the Bug

A `Cast to ObjectId failed` error occurs after calling `payload.resetPassword` or the REST endpoint `/api/{collection}/reset-password` on a collection with auth enabled.

Occurs in `1.8.6` or above, functionality works as expected in `1.8.5` and below (tested down to `1.8.3`).

### Full error output
```
CastError: Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "users"
    at model.Query.exec (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/query.js:4789:21)
    at model.Query.Object.<anonymous>.Query.then (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/query.js:4888:15) {
  messageFormat: undefined,
  stringValue: '"{ _id: undefined }"',
  kind: 'ObjectId',
  value: { _id: undefined },
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new BSONTypeError (/Users/henry/dev/misc/payload/node_modules/bson/src/error.ts:16:5)
      at new ObjectId (/Users/henry/dev/misc/payload/node_modules/bson/src/objectid.ts:88:15)
      at castObjectId (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.Object.<anonymous>.ObjectId.cast (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/schema/objectid.js:246:12)
      at ObjectId.Object.<anonymous>.SchemaType.applySetters (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/schematype.js:1192:12)
      at ObjectId.Object.<anonymous>.SchemaType._castForQuery (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/schematype.js:1635:15)
      at ObjectId.Object.<anonymous>.SchemaType.castForQuery (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/schematype.js:1623:15)
      at ObjectId.Object.<anonymous>.SchemaType.castForQueryWrapper (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/schematype.js:1599:20)
      at cast (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/cast.js:288:34)
      at model.Query.Object.<anonymous>.Query.cast (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/query.js:5211:12)
      at castQuery (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/query.js:5014:18)
      at model.Query.Object.<anonymous>.Query._findAndModify (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/query.js:3889:23)
      at model.Query.<anonymous> (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/query.js:3422:8)
      at model.Query._wrappedThunk [as _findOneAndUpdate] (/Users/henry/dev/misc/payload/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
      at /Users/henry/dev/misc/payload/node_modules/kareem/index.js:334:18
      at _next (/Users/henry/dev/misc/payload/node_modules/kareem/index.js:128:16)
      at /Users/henry/dev/misc/payload/node_modules/kareem/index.js:555:30
      at processTicksAndRejections (node:internal/process/task_queues:77:11),
  valueType: 'Object'
}
```

### Payload Version

1.8.6

**Comment by JarrodMFlesch** [comment]
@hjbugajski Looking into this now. Just wanted to say that the repro with the failing test is so helpful to get moving on a fix quicky, so thank you!

**Comment by JarrodMFlesch** [comment]
PR is open [here](https://github.com/payloadcms/payload/pull/2808) 🎉

**Comment by elilemons** [comment]
I was also running into this bug and super appreciate the fast fix. Y'all are the best!
