### ISSUE TITLE
input without onChange handler warning

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#3243]
### Link to reproduction

private repo

### To Reproduce

Lunch the admin panel and chech the JavaScript console:

```
Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at div
    at div
    at CheckboxInput (http://localhost:3000/admin/main.js:104291:13)
    at SelectAll (http://localhost:3000/admin/main.js:117702:54)
    at th
    at tr
    at thead
    at table
    at div
    at Table (http://localhost:3000/admin/main.js:99695:18)
    at RelationshipProvider (http://localhost:3000/admin/main.js:117577:33)
    at div
    at http://localhost:3000/admin/main.js:96795:13
    at SelectionProvider (http://localhost:3000/admin/main.js:117784:30)
    at div
    at DefaultList (http://localhost:3000/admin/main.js:117472:13)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:113392:13)
    at TableColumnsProvider (http://localhost:3000/admin/main.js:99954:33)
    at ListView (http://localhost:3000/admin/main.js:117997:13)
    at Route (http://localhost:3000/admin/main.js:177885:29)
    at Switch (http://localhost:3000/admin/main.js:178087:29)
    at div
    at div
    at Default (http://localhost:3000/admin/main.js:112182:20)
    at Route (http://localhost:3000/admin/main.js:177885:29)
    at Switch (http://localhost:3000/admin/main.js:178087:29)
    at Route (http://localhost:3000/admin/main.js:177885:29)
    at Suspense
    at Routes (http://localhost:3000/admin/main.js:94168:64)
    at CustomProvider (http://localhost:3000/admin/main.js:112576:27)
    at LoadingOverlayProvider (http://localhost:3000/admin/main.js:113004:35)
    at StepNavProvider (http://localhost:3000/admin/main.js:99641:28)
    at LocaleProvider (http://localhost:3000/admin/main.js:113136:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:113443:33)
    at ThemeProvider (http://localhost:3000/admin/main.js:113508:26)
    at PreferencesProvider (http://localhost:3000/admin/main.js:113327:32)
    at AuthProvider (http://localhost:3000/admin/main.js:112278:25)
    at ModalProvider (http://localhost:3000/admin/main.js:7857:29)
    at Router (http://localhost:3000/admin/main.js:177504:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:176609:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:8553:26)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:8830:29)
    at ConfigProvider (http://localhost:3000/admin/main.js:112529:27)
    at Root
```

### Describe the Bug

Warning from React.

### Payload Version

1.15.2

**Comment by cbratschi** [comment]
Happens here: https://github.com/payloadcms/payload/blob/2c7a15ceca893b4789aaa3d587293918b67cc163/src/admin/components/forms/field-types/Checkbox/Input.tsx#L46

**Comment by pooledge** [comment]
My guess it also prevents from extending richText's `admin.link.fields` like this:
```ts
...
fields: ({ defaultFields }) => {
		return [
			{
				type: 'tabs',
				tabs: [
					{
						label: 'Default',
						fields: defaultFields,
					},
					{
						label: 'UI',
						fields: [
							{
								label: 'Link is a button',
								type: 'checkbox',
								name: 'isButton',
							},
						],
					},
				],
			},
		];
	}
```

The `isButton` value is not being saved.
