### ISSUE TITLE
Field `group` broken after updating to version 2 (mongooseAdapter)

### ISSUE THREAD

**Issue by jm2097** [payloadcms/payload#3534]
### Link to reproduction

https://stackblitz.com/~/github.com/jm2097/payload2-group-field-reproduction

## For a new project

1. Create a new project using `create-payload-app`.
2. Add some collection.
3. Create three fields: an array, a nested group and any other field within the group:
    ```ts
    {
      type: "array",
      name: "someArray",
      fields: [
        {
          type: "group",
          name: "someGroup",
          fields: [
            {
              type: "text",
              name: "someText",
            },
          ],
        },
      ],
    }
    ```
4. Fill in the group fields, attempt to save, and observe the error.

### Describe the Bug

After updating to version 2, an unhandled server error occurs when attempting to save a collection. This issue arises specifically when the collection contains a field of type array, which includes a field of type group.

> [!NOTE]
> This exact same configuration was working fine on version [1.15.6](https://www.npmjs.com/package/payload/v/1.15.6)

![image](https://github.com/payloadcms/payload/assets/64181348/3c156f41-7620-4c94-8cd1-73204dddc552)
![image](https://github.com/payloadcms/payload/assets/64181348/25939143-2e8d-444e-9f17-32a5a22a807a)

**Error logs:**

```sh
[01:59:30] ERROR (payload): CastError: Cast to embedded failed for value "{
  'link.type': { passesCondition: true, valid: true },
  'link.url': { passesCondition: true, valid: true },
  id: '6524afff982afd4f8d523345',
  link: { url: 'test', type: 'internal' }
}" (type Object) at path "links" because of "CastError"
    at model.Query.exec (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/query.js:4921:21)
    at model.Query.Query.then (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/query.js:5020:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```sh
[02:07:24] ERROR (payload): ValidationError: events validation failed: links.0.link.type: Cast to string failed for value "{ passesCondition: true, valid: true }" (type Object) at path "type", links.0.link.url: Cast to string failed for value "{ passesCondition: true, valid: true }" (type Object) at path "url"
    at model.Document.invalidate (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/document.js:3165:32)
    at EmbeddedDocument.Subdocument.invalidate (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/types/subdocument.js:225:12)
    at SingleNested.Subdocument.invalidate (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/types/subdocument.js:225:12)
    at SingleNested.$set (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/document.js:1466:12)
    at SingleNested.set [as type] (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/helpers/document/compile.js:204:19)
    at EmbeddedDocument.Document.$__set (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/document.js:1710:23)
    at EmbeddedDocument.$set (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/document.js:1488:10)
    at EmbeddedDocument.$set (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/document.js:1149:16)
    at EmbeddedDocument.Document (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/document.js:164:12)
    at EmbeddedDocument.Subdocument (/home/juan/Desktop/payload2/node_modules/.pnpm/mongoose@6.11.4/node_modules/mongoose/lib/types/subdocument.js:31:12)
```

### Payload Version

2.0.3

**Comment by JarrodMFlesch** [comment]
Hey @jm2097 thanks for bringing this to our attention. I will take a look and add tests to prevent this going forward 👍

**Comment by JarrodMFlesch** [comment]
Hey @jm2097 this was fixed in https://github.com/payloadcms/payload/issues/3534 and will be available in the next release.

**Comment by diesieben07** [comment]
This is still partially broken in `payload@2.0.4`.
Reproduction: https://github.com/diesieben07/payload-transactions-demo

In the pages collection create a new "Some Array" entry. This works now.
Duplicating or removing an array entry however still results in this same issue.
