### ISSUE TITLE
Payload 2.0 with Postgres -  website template seeding error

### ISSUE THREAD

**Issue by junteudjio** [payloadcms/payload#3568]
### Link to reproduction

NA

### To Reproduce

1. npx install Payload website template 
2. choose postgres during install process
3. edit .env file to point to postgres URI
4. yarn dev to start the app
5. visit localhost:3000/admin and create first user
6. click seed database after login from previous step
7. ui says seeding succeeded but network tab shows error

### Describe the Bug

The seeding process fails with error:
{"error":"inArray requires at least one value"}

Error Log in console:
```

[07:12:57] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'referencedTable')
    at normalizeRelation (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/relations.ts:428:55)
    at PgDialect.buildRelationalQueryWithoutPK (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/pg-core/dialect.ts:1106:32)
    at PgDialect.buildRelationalQueryWithoutPK (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/pg-core/dialect.ts:1118:32)
    at /Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/pg-core/query-builders/query.ts:105:31
    at Object.startActiveSpan (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/tracing.ts:27:11)
    at QueryPromise._prepare (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/pg-core/query-builders/query.ts:83:17)
    at /Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/pg-core/query-builders/query.ts:139:16
    at Object.startActiveSpan (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/tracing.ts:27:11)
    at QueryPromise.execute (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/pg-core/query-builders/query.ts:138:17)
    at QueryPromise.then (/Users/junior/LocalRoot/Dev/repos/my-projects/dummyproject-repos/payload-dummyproject/node_modules/src/query-promise.ts:31:15)
```

### Payload Version

2.0

**Comment by getakalabs-christarroja** [comment]
Confirming that I can reproduce this error as well. The console logs this when pressing the seed link:
`[07:39:39] INFO (payload): Seeding database...
[07:39:39] INFO (payload): — Clearing media...
[07:39:39] INFO (payload): — Clearing collections and globals...
[07:39:39] ERROR (payload): inArray requires at least one value`

**Comment by junteudjio** [comment]
hi @DanRibbens , thanks for looking into this. 
just FYI there is also a problem with the seeding logic when using mongo.

```
[18:49:23] INFO (payload): Seeding database...
[18:49:23] INFO (payload): — Clearing media...
[18:49:23] INFO (payload): — Clearing collections and globals...
[18:49:24] INFO (payload): — Seeding demo author and user...
[18:49:26] INFO (payload): — Seeding media...
[18:49:27] INFO (payload): — Seeding categories...
[18:49:28] ERROR (payload): The requested resource was not found.
```

**Comment by andersonfpcorrea** [comment]
@junteudjio @DanRibbens, I had the same problem when trying to seed from the admin page:
![image](https://github.com/payloadcms/payload/assets/92505216/3401a20a-4608-42ae-81fd-46f4b620174e)

![image](https://github.com/payloadcms/payload/assets/92505216/a34b82aa-ca98-45b5-aeb8-1c11740cd05f)


I was using Atlas (not sure if that's the issue - I did not test with a local MongoDB) and the _e-commerce_ template.

I also tried to use `yarn seed` but without success. There was a "WriteConflict":
![image](https://github.com/payloadcms/payload/assets/92505216/322b9852-9732-4a73-a172-a0bd4e66bfd3)

Then I refactored the code from `src/payload/seed/index.ts` to make all operations sequentially instead of using `Promise.all`, and the "WriteConflict" error was gone, but then there was this one:
![image](https://github.com/payloadcms/payload/assets/92505216/c23450dc-0da0-4e4f-a969-0e75606884e5)

Is this expected when working with Atlas? I'll try with a local instance of MongoDB when I have a chance.

**Comment by junteudjio** [comment]
@andersonfpcorrea , that's exactly the setup I tried in my most recent comment: Payload 2.0  website template + Mongodb Atlas and got all the issues you pointed out. The seeding logic fails whether you run it from CLI or click the link in the admin dashboard.

**Comment by getakalabs-christarroja** [comment]
I don't have this problem using MongoDB. Only w/ postgres. Seems like there's a redundancy going on, or possibly a key mismatch

**Comment by DanRibbens** [comment]
For mongoDB are you connecting using a replicaSet? I am thinking there is an issue with the transactions, which this PR aims to address in this https://github.com/payloadcms/plugin-nested-docs/pull/29.

For postgres, transactions are also an issue so that PR is important to get released. Additionally, the PR linked above solves an issue for the field structure needed.
