### ISSUE TITLE
Postgres: sorting with drafts enabled not working

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#3572]
### Link to reproduction

https://github.com/janisvb/payload-reproduction/tree/sorting

### To Reproduce

```
export PAYLOAD_DATABASE=postgres
yarn dev _community
```
Then open http://localhost:3000/api/posts?depth=0&draft=true&limit=10&sort=text

### Describe the Bug

Payload throws the following error:

```
APIError: Cannot find field for path at text
    at getTableColumnFromPath (/packages/db-postgres/src/queries/getTableColumnFromPath.ts:415:9)
    at buildQuery (/packages/db-postgres/src/queries/buildQuery.ts:67:89)
    at find (/packages/db-postgres/src/find/findMany.ts:44:80)
    at Object.queryDrafts (/packages/db-postgres/src/queryDrafts.ts:25:32)
    at find (/packages/payload/src/collections/operations/find.ts:123:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async findHandler (/packages/payload/src/collections/requestHandlers/find.ts:30:20)
```

### Payload Version

2.0.4

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by jmikrut** [comment]
Hey @Janisvb — on it. Thank you for the report!

**Comment by DanRibbens** [comment]
I started a fix for this but we need to review how this should be done so that we can maintain consistency between how mongodb and postgres work.
https://github.com/payloadcms/payload/tree/fix/sort-versions

Will update again soon.
