### ISSUE TITLE
Webpack cannot resolve Payload package in Yarn workspace

### ISSUE THREAD

**Issue by joas8211** [payloadcms/payload#3661]
### Link to reproduction

https://github.com/joas8211/payload-webpack-bug

### To Reproduce

1. Clone reproduction 
2. Install dev dependencies using command `yarn install`.
3. Run build using command `yarn build`.

### Describe the Bug

It seems that Webpack is now looking for "payload" package from the subproject's node_modules folder, although the files exist workspace's node_modules folder. The problem appeared after updating @payloadcms/bundler-webpack to version 1.0.3 

Build output:
```
yarn run v1.22.19
$ yarn workspace payload-webpack-bug build
$ yarn copyfiles && yarn build:payload && yarn build:server
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
$ cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build
[12:30:09] INFO (payload): Starting Payload...
assets by status 11.4 KiB [cached] 2 assets
runtime modules 28.3 KiB 10 modules

ERROR in main
Module not found: Error: Can't resolve '/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin' in '/home/joas/files/projects/web/payload-webpack-bug/packages/buggy'
resolve '/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin' in '/home/joas/files/projects/web/payload-webpack-bug/packages/buggy'
  using description file: /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    root path /home/joas/files/projects/web/payload-webpack-bug/packages/buggy
      using description file: /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/package.json (relative path: ./home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin)
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.tsx doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.json doesn't exist
        as directory
          /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin doesn't exist
    using description file: /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/package.json (relative path: ./node_modules/payload/dist/admin)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.tsx doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin.json doesn't exist
      as directory
        /home/joas/files/projects/web/payload-webpack-bug/packages/buggy/node_modules/payload/dist/admin doesn't exist

webpack 5.89.0 compiled with 1 error in 238 ms
$ tsc
Done in 5.55s
```

### Payload Version

2.0.6

### Adapters and Plugins

@payloadcms/bundler-webpack@1.0.3, @payloadcms/db-mongodb@1.0.3, @payloadcms/plugin-cloud@2.2.5, @payloadcms/richtext-slate@1.0.5

**Comment by tyteen4a03** [comment]
Workaround for now: Set `nmHoistingLimits: workspaces` in `.yarnrc`

**Comment by denolfe** [comment]
Need to make this more of a complete fix https://github.com/payloadcms/payload/commit/65cdf6bfd0578bc8949552d89a8d17ebe0177051

**Comment by tyteen4a03** [comment]
After removing the workaround, I'm still getting issues:

```

/Users/tyteen4a03/Documents/CodeProjects/Crisis/christmas-js/node_modules/react-router-navigation-prompt/es/index.js:300
exports.default = (0, _reactRouterDom.withRouter)(NavigationPrompt);
                                                 ^
TypeError: (0 , _reactRouterDom.withRouter) is not a function
    at Object.<anonymous> (/Users/tyteen4a03/Documents/CodeProjects/Crisis/christmas-js/node_modules/react-router-navigation-prompt/es/index.js:300:50)
    at __webpack_require__ (/Users/tyteen4a03/Documents/CodeProjects/Crisis/christmas-js/node_modules/react-router-navigation-prompt/es/index.js:21:30)
    at /Users/tyteen4a03/Documents/CodeProjects/Crisis/christmas-js/node_modules/react-router-navigation-prompt/es/index.js:64:18
    at Object.<anonymous> (/Users/tyteen4a03/Documents/CodeProjects/Crisis/christmas-js/node_modules/react-router-navigation-prompt/es/index.js:67:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/Users/tyteen4a03/Documents/CodeProjects/Crisis/christmas-js/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)

```

**Comment by tyteen4a03** [comment]
Deleting `node_modules` seems to have solved the issue.
