### ISSUE TITLE
'column "version__status" cannot be cast automatically' after update to 2.0.10 (PostgreSQL)

### ISSUE THREAD

**Issue by DavidOliver** [payloadcms/payload#3732]
### Link to reproduction

None as yet

### To Reproduce

Use Payload 2.0.0/2.0.3 with PostgreSQL, use versions on a collection, and update to 2.0.10, from what I can gather.

### Describe the Bug

After updating to Payload 2.0.10:

```
$ npm run dev

> ac-payload@1.0.0 dev
> cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts -- -I`
✔ Warnings detected during schema push: 

· You're about to change version__status column type from enum__news_posts_v_version_version_status to enum__news_posts_v_version_status with 27 items

DATA LOSS WARNING: Possible data loss detected if schema is pushed.

Accept warnings and push schema to database? … yes
error: column "version__status" cannot be cast automatically to type enum__user_case_studies_v_version_status
    at /data/projects/ac/payload/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DrizzleORMPgClient.query (/data/projects/ac/payload/node_modules/drizzle-kit/utils.js:23330:21)
    at apply (/data/projects/ac/payload/node_modules/drizzle-kit/utils.js:40694:13)
    at Object.connect (/data/projects/ac/payload/node_modules/@payloadcms/db-postgres/src/connect.ts:80:3)
    at BasePayload.init (/data/projects/ac/payload/node_modules/payload/src/payload.ts:360:7)
    at getPayload (/data/projects/ac/payload/node_modules/payload/src/payload.ts:431:22)
    at initHTTP (/data/projects/ac/payload/node_modules/payload/src/initHTTP.ts:33:19)
    at Payload.init (/data/projects/ac/payload/node_modules/payload/src/index.ts:17:21)
[nodemon] app crashed - waiting for file changes before starting...
```

I'm using Postgres 16.

Collection config:

```typescript
import { CollectionConfig } from 'payload/types';
import { Access } from 'payload/config';
import * as auth from '../authorisation';

const canAdmin: Access = ({ req: { user } }) => auth.isAdmin(user);

const UserCaseStudies: CollectionConfig = {
  slug: 'user-case-studies',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'companyName'],
    disableDuplicate: true,
    listSearchableFields: ['title', 'companyName'],
    group: 'Website',
  },
  versions: {
    drafts: true,
  },
  access: {
    create: canAdmin,
    read: ({ req }) => {
      if (canAdmin({ req })) return true;
      return {
        _status: {
          equals: 'published',
        },
      };
    },
    update: canAdmin,
    delete: canAdmin,
    readVersions: canAdmin,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      index: true,
      required: true,
    },
    {
      name: 'companyName',
      type: 'text',
      required: true,
    },
    {
      name: 'publishCompanyName',
      type: 'checkbox',
    },
    {
      name: 'content',
      type: 'richText',
    },
    {
      name: 'publishDate',
      type: 'date',
      required: true,
      admin: {
        position: 'sidebar',
        description: 'The Case Study will be displayed only from this date onwards.',
        date: {
          pickerAppearance: 'dayOnly',
          displayFormat: 'd MMM yyy',
        },
      },
    },
  ],
};
```

As an aside, I've found that after using the create-payload-app npx command I've had to change payload in package.json from 'latest' to '^2.0.0' and use `npm install --force` to avoid Payload 1 being installed, which I think was due to peer dependencies of some of the other packages. I'm using npm.

### Payload Version

2.0.10

### Adapters and Plugins

db-postgres, bundler-webpack, richtext-lexical. Also, because they were installed by default (even though I chose pgsql): db-mongodb, plugin-cloud, richtext-slate.

**Comment by DavidOliver** [comment]
Fresh installation of 2.0.10 done, and all seems well. As I'm not confident it wasn't something I did, I'm closing the issue.

The generated/default contents of package.json seems more explicit/correct now, too. :+1: 

There was also a server error when trying to search for entries in relationships in Lexical before I updated, which also seems to have been fixed by a fresh installation. :)

**Comment by DavidOliver** [comment]
Continued: https://github.com/payloadcms/payload/issues/4677#issuecomment-2066931438
