### ISSUE TITLE
Does not work with GraphQL Schema Stitching

### ISSUE THREAD

**Issue by ikenox** [payloadcms/payload#3733]
### Link to reproduction

https://github.com/ikenox/payload/tree/does-not-work-with-graphql-stitched-schema

### To Reproduce

According to the reproduction-guide, I added a test case to reproduce.
Please execute `yarn test:int _community`.

#### Another example

I also created a minimum reproducible project.
https://github.com/ikenox/payload-examples/tree/does-not-work-with-graphql-stitched-schema

1. Start server

    ```shell
    git clone https://github.com/ikenox/payload-examples.git
    git checkout does-not-work-with-graphql-stitched-schema
    pnpm install
    pnpm dev
    ```

2. Access to `http://localhost:3000/merged-graphql` on browser to open GraphQL Playground
3. Send the following GraphQL query
    ```graphql
    query ExampleQuery {
      hello
      Users{
        docs {
          id
        }
      }
    }
    ```
4. An error response is returned

    ```json
    {
      "data": {
        "hello": "Hello world!",
        "Users": null
      },
      "errors": [
        {
          "message": "Cannot read properties of undefined (reading 'locale')",
          "path": [
            "Users"
          ],
          "extensions": {
            "code": "INTERNAL_SERVER_ERROR",
            "stacktrace": [
              "TypeError: Cannot read properties of undefined (reading 'locale')",
              "    at find (/Users/naoto.ikeno/repos/github.com/ikenox/payload-examples/node_modules/.pnpm/payload@2.0.10_typescript@4.9.5_webpack@5.89.0/node_modules/payload/src/collections/operations/find.ts:65:12)",
              "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
              "    at resolver (/Users/naoto.ikeno/repos/github.com/ikenox/payload-examples/node_modules/.pnpm/payload@2.0.10_typescript@4.9.5_webpack@5.89.0/node_modules/payload/src/collections/graphql/resolvers/find.ts:44:21)",
              "    at /Users/naoto.ikeno/repos/github.com/ikenox/payload-examples/node_modules/.pnpm/@graphql-tools+executor@1.2.0_graphql@16.8.1/node_modules/@graphql-tools/executor/cjs/execution/promiseForObject.js:18:35",
              "    at async Promise.all (index 1)"
            ]
          }
        }
      ]
    }
    ```

### Describe the Bug

I tried to merge my original GraphQL schema and PayloadCMS's GraphQL schema by [GraphQL Schema Stitching](https://the-guild.dev/graphql/stitching/docs) within one modular-monolithic express server.

I found that the payload instance has `schema` field, that seems to be executable `GraphQLSchema` object.
So I used it for schema stitching as below.

```typescript
import { makeExecutableSchema } from "@graphql-tools/schema";
import { stitchSchemas } from "@graphql-tools/stitch";
import express from "express";
import payload from "payload";
import { expressMiddleware } from "@apollo/server/express4";
import { ApolloServer } from "@apollo/server";

require("dotenv").config();
const app = express();

// Redirect root to Admin panel
app.get("/", (_, res) => {
  res.redirect("/admin");
});

const start = async () => {
  const payloadInstance = await payload.init({
    secret: process.env.PAYLOAD_SECRET,
    express: app,
    onInit: async () => {
      payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`);
    },
  });

  const schema1 = makeExecutableSchema({
    resolvers: { Query: { hello: () => "Hello world!" } },
    typeDefs: `type Query { hello: String }`,
  });
  const schema2 = payloadInstance.schema;

  const stitchedSchema = stitchSchemas({
    subschemas: [schema1, schema2],
  });
  const server = new ApolloServer({ schema: stitchedSchema });
  await server.start();

  app.use("/merged-graphql", express.json(), expressMiddleware(server));

  app.listen(3000);
};

start();
```

But this server returns an error `TypeError: Cannot read properties of undefined (reading 'locale')` when querying, as I described in "To Reproduce" section.

Actually I don't know if this is a bug or if there is another correct way to do schema stitching.

### Payload Version

2.0.10

**Comment by ikenox** [comment]
I found that just `new ApolloServer({ schema: payloadInstance.schema });` causes the same result, so GraphQL schema stitching is not essential for this issue.

**Comment by ikenox** [comment]
After investigation, I noticed that using schema directly is difficult because Payload's resolvers uses payload-specific request context values that are initialized by payload's express middleware. The `locale` appeared the described error is such one.
I'll close this issue because of I think this is not Payload's problem.
