### ISSUE TITLE
Connection terminated unexpectedly in pg module after a few minutes

### ISSUE THREAD

**Issue by BEpresent** [payloadcms/payload#3920]
### Describe the Bug

**Description**:

When deploying on railway.app and also running locally, the application starts successfully and operates as expected initially. However, after a few minutes, it throws an "Unhandled 'error' event" and terminates the connection unexpectedly. Both instances of the issue seem to originate from the pg module, which is used for PostgreSQL interactions. So it happens both locally `Connection terminated unexpectedly,` and on railway.app (`error code 57P01`). Sorry if these are two different issues, but both seem to originate from `pg` ? 

**Error Details**:

On railway.app (Node.js v18.17.1):

```
error: terminating connection due to administrator command
severity: 'FATAL',
code: '57P01',
file: 'postgres.c',
line: '3221',
routine: 'ProcessInterrupts'
Locally (Node.js v20.8.0):
```

```
Error: Connection terminated unexpectedly
Stack Trace:
The error traces back to /app/node_modules/pg-protocol/dist/parser.js on railway.app and localpath/node_modules/pg/lib/client.js locally.
```

**Observations**:
The application works as intended initially, but the described issue arises only after a few minutes of operation.

This here is the error log on railway.app:

```
node:events:492

throw er; // Unhandled 'error' event

^

error: terminating connection due to administrator command

at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)

at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)

at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)

at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)

at TLSSocket.emit (node:events:514:28)

at addChunk (node:internal/streams/readable:324:12)

at readableAddChunk (node:internal/streams/readable:297:9)

at Readable.push (node:internal/streams/readable:234:10)

at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

Emitted 'error' event on Client instance at:

at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:341:10)

at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:352:12)

at Connection.emit (node:events:514:28)

at /app/node_modules/pg/lib/connection.js:117:12

at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)

at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)

[... lines matching original stack trace ...]

at Readable.push (node:internal/streams/readable:234:10) {

length: 116,

severity: 'FATAL',

code: '57P01',

detail: undefined,

hint: undefined,

position: undefined,

internalPosition: undefined,

internalQuery: undefined,

where: undefined,

schema: undefined,

table: undefined,

column: undefined,

dataType: undefined,

constraint: undefined,

file: 'postgres.c',

line: '3221',

routine: 'ProcessInterrupts'

}

Node.js v18.17.1

error Command failed with exit code 1.

```

Locally I also get

```
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (.../node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:628:28)
    at Connection.emit (node:events:514:28)
    at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:63:12)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (.../node_modules/pg/lib/client.js:341:10)
    at Connection.<anonymous> (.../node_modules/pg/lib/client.js:150:16)
    at Object.onceWrapper (node:events:628:28)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:337:12)
```

### To Reproduce

My `payload.config.ts`
```
import path from "path";

import { postgresAdapter } from "@payloadcms/db-postgres";
import { lexicalEditor } from "@payloadcms/richtext-lexical"; // beta

import { buildConfig } from "payload/config";
import { webpackBundler } from "@payloadcms/bundler-webpack";
import Users from "./collections/Users";
import Post from "./collections/Post";
import { Media } from "./collections/Media";

export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: webpackBundler(), //webpackBundler(), viteBundler()
  },
  editor: lexicalEditor({}), // or slateEditor({})
  collections: [Users, Post, Media],
  typescript: {
    outputFile: path.resolve(__dirname, "payload-types.ts"),
  },
  graphQL: {
    // schemaOutputFile: path.resolve(__dirname, "generated-schema.graphql"),
    disable: true,
  },
  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI,
    },
  }),
});

```

### Payload Version

`^2.0.0`

### Adapters and Plugins

postgresAdapter, webpackBundler

**Comment by joschan21** [comment]
Got the same issue!

**Comment by jmikrut** [comment]
Hey @BEpresent and @joschan21 — this is a problem with your database, and is not something related to Payload itself. It appears your connection is closing for some reason. Is your database hosted on Railway? I would bring this up with them or see if you can Google the issue unrelated to Payload.

I am happy to continue to help here, but there is nothing actionable on Payload's side, so I will convert this to a discussion instead.

Thank you!
