### ISSUE TITLE
Build should not start payload (wasn't the case in v1)

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/payload#3942]
### Describe the Bug

Within the CI setup to check if the build would work. Enviroment variables like this should not be used on build time, cause i and probably most others set the on runtime. Either those where temporary used in v1, but not validated or the behavoir changed.

```
 > press-lalique@1.0.0 build:payload
> payload build

[07:17:11] INFO (payload): Starting Payload...
/app/node_modules/payload/dist/email/build.js:33
        throw new _errors.InvalidConfiguration('Email fromName and fromAddress must be configured when transport is configured');
              ^

InvalidConfiguration: Email fromName and fromAddress must be configured when transport is configured
    at ensureConfigHasFrom (/app/node_modules/payload/dist/email/build.js:33:15)
    at buildEmail (/app/node_modules/payload/dist/email/build.js:68:9)
    at BasePayload.init (/app/node_modules/payload/dist/payload.js:226:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getPayload (/app/node_modules/payload/dist/payload.js:259:26)
    at async initHTTP (/app/node_modules/payload/dist/initHTTP.js:39:21)
    at async Payload.init (/app/node_modules/payload/dist/index.js:27:25)
    at async build (/app/node_modules/payload/dist/bin/build.js:18:5) {
  data: null,
  isOperational: true,
  isPublic: false,
  status: 500
}
``

### To Reproduce

do not set env vars and run `npm run build` 

### Payload Version

2.0.14

### Adapters and Plugins

db-mongodb

**Comment by RickVM** [comment]
Yep, its quite annoying. Though I think I actually had it with v1 as well.

**Comment by jmikrut** [comment]
Hey @RickVM, @dominikzogg — we'll get this taken care of. We intentionally moved to initializing prior to building Payload's admin UI but I think we can work around it.

Give us a bit here to get back to you!

**Comment by dominikzogg** [comment]
@jmikrut i move the email config to payload.init instead of the normal config, no messages like that anymore so far.

**Comment by dominikzogg** [comment]
@jmikrut with this change we could move our projects to payload 2.0
