### ISSUE TITLE
Foreign key error when adding tenant to user in the multi tenant example

### ISSUE THREAD

**Issue by timoconnellaus** [payloadcms/payload#3983]
### Link to reproduction

https://github.com/timoconnellaus/payload-tenancy-test

### Describe the Bug

I have converted the mutli tenance example from the payload repo to postgresql and attempted to run it

The issue I experience occurs in two places:

1. When running the seed there will be mulitple errors related to inserting data into the DB
2. When adding a tenant to a user and setting their role a FK error will occur

error: insert or update on table "users_tenants_roles" violates foreign key constraint "users_tenants_roles_parent_id_users_tenants_id_fk"
    at /Users/tim/repos/payload-tenancy-test/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/tim/repos/payload-tenancy-test/node_modules/.pnpm/drizzle-orm@0.28.5_@libsql+client@0.3.6_pg@8.11.3/node_modules/src/node-postgres/session.ts:64:19
    at upsertRow (/Users/tim/repos/payload-tenancy-test/node_modules/.pnpm/@payloadcms+db-postgres@0.1.11_payload@2.0.14/node_modules/@payloadcms/db-postgres/src/upsertRow/index.ts:275:7)
    at Object.updateOne (/Users/tim/repos/payload-tenancy-test/node_modules/.pnpm/@payloadcms+db-postgres@0.1.11_payload@2.0.14/node_modules/@payloadcms/db-postgres/src/update.ts:66:18)
    at updateByID (/Users/tim/repos/payload-tenancy-test/node_modules/.pnpm/payload@2.0.14_@types+react@18.0.21_esbuild@0.18.20_typescript@4.8.4_webpack@5.89.0/node_modules/payload/src/collections/operations/updateByID.ts:262:16)
    at updateByIDHandler (/Users/tim/repos/payload-tenancy-test/node_modules/.pnpm/payload@2.0.14_@types+react@18.0.21_esbuild@0.18.20_typescript@4.8.4_webpack@5.89.0/node_modules/payload/src/collections/requestHandlers/updateByID.ts:36:17)

### To Reproduce

1. clone the linked repo
2. pnpm i
3. cp .env.example .env
4. set DATABASE_URL variable in env file
5. Set PAYLOAD_SEED variable to true
6. pnpm run dev - this will reproduce the issues on seed. Some data will be inserted but not all
7. set PAYLOAD_SEED variable to false
8. pnpm run dev - should start successfully
9. add a new user in the CMS and add a tenant to that user. Should see an error relating to FK relationships

### Payload Version

2.0.14

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by timoconnellaus** [comment]
Some more info on this. If you drop the FK relationship allowing the data to be inserted it looks like the table users_tenants_roles is attemping to set the FK to users id and not the users_tenants id. This would explain the FK error

ALTER TABLE users_tenants_roles
DROP CONSTRAINT users_tenants_roles_parent_id_users_tenants_id_fk;

SELECT * FROM users_tenants_roles
<img width="531" alt="image" src="https://github.com/payloadcms/payload/assets/3151605/e2f5543d-de14-4865-8997-7d4a8111926f">
Note: parent_id = 5

SELECT * FROM users_tenants
<img width="411" alt="image" src="https://github.com/payloadcms/payload/assets/3151605/f1293535-bdd0-489b-9ffb-47a75d57d6d1">
Note: id = 6544062d02479b2b7164ae1b
