### ISSUE TITLE
Cannot upload files on Payload 2.0.14

### ISSUE THREAD

**Issue by thompsonsj** [payloadcms/payload#3989]
### Describe the Bug

The following error appears in Payload Cloud logs/local console:

```


[2023-11-03T11:58:36] | (payload): FileUploadError: There was a problem while uploading the file.
-- | --
[2023-11-03T11:58:36] | at generateFileData (/workspace/node_modules/payload/dist/uploads/generateFileData.js:195:15)
[2023-11-03T11:58:36] | at async create (/workspace/node_modules/payload/dist/collections/operations/create.js:78:61)
[2023-11-03T11:58:36] | at async createHandler (/workspace/node_modules/payload/dist/collections/requestHandlers/create.js:24:21)
[2023-11-03T11:58:58] | TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[2023-11-03T11:58:58] | at Object.writeFile (node:internal/fs/promises:785:5)
[2023-11-03T11:58:58] | at generateFileData (/workspace/node_modules/payload/dist/uploads/generateFileData.js:164:44)
[2023-11-03T11:58:58] | at async create (/workspace/node_modules/payload/dist/collections/operations/create.js:78:61)
[2023-11-03T11:58:58] | at async createHandler (/workspace/node_modules/payload/dist/collections/requestHandlers/create.js:24:21) {
[2023-11-03T11:58:58] | code: 'ERR_INVALID_ARG_TYPE'
[2023-11-03T11:58:58] | }
```

Downgrading to 2.0.13 resolves the issue.

### To Reproduce

- Upgrade to the latest version of Payload at the time of writing: https://github.com/payloadcms/payload/releases/tag/v2.0.14
- Try uploading a file using Payload Cloud credentials locally or on production.

### Payload Version

2.0.14

### Adapters and Plugins

db-mongodb, bundler-webpack, plugin-cloud, plugin-seo, richtext-lexical, richtext-slate, payload-crowdin-sync

**Comment by denolfe** [comment]
Thank you for the report @thompsonsj . I was able to recreate this. Looking into a fix now.

**Comment by denolfe** [comment]
Regression due to https://github.com/payloadcms/payload/pull/3883

Affects any usage of `useTempFiles`, which plugin-cloud does utilize.
