### ISSUE TITLE
Payload Admin not working

### ISSUE THREAD

**Issue by iktusgame** [payloadcms/payload#400]
Hi, I just installed Payload only impossible to access the admin, I have directly react errors, I have to reinstall, switch between js and ts, nothing happens ... Any solution? Thanks.

```
Routes.js:25 Uncaught TypeError: Cannot read properties of undefined (reading 'canAccessAdmin')
    at Routes (Routes.js:25)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
Routes @ Routes.js:25
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonyme) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./node_modules/payload/dist/admin/index.js @ index.js:35
__webpack_require__ @ bootstrap:24
(anonyme) @ startup:5
(anonyme) @ startup:5
react-dom.development.js:20085 The above error occurred in the <Routes> component:

    at Routes (http://localhost:3000/admin/main.js:12833:90)
    at C (http://localhost:3000/admin/main.js:50636:37)
    at LocaleProvider (http://localhost:3000/admin/main.js:15577:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:15814:33)
    at PreferencesProvider (http://localhost:3000/admin/main.js:15726:32)
    at t.AuthProvider (http://localhost:3000/admin/main.js:3292:12361)
    at ModalProvider (http://localhost:3000/admin/main.js:2268:33)
    at Router (http://localhost:3000/admin/main.js:50010:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:49627:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:2821:28)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:3092:28)
    at t.ConfigProvider (http://localhost:3000/admin/main.js:3292:15978)
    at Index

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonyme) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./node_modules/payload/dist/admin/index.js @ index.js:35
__webpack_require__ @ bootstrap:24
(anonyme) @ startup:5
(anonyme) @ startup:5
Routes.js:25 Uncaught TypeError: Cannot read properties of undefined (reading 'canAccessAdmin')
    at Routes (Routes.js:25)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
```

**Comment by jmikrut** [comment]
Hey @iktusgame — you caught us in the middle of deploying a new version!

Give it another shot. A fresh install should be good to go now. Make sure to delete any `yarn.lock` or `package-lock.json` files you might have.

**Comment by iktusgame** [comment]
@jmikrut Oh, everything is now functional, thanks ;)
