### ISSUE TITLE
ERR_REQUIRE_ESM on build when using Yarn v1. Incorrect dep resolution.

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#4109]
### Link to reproduction

npx create-payload-app

### Describe the Bug

A blank template is unable to deploy on cloud. It appears to be caused by a dependency deep in the chain being ESM-only.

<img width="1009" alt="CleanShot 2023-11-11 at 20 57 41" src="https://github.com/payloadcms/payload/assets/65888/f8b330a0-cb5b-4ab5-b19d-4e6cdb58decd">

```
[2023-11-12 01:33:05] │ Running custom build command: yarn build
[2023-11-12 01:33:06] │ yarn run v1.22.19
[2023-11-12 01:33:06] │ $ yarn copyfiles && yarn build:payload && yarn build:server
[2023-11-12 01:33:06] │ $ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
[2023-11-12 01:33:07] │ /workspace/node_modules/cliui/build/index.cjs:291
[2023-11-12 01:33:07] │ const stringWidth = require('string-width');
[2023-11-12 01:33:07] │                     ^
[2023-11-12 01:33:07] │ 
[2023-11-12 01:33:07] │ Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/node_modules/string-width/index.js from /workspace/node_modules/cliui/build/index.cjs not supported.
[2023-11-12 01:33:07] │ Instead change the require of index.js in /workspace/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
[2023-11-12 01:33:07] │     at Object.<anonymous> (/workspace/node_modules/cliui/build/index.cjs:291:21)
[2023-11-12 01:33:07] │     at Object.<anonymous> (/workspace/node_modules/yargs/build/index.cjs:2861:12)
[2023-11-12 01:33:07] │     at Object.<anonymous> (/workspace/node_modules/yargs/index.cjs:5:30)
[2023-11-12 01:33:07] │     at Object.<anonymous> (/workspace/node_modules/copyfiles/copyfiles:4:12) {
[2023-11-12 01:33:07] │   code: 'ERR_REQUIRE_ESM'
[2023-11-12 01:33:07] │ }
[2023-11-12 01:33:07] │ error Command failed with exit code 1.
[2023-11-12 01:33:07] │ info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2023-11-12 01:33:07] │ error Command failed with exit code 1.
[2023-11-12 01:33:07] │ info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2023-11-12 01:33:07] │ building: exit status 1
[2023-11-12 01:33:07] │ ERROR: failed to build
```

Other dependencies appear to be having the same issue:
- https://github.com/isaacs/jackspeak/issues/5
- https://github.com/iarna/wide-align/issues/63

## Possible Solutions

1. Cloud deployments for the template were working previously, determine what dep was updated to cause this - revert it.

1. Our direct dependency is `resend`. See if updating that dependency fixes the reference

1. Add a `resolutions` to the package.json. Not the best solution.

### To Reproduce

- `npx create-payload-app -t blank`
- Deploy on cloud

### Payload Version

2.1.1

**Comment by denolfe** [comment]
Looks like this is a yarn v1 package alias resolution issue: https://github.com/yarnpkg/yarn/issues/4812

**Comment by denolfe** [comment]
Only workaround for yarn is to use this in the application's package.json:

```json
"resolutions": {
  "jackspeak": "2.1.1"
}
```

**Comment by denolfe** [comment]
Another avenue would be to update our templates to use yarn v2 and then specify as such in their `package.json`.

```json
  "engines": {
    "yarn": "1.x"
  }
  ```
  
  https://devcenter.heroku.com/articles/nodejs-support#specifying-a-yarn-version
