### ISSUE TITLE
Editing an image's size in dashboard gives an error

### ISSUE THREAD

**Issue by dylankuipers** [payloadcms/payload#4141]
### Link to reproduction

/

### Describe the Bug

When I edit an image it's size after uploading it I get an error saying "Something went wrong". Then in my logs it says this:

`<html>
<body>

[2023-11-14T14:37:46] | (payload): Error: ENOENT: no such file or directory, open '/workspace/payload/dist/images/triton-tx550.jpg'
-- | --
[2023-11-14T14:37:46] | at Object.openSync (node:fs:590:3)
[2023-11-14T14:37:46] | at Object.readFileSync (node:fs:458:35)
[2023-11-14T14:37:46] | at getFileByPath (/workspace/payload/node_modules/payload/dist/uploads/getFileByPath.js:21:34)
[2023-11-14T14:37:46] | at generateFileData (/workspace/payload/node_modules/payload/dist/uploads/generateFileData.js:46:59)
[2023-11-14T14:37:46] | at updateByID (/workspace/payload/node_modules/payload/dist/collections/operations/updateByID.js:103:106)
[2023-11-14T14:37:46] | at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-11-14T14:37:46] | at async updateByIDHandler (/workspace/payload/node_modules/payload/dist/collections/requestHandlers/updateByID.js:35:21)

</body>
</html>`

Sometimes I also get this error while editing the size before uploading/saving. Is this a known issue in Payload or just for me?

To edit the size I use the build in image editor in the dashboard and I use the overlay sliders on the image to make the view smaller.

### To Reproduce

Upload an image in payload dashboard and try to edit it's size after uploading the image. (Sometimes I also get an error while trying to edit it's size while I upload it)

### Payload Version

2.0.13

**Comment by JessChowdhury** [comment]
Hi @dylankuipers - we do have a known issue with upload editing when deployed to Cloud or using `plugin-cloud()`, you can track that [here](https://github.com/payloadcms/plugin-cloud-storage/issues/81).

Is this error happening locally or in production? We have released some upload related fixes recently, I would also test this on latest and see if the error persists.

**Comment by dylankuipers** [comment]
@JessChowdhury Hi, both in production and locally it gives the errors. And yes, I use payload-cloud, could that be related then?

**Comment by JessChowdhury** [comment]
@dylankuipers yes definitely - we have a fix in the works [here](https://github.com/payloadcms/payload/pull/4170), I'll shoot you a reply when we get it released.
