### ISSUE TITLE
GraphQLError: Names must only contain [_a-zA-Z0-9] when using non-latin names in select field

### ISSUE THREAD

**Issue by LoydAndrew** [payloadcms/payload#4172]
### Describe the Bug

I'm trying to use select field with a simple array of non-latin strings like ['текст1', 'текст 2']
The related config properties looks like this:
```javascript
    {
      name: 'someSelectField',
      hasMany: true,
      options: ['текст1', 'текст 2'],
      required: true,
      type: 'select',
    },

```
but in the end I'm having this error:
```javascript
unhandledRejection GraphQLError: Names must only contain [_a-zA-Z0-9] but "текст1" does not.
  at assertName (/home/node/app/node_modules/graphql/type/assertName.js:31:13)
 at assertEnumValueName (/home/node/app/node_modules/graphql/type/assertName.js:58:10)
 at /home/node/app/node_modules/graphql/type/definition.js:1223:49
  at Array.map (<anonymous>)
 at defineEnumValues (/home/node/app/node_modules/graphql/type/definition.js:1213:35)
at new GraphQLEnumType (/home/node/app/node_modules/graphql/type/definition.js:1080:20)
  at Object.type (/home/node/app/node_modules/payload/src/graphql/schema/withOperators.ts:198:11)
  at reduce (/home/node/app/node_modules/payload/src/graphql/schema/withOperators.ts:295:56)
 at Array.reduce (<anonymous>)
  at withOperators (/home/node/app/node_modules/payload/src/graphql/schema/withOperators.ts:292:28) {
 path: undefined,
  locations: undefined,
   extensions: [Object: null prototype] {}
```
My guess it's because payload produces an enum type like 
```javascript
enum Some_Select_Field_type {
  текст1
  текст2
}
```
But what I need is just some array of strings rather than enum so I can use non-latin array of strings in my database, like  Some_Select_Field_type: [String]. 
Is there a way to do that or maybe some workaround?

### To Reproduce

Create a basic collection with this field
```javascript
    {
      name: 'someSelectField',
      hasMany: true,
      options: ['текст1', 'текст 2'],
      required: true,
      type: 'select',
    },
```

### Payload Version

"payload": "^2.0.13",

**Comment by JarrodMFlesch** [comment]
You could do:

```ts
options: [
  {
    label: 'текст 1',
    value: 'tekct1',
  },
  {
    label: 'текст 2',
    value: 'tekct2',
  }
]
```

But as you noticed, the value will need to be able to be turned into an enum therefore characters will **need** to meet the criteria there. Could you store them like I did above?

I am going to close this for now as this is not something that we are going to change right now due to the benefits the enums provide in GraphQL.
