### ISSUE TITLE
Disabling drafts leads to API error

### ISSUE THREAD

**Issue by ciokan** [payloadcms/payload#4239]
### Describe the Bug

My admin panel for `pages` collection was showing only one page out of 12. The API however was returning all of them correctly. While searching for solutions I tried disabling the drafts on this collection to see if it brings any changes and the admin started showing all pages but now the API gives an error:

```[06:27:17] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'type')
    at sanitizeQueryValue (/cms/node_modules/@payloadcms/db-mongodb/src/queries/sanitizeQueryValue.ts:43:13)
    at buildSearchParam (/cms/node_modules/@payloadcms/db-mongodb/src/queries/buildSearchParams.ts:95:46)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseParams (/cms/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:60:35)
    at async buildAndOrConditions (/cms/node_modules/@payloadcms/db-mongodb/src/queries/buildAndOrConditions.ts:29:22)
    at async parseParams (/cms/node_modules/@payloadcms/db-mongodb/src/queries/parseParams.ts:43:33)
    at async Function.buildQuery (/cms/node_modules/@payloadcms/db-mongodb/src/queries/buildQuery.ts:43:22)
    at async Object.find (/cms/node_modules/@payloadcms/db-mongodb/src/find.ts:39:17)
    at async find (/cms/node_modules/payload/src/collections/operations/find.ts:144:16)
    at async findHandler (/cms/node_modules/payload/src/collections/requestHandlers/find.ts:30:20)```

### To Reproduce

I really don;t know what caused the admin to only show one page in the first place. This is my config:

```
import {webpackBundler} from '@payloadcms/bundler-webpack'; // bundler-import
import {payloadCloud} from '@payloadcms/plugin-cloud';
import {mongooseAdapter} from '@payloadcms/db-mongodb';
import nestedDocs from '@payloadcms/plugin-nested-docs';
import redirects from '@payloadcms/plugin-redirects';
import seo from '@payloadcms/plugin-seo';
import type {GenerateTitle} from '@payloadcms/plugin-seo/types';
import path from 'path';
import {buildConfig} from 'payload/config';
import {slateEditor} from "@payloadcms/richtext-slate";

import Categories from '@/collections/Categories';
import {Media} from '@/collections/Media';
import {Pages} from '@/collections/Pages';
import {Posts} from '@/collections/Posts';
import Faqs from '@/collections/Faqs';
import Testimonials from '@/collections/Testimonials';
import ContentBlocks from '@/collections/ContentBlocks';
import Features from '@/collections/Features';
import UseCases from '@/collections/UseCases';
import TextContent from '@/collections/TextContent';
import Cards from '@/collections/Cards';
import Tokens from "@/collections/Tokens";
import Users from '@/collections/Users';
import BeforeDashboard from './components/BeforeDashboard';
import {FooterGlobal} from './globals/Footer';
import {HeaderGlobal} from './globals/Header';

const generateTitle: GenerateTitle = () => {
	return 'Anonymous proxies';
};

const mockModulePath = path.resolve(__dirname, './emptyModuleMock.js');

export default buildConfig({
	editor     : slateEditor({}),
	admin      : {
		user      : Users.slug,
		components: {
			beforeDashboard: [BeforeDashboard],
		},
		webpack   : config => ({
			...config,
			resolve: {
				...config.resolve,
				alias: {
					...config.resolve?.alias,
					express: mockModulePath,
					'@'    : path.resolve(__dirname, './'),
				},
			},
		}),
		bundler   : webpackBundler(),
	},
	serverURL  : process.env.PAYLOAD_PUBLIC_SERVER_URL,
	collections: [
		Users,
		Categories,
		Pages,
		Posts,
		Media,
		Features,
		Faqs,
		Testimonials,
	],
	globals    : [
		HeaderGlobal,
		FooterGlobal,
	],
	rateLimit  : {
		max       : 10000, // limit each IP per windowMs
		trustProxy: true,
		window    : 2 * 60 * 1000, // 2 minutes
	},
	typescript : {
		outputFile: path.resolve(__dirname, 'payload-types.ts'),
	},
	graphQL    : {
		schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
	},
	cors       : [process.env.PAYLOAD_PUBLIC_SERVER_URL || ''].filter(Boolean),
	csrf       : [process.env.PAYLOAD_PUBLIC_SERVER_URL || ''].filter(Boolean),
	db         : mongooseAdapter({
		url: process.env.MONGODB_URI,
	}),
	plugins    : [
		nestedDocs({
			collections: ['pages', 'posts', 'categories'],
		}),
		redirects({
			collections: ['pages', 'posts'],
		}),
		seo({
			collections      : ['pages', 'posts'],
			generateTitle,
			uploadsCollection: 'media',
		}),
		payloadCloud(),
	],
});

```

### Payload Version

2.1.1

### Adapters and Plugins

_No response_

**Comment by DanRibbens** [comment]
When versions are enabled Paylod will store documents in a seperate _versions collection. The list view or any `find` with drafts operations, will use the versions collection instead of the actual collection.

When turning on/off versions you also need to create a migration or run a script to resave all documents.

The only reason I can think for why you stopped seeing all your `pages` in the admin UI would be a read access control. Have you changed `access.read` that would cause drafts to not be returned?

It would be helpful if you could share your pages collection config. The network requests that have different results could also help reveal the problem if you can share that as well.

Also, you cut off the error in what you pasted starting with: `at sanitizeQueryValue (/cms/node_modules/@payloadcms/db-mongodb/src/queries/sanitizeQueryValue.ts:43:13)` I can see the stack, but not what was thrown so that doesn't tell me much.

Thanks!

**Comment by ciokan** [comment]
Updated the initial message with the required info.

**Comment by jmikrut** [comment]
Hey @ciokan — did you recently upgrade to Payload 2.0?

When drafts are enabled, in order for pages to show up in the List view or be returned from the API with `?draft=true`, the newest drafts for each page need to have `latest: true` on them. 

This is written up in detail within the changelog here:
https://github.com/payloadcms/payload/releases/tag/v2.0.0

I'm pretty sure this is what you're seeing. There is a migration that you can run as part of our 2.0 migration guide that will solve this for you by going through and ensuring that each most recent draft of your Pages documents is marked as `latest: true`. But this is not an issue with Payload - rather, this is an issue with your data being inconsistent with what Payload expects. 

I will close this for now, but if it turns out that this is indeed related to a Payload bug, we will need a reproduction repo in order to diagnose further. 

We're happy to continue helping on this though!
