### ISSUE TITLE
Upgrading from 2.0.10 to >= 2.0.11 introduces a type error which appears to be related to the text field??

### ISSUE THREAD

**Issue by jakehopking** [payloadcms/payload#4252]
### Describe the Bug

All is working correctly in 2.0.10. All version above this (tried up to latest 2.2.1) maintain this introduced error.

I have no idea how to fix or why this has happened. My front-end is dead, and the collection queries within payload's admin are also screwed, suggesting this is deeper problem.

Here is the terminal error (see end of report for screenshot of network error from admin ui):

```shell
yarn run v1.22.19
$ cross-env NODE_ENV=development PAYLOAD_CONFIG_PATH=src/payload.config.ts ts-node src/dev.ts
[10:45:53] INFO (payload): Connected to MongoDB server successfully!
[10:45:53] INFO (payload): Starting Payload...
[10:45:53] INFO (payload): Payload Admin URL: http://10.0.1.236:3000/admin
Server listening on 3000...
 ○ compiling /[...slug] ...
webpack built 781d5c02f208788ab590 in 11736ms
WARNING in ./src/lib/payload.ts 226:16-28
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 257:16-28
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 288:16-28
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 308:16-34
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 365:24-40
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 410:35-51
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 700:24-36
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 733:24-36
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

webpack compiled with 8 warnings
 ✓ Compiled /[...slug] in 6.3s (1084 modules)
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/vendor-chunks/next.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/pages/_app.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/pages/[...slug].js as it exceeds the max of 500KB.
 X src/pages/_app.tsx (220:29) @ map
 X TypeError: Cannot read properties of undefined (reading 'map')
    at eval (webpack-internal:///./src/pages/_app.tsx:250:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async Function.MyApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:182:81)
    at async s (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:1:32573)
    at async We (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:1:55076)
    at async doRender (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2107:18)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2366:24)
    at async /Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/response-cache/index.ts:129:28 {
  page: '/_next/webpack-hmr'
}
  218 |         return {
  219 |           ...journal,
> 220 |           docs: journal.docs.map((doc: JournalType) => {
      |                             ^
  221 |             // Remove these, spread the ...rest back into the object.
  222 |             const { layout, ...rest } = doc || {};
  223 |             return {
[10:46:09] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'payload')
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:38:32)
    at Array.forEach (<anonymous>)
    at recurseRichText (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:36:26)
    at richTextRelationshipPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:136:3)
    at Object.afterReadPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/index.ts:37:43)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:157:42)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:45:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:43:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:418:21)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:45:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:43:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:280:21)
    at /Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:45:14
```

## Collections with errors (there are others, but these are indicative).

<img width="1749" alt="Screenshot 2023-11-23 at 10 36 51" src="https://github.com/payloadcms/payload/assets/3432643/d306b32c-18ba-4c2d-b813-90453df33ce7">
<img width="1764" alt="Screenshot 2023-11-23 at 10 37 05" src="https://github.com/payloadcms/payload/assets/3432643/314beede-ac3f-412c-ae27-f95a452b0084">

## Collection working correctly

<img width="1773" alt="Screenshot 2023-11-23 at 10 37 27" src="https://github.com/payloadcms/payload/assets/3432643/707f16ae-94fb-490b-9544-916cc08b61d4">

Please look into why this error has been introduced and not affecting others. Let me know what else I can supply to help you bugfix.

FYI @DanRibbens has access to this repo already (`dev` branch).

### To Reproduce

Install version `>=2.0.11` on my codebase.

### Payload Version

Working is 2.0.10. Breaking is >= 2.0.11

### Adapters and Plugins

db-mongodb, stripePlugin, webpackBundler, slateEditor

**Comment by MarkAtOmniux** [comment]
Hi @jakehopking are you using a standalone Payload project or a Payload-Nextjs project?

**Comment by MarkAtOmniux** [comment]
@AlessioGr this looks like it's using slate, not lexical

**Comment by jakehopking** [comment]
Yes - I'm using Slate (as mentioned in the Adapters and Plugins section).

I've searched through my collections, and nowhere do I specify an `upload` or `relationship` prop on a `type: 'richText'` object.

I've been using Payload for over a year now, and this is the first time I've had a breaking issues with with the textField. I feel this is a bug introduced on Payload's side. How can we progress here?

I have `upload` or `relationship` enabled within my `elements.ts`:

```ts
import { RichTextElement } from '@payloadcms/richtext-slate';
import video from './video';
import pullQuote from './pullQuote';

export const defaultElements: RichTextElement[] = [
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'blockquote',
  pullQuote,
  'ul',
  'ol',
  'indent',
  'link',
  'relationship',
  'upload',
  video,
];
```

I also have abstracted richtext into a function, so I can selectively enable the custom elements/leaves etc. 

Here's the code for that `richText.ts`:

```ts
import {
  RichTextElement,
  RichTextLeaf,
  slateEditor,
} from '@payloadcms/richtext-slate';
import { deepMerge } from '../../utilities/deepMerge';
import { defaultElements } from './elements';
import { defaultLeaves } from './leaves';
import { RichTextField } from 'payload/types';

type RichText = (
  overrides?: Partial<RichTextField>,
  additions?: {
    elements?: RichTextElement[];
    leaves?: RichTextLeaf[];
  },
) => RichTextField;

export const richText: RichText = (
  overrides,
  additions = {
    elements: [],
    leaves: [],
  },
) =>
  deepMerge<RichTextField, Partial<RichTextField>>(
    {
      name: 'richText',
      type: 'richText',
      required: true,
      editor: slateEditor({
        admin: {
          elements: [...defaultElements, ...(additions.elements || [])],
          leaves: [...defaultLeaves, ...(additions.leaves || [])],
        },
      }),
    },
    overrides,
  );
```

In some collections, I have disabled the relationship field (this was a workaround to an issue I had a while ago, and was suggested by @DanRibbens if I recall). Here's what I mean:


`Category.ts`

```ts
import { CollectionConfig } from 'payload/types';
import { slug } from '../fields';

export type CategoryType = {
  id?: string;
  title: string;
  slug: string;
};

const Category: CollectionConfig = {
  slug: 'categories',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'slug', 'id', 'createdAt', 'updatedAt'],
    enableRichTextRelationship: false,
    enableRichTextLink: false,
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'title',
      label: 'Title',
      type: 'text',
      required: true,
    },
    slug(),
  ],
};

export { Category };
```

Does any of this code that relates to richText raise any concerns with you??

Thanks

**Comment by MarkAtOmniux** [comment]
defaultElements contains relationship elements. I would start by removing all of those and then adding them back in one at a time to see which is causing the issue

**Comment by jakehopking** [comment]
I will try this.

The more important question is what has changed between these two versions that could have caused this?

**Comment by MarkAtOmniux** [comment]
Yes of course, but by making these changes and adding them back in one by one, you should be able to narrow down what element is causing the issue. From there, we can take a look at the files affected and then look at the history of changes 😊

**Comment by jakehopking** [comment]
Nope - disabling all of these elements, I get the exact same error.

Any other ideas?


## elements.ts

```ts
import { RichTextElement } from '@payloadcms/richtext-slate';
import largeBody from './largeBody';
import label from './label';
import video from './video';
import pullQuote from './pullQuote';

export const defaultElements: RichTextElement[] = [
  // 'h1',
  // 'h2',
  // 'h3',
  // 'h4',
  // 'h5',
  // 'h6',
  // 'blockquote',
  // pullQuote,
  // 'ul',
  // 'ol',
  // 'indent',
  // 'link',
  // 'relationship',
  // 'upload',
  // video,
];

```

## Error

```shell
[11:44:44] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'payload')
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:38:32)
    at Array.forEach (<anonymous>)
    at recurseRichText (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:36:26)
    at richTextRelationshipPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:136:3)
    at Object.afterReadPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/index.ts:37:43)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:157:42)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:45:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:43:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:418:21)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:45:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:43:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:280:21)
    at /Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:45:14
 ⨯ src/pages/_app.tsx (220:29) @ map
 ⨯ TypeError: Cannot read properties of undefined (reading 'map')
    at eval (webpack-internal:///./src/pages/_app.tsx:250:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async Function.MyApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:182:81)
    at async ea (webpack://next/./dist/esm/shared/lib/utils.js:73:19)
    at async e9 (webpack://next/./dist/esm/server/render.js:388:13)
    at async doRender (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2311:20)
    at async cacheEntry.responseCache.get.routeKind (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2593:24)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2450:24)
    at async DevServer.renderPageComponent (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2979:16)
    at async DevServer.renderToResponseImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:3039:24)
    at async DevServer.pipeImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:1563:21)
    at async DevServer.NextNodeServer.handleCatchallRenderRequest (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/next-server.ts:938:7)
    at async DevServer.handleRequestImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:1348:9) {
  page: '/_next/webpack-hmr'
}
  218 |         return {
  219 |           ...journal,
> 220 |           docs: journal.docs.map((doc: JournalType) => {
      |                             ^
  221 |             // Remove these, spread the ...rest back into the object.
  222 |             const { layout, ...rest } = doc || {};
  223 |             return {
 ○ Compiling /_error ...
^C

```

**Comment by jakehopking** [comment]
@jmikrut — James I'd love your thoughts here 🙏

**Comment by MarkAtOmniux** [comment]
Did you also check for duplicate payload installs in your node modules? That's been happening more frequently recently

**Comment by jmikrut** [comment]
Hey @jakehopking I'm gonna jump on this right away with the team. At first blush I can't see anything that would have changed here causing this, but @DanRibbens and I will work together to try and recreate the issue immediately.

**Comment by jakehopking** [comment]
> Did you also check for duplicate payload installs in your node modules? That's been happening more frequently recently

Checked, and no duplicates here.

**Comment by DanRibbens** [comment]
I pulled down `main` on your project, ran yarn, updated env vars, etc. and webpack built successfully when I ran in dev.

Working version: 
Installed `payload@2.3.0`
Node version `21.3.0`
yarn `1.22.21`

Then I went back to `2.0.11` and tried to run but I hit some config validation errors that prevented Payload from starting. Now I've run `2.2.2` and it is looking good `webpack compiled successfully`.

Moving on to building, I found some other type error on a hook which I fixed and opened a PR in your repo.

Then I got three webpack errors:

```
ERROR in ./node_modules/next/dist/compiled/gzip-size/index.js 248:24-37
Module not found: Error: Can't resolve 'fs' in 'C:\code\elkli-and-hart\node_modules\next\dist\compiled\gzip-size'

ERROR in ./node_modules/next/dist/compiled/gzip-size/index.js 252:24-41
Module not found: Error: Can't resolve 'stream' in 'C:\code\elkli-and-hart\node_modules\next\dist\compiled\gzip-size'

ERROR in ./node_modules/next/dist/compiled/gzip-size/index.js 256:24-39
Module not found: Error: Can't resolve 'zlib' in 'C:\code\elkli-and-hart\node_modules\next\dist\compiled\gzip-size'
```

This is unrelated to the issue of course, you will need to alias these of course.


Let me know how else I can help here. Are you still getting the errors after updating to latest?

**Comment by jakehopking** [comment]
Thanks for taking the time to look into this.

However I'm still completely stuck and confused how you managed to run my project, when I'm unable to 😞

@DanRibbens Did you run `yarn dev:basic` when you tried to run my project? 
This runs: `cross-env NODE_ENV=development PAYLOAD_CONFIG_PATH=src/payload.config.ts ts-node src/dev.ts`

I'm still in the exact same situation after updating to `2.3.0` with the same version of node you tried `21.3.0`.

Here's the console error after trying completely fresh install of everything in a fresh nvm environment.

```shell
❯ yarn dev:basic
yarn run v1.22.21
$ cross-env NODE_ENV=development PAYLOAD_CONFIG_PATH=src/payload.config.ts ts-node src/dev.ts
(node:24425) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[22:14:59] INFO (payload): Connected to MongoDB server successfully!
[22:14:59] INFO (payload): Starting Payload...
[22:14:59] INFO (payload): Payload Admin URL: http://10.0.1.236:3000/admin
Server listening on 3000...
webpack built 9c94e40fb139fa5bbe4f in 8779ms
WARNING in ./src/lib/payload.ts 226:16-28
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 257:16-28
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 288:16-28
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 308:16-34
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 365:24-40
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 410:35-51
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 700:24-36
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

WARNING in ./src/lib/payload.ts 733:24-36
export 'default' (imported as 'payload') was not found in 'payload' (possible exports: __esModule, webpackBundler)

webpack compiled with 8 warnings
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: No serializer registered for ConcatSource
<w> while serializing webpack/lib/util/registerExternalSerializer.webpack-sources/ConcatSource -> Array { 2 items } -> ConcatSource
 ○ Compiling / ...
 ✓ Compiled / in 3.9s (1088 modules)
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/vendor-chunks/next.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/pages/_app.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/pages/index.js as it exceeds the max of 500KB.
[22:15:27] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'payload')
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:38:32)
    at Array.forEach (<anonymous>)
    at recurseRichText (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:36:26)
    at richTextRelationshipPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:136:3)
    at Object.afterReadPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/index.ts:37:43)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:165:42)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:49:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:47:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:436:21)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:49:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:47:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:288:21)
    at /Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:49:14
 ⨯ src/pages/_app.tsx (220:29) @ map
 ⨯ TypeError: Cannot read properties of undefined (reading 'map')
    at eval (webpack-internal:///./src/pages/_app.tsx:250:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async Function.MyApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:182:81)
    at async ea (webpack://next/./dist/esm/shared/lib/utils.js:73:19)
    at async e9 (webpack://next/./dist/esm/server/render.js:388:13)
    at async doRender (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2311:20)
    at async cacheEntry.responseCache.get.routeKind (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2593:24)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2450:24)
    at async DevServer.renderPageComponent (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2979:16)
    at async DevServer.renderToResponseImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:3039:24)
    at async DevServer.pipeImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:1563:21)
    at async DevServer.NextNodeServer.handleCatchallRenderRequest (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/next-server.ts:938:7)
    at async DevServer.handleRequestImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:1348:9) {
  page: '/'
}
  218 |         return {
  219 |           ...journal,
> 220 |           docs: journal.docs.map((doc: JournalType) => {
      |                             ^
  221 |             // Remove these, spread the ...rest back into the object.
  222 |             const { layout, ...rest } = doc || {};
  223 |             return {
 ○ Compiling /_error ...
 ✓ Compiled /_error in 7.5s (1088 modules)
[BABEL] Note: The code generator has deoptimised the styling of /Users/jake/Development/personal/elkliandhart.com/.next/server/pages/_error.js as it exceeds the max of 500KB.
 ⨯ TypeError: Cannot read properties of undefined (reading 'map')
    at eval (webpack-internal:///./src/pages/_app.tsx:250:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async Function.MyApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:182:81)
    at async ea (webpack://next/./dist/esm/shared/lib/utils.js:73:19)
    at async e9 (webpack://next/./dist/esm/server/render.js:388:13)
    at async doRender (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2311:20)
    at async cacheEntry.responseCache.get.routeKind (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2593:24)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:2450:24)
    at async DevServer.renderErrorToResponseImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:3355:16)
    at async pipe.req.req (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:3198:26)
    at async DevServer.pipeImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:1563:21)
    at async DevServer.NextNodeServer.handleCatchallRenderRequest (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/next-server.ts:956:9)
    at async DevServer.handleRequestImpl (/Users/jake/Development/personal/elkliandhart.com/node_modules/next/src/server/base-server.ts:1348:9)
[22:15:35] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'payload')
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:38:32)
    at Array.forEach (<anonymous>)
    at recurseRichText (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:36:26)
    at richTextRelationshipPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/data/richTextRelationshipPromise.ts:136:3)
    at Object.afterReadPromise (/Users/jake/Development/personal/elkliandhart.com/node_modules/@payloadcms/richtext-slate/src/index.ts:37:43)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:165:42)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:49:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:47:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:436:21)
    at forEach (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:49:14)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:47:10)
    at promise (/Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/promise.ts:288:21)
    at /Users/jake/Development/personal/elkliandhart.com/node_modules/payload/src/fields/hooks/afterRead/traverseFields.ts:49:14

```

**Comment by jakehopking** [comment]
Not so fast Jake...

`yarn build` fails with this error:

```shell
❯ yarn build
yarn run v1.22.21
$ cross-env NODE_ENV=production yarn clear:build && yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next:custom
$ rm -rf .next && rm -rf build && rm -rf dist && yarn clear:cache:next
$ rm -rf .next
$ cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build
[23:29:05] INFO (payload): Starting Payload...
$ tsc --project tsconfig.server.json
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
/Users/jake/Development/personal/elkliandhart.com/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jake/Development/personal/elkliandhart.com/node_modules/string-width/index.js from /Users/jake/Development/personal/elkliandhart.com/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/jake/Development/personal/elkliandhart.com/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/jake/Development/personal/elkliandhart.com/node_modules/cliui/build/index.cjs:291:21) {
  code: 'ERR_REQUIRE_ESM'
}

```


Any ideas @DanRibbens ??

**Comment by DanRibbens** [comment]
I've not tried yarn 3, could be worth trying or npm or pnpm.

I did run `dev:basic`  and I only tried loading the admin UI as far as the register first user. I did see an error but I was only trying to make sure the webpack build was working and didn't go further.

I can check again tomorrow to see what the 500 error might be caused from.

**Comment by AlessioGr** [comment]
@jakehopking for PNPM, try adding a .npmrc file at the root of your project with the following contents:

`node-linker=hoisted`

That should fix the issue.

It's similar to setting `nodeLinker: node-modules` in yarn 4
