### ISSUE TITLE
richtext-lexical: HTMLConverter not working for fields nested in tabs

### ISSUE THREAD

**Issue by mrkrud** [payloadcms/payload#4260]
### Describe the Bug

Currently when a field is nested within a ```tabs``` field the HTML converter throws the following error:

```
[14:05:10] ERROR (payload): TypeError: Cannot destructure property 'path' of 'findFieldPathAndSiblingFields(...)' as it is null.
    at currentHook (C:\Users\mrkrud\Documents\sites\web\test-website\node_modules\@payloadcms\richtext-lexical\src\field\features\converters\html\field\index.ts:96:19)
    at C:\Users\mrkrud\Documents\sites\web\test-website\node_modules\payload\src\fields\hooks\afterRead\promise.ts:222:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at promise (C:\Users\mrkrud\Documents\sites\web\test-website\node_modules\payload\src\fields\hooks\afterRead\promise.ts:190:7)
    at async Promise.all (index 1)
    at afterRead (C:\Users\mrkrud\Documents\sites\web\test-website\node_modules\payload\src\fields\hooks\afterRead\index.ts:67:3)
```

Related issues: [#4023 ](https://github.com/payloadcms/payload/issues/4023), [#4034](https://github.com/payloadcms/payload/issues/4034)
Related fix: [#4103](https://github.com/payloadcms/payload/pull/4103)

On looking into this issue it appears that the ```tabs``` field nests its child fields under a ```tabs``` property instead of ```fields``` and this isn't currently being accounted for within the ```lexicalHTML()``` function.

### Possible solution

Within the ```lexicalHTML()``` afterRead hook, adding an additional check for 'tabs' into ```findFieldPathAndSiblingFields()``` :

``` ts
function findFieldPathAndSiblingFields(
  fields: Field[],
  path: string[],
): {
  path: string[]
  siblingFields: Field[]
} {
  for (const curField of fields) {
    if (curField === field) {
      return {
        path: [...path, curField.name],
        siblingFields: fields,
      }
    }

    if ('fields' in curField && 'name' in curField) {
      const result = findFieldPathAndSiblingFields(curField.fields, [
        ...path,
        curField.name,
      ])
      if (result) {
        return result
      }
    }
    // Additional check for a 'tabs' field
    if('tabs' in curField) {
      const tabFields = curField.tabs.flatMap( tab => tab.fields);
      const result = findFieldPathAndSiblingFields(tabFields, [
          ...path
      ]);
      if (result) {
          return result;
      }
    }
  }

  return null
}
```

### To Reproduce

Sample code needed to reproduce the error.

``` ts
import { CollectionConfig } from 'payload/types';

import { 
lexicalEditor, 
HTMLConverterFeature,
lexicalHTML
} from '@payloadcms/richtext-lexical';


const Tests:CollectionConfig = {
  slug: 'tests',

  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Content - Field',
          fields: [
            {
              name: 'testTabField',
              label: false,
              type: 'richText',
              editor: lexicalEditor({
                features: ({ defaultFeatures }) => [
                  ...defaultFeatures,
                  HTMLConverterFeature({}),
               ]
              })
            },
            lexicalHTML('testTabField', { name: 'testTabField_html' })
          ]
        },
        {
          label: 'Content - Field',
          fields: [
            {
              name: 'testTabSideField',
              label: false,
              type: 'richText',
              editor: lexicalEditor({
                features: ({ defaultFeatures }) => [
                 ...defaultFeatures,
                 HTMLConverterFeature({})
                ] 
              })
            },
            lexicalHTML('testTabSideField', { name: 'testTabSideField_html' })
          ]
        }
      ]
    }
  ]
}

export default Tests;
```

### Payload Version

2.2.1

### Adapters and Plugins

richtext-lexical v0.2.0

**Comment by silveltman** [comment]
I'm also still facing this issue
