### ISSUE TITLE
After fetch login. The requested resource was not found.

### ISSUE THREAD

**Issue by Kobreros** [payloadcms/payload#4267]
### Describe the Bug

After successfully logging in and obtaining a token using the fetch request `http://localhost:3000/api/profiles/login`, the server throws an error when I attempt to open the admin panel at `http://localhost:3000/admin`.
Unable to access the admin panel until the Profiles collection is removed from `payload.config.ts`

```
ERROR (payload): NotFound: The requested resource was not found.
    at findByID (D:\Study\svelte\test-auth\node_modules\payload\src\collections\operations\findByID.ts:114:15)  
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at me (D:\Study\svelte\test-auth\node_modules\payload\src\auth\operations\me.ts:32:19)
    at meHandler (D:\Study\svelte\test-auth\node_modules\payload\src\auth\requestHandlers\me.ts:13:22)
```

### To Reproduce

1. `npx create-payload-app@latest`
2. Create collection with auth or copy User collection and rename(filename, const, export)
3. Import collection to payload.config.ts
4. Create item in Profiles collection
5. Login using fetch
```js
const req = await fetch("http://localhost:3000/api/profiles/login", {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: 'EMAIL',
          password: 'PASSWORD'
        }),
      });

const data = await req.json();
```
6. Open `http://localhost:3000/admin`

### Payload Version

2.0.0 and 2.2.1

### Adapters and Plugins

mongooseAdapter, webpackBundler, slateEditor

**Comment by jmikrut** [comment]
Hey @Kobreros — this must be something to do with your implementation as we can't reproduce with what you've provided.

I suspect that this has something to do with your code, in hooks or similar. If you can create a reproduction, we can help spot your issue, but we try and reserve GitHub issues for bugs with Payload specifically and I do not think this is actionable on Payload's end. 

Happy to help in GitHub discussions and / or Discord though!
