### ISSUE TITLE
Global collection with field type ui crash

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#4459]
### Link to reproduction

-

### Describe the Bug

When I add a field type ui and I fetch using graphQL, the backend crash and report the following error:

```bash
Input Object type mutationOption_DeploymentsInput must define one or more fields.
    at assertValidSchema (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/graphql/type/validate.js:59:11)
    at validate (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/graphql/validation/validate.js:63:35)
    at handler (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/graphql-http/lib/handler.js:169:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestListener (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/graphql-http/lib/use/express.js:27:34)
```

### To Reproduce

1. Create a global collection
2. Add a field type UI
3. Fetch data using graphQL in the frontend (in my schema I don't require the field)
4. The backend show the error provided in the previous description

The collection is the following
```ts
const Options: GlobalConfig = {
    slug: "options",
    access: {
        read: () => true,
    },
    admin: {
        group: "Admin",
    },
    fields: [
        {
            type: "tabs",
            tabs: [
                {
                    name: "Deployments",
                    fields: [
                        {
                            name: 'redeploy',
                            label: 'Redeploy',
                            type: 'ui',
                            admin: {
                                components: {
                                    Field: DeploymentsField,
                                }
                            }
                        }
                    ]
                }
            ],
        },
    ],
};
```

The component is the folllwing

```ts
import { UIField } from "payload/types";
import React from 'react';
import "./index.scss";

export const DeploymentsField: React.FC<UIField> = () => {
    return <div>Hello world</div>
};

```

### Payload Version

"payload": "2.4.0",

### Adapters and Plugins

 		"@payloadcms/bundler-webpack": "1.0.5", 		"@payloadcms/db-mongodb": "1.1.0", 		"@payloadcms/plugin-cloud-storage": "1.1.1", 		"@payloadcms/plugin-form-builder": "1.0.15", 		"@payloadcms/plugin-nested-docs": "1.0.9", 		"@payloadcms/plugin-seo": "1.0.15", 		"@payloadcms/richtext-lexical": "0.4.0", 		"@payloadcms/richtext-slate": "1.3.0",

**Comment by JarrodMFlesch** [comment]
@matteo-naif what does your graphql query look like?

**Comment by matteo-naif** [comment]
Ok, I confirm that now works with this workaround

```ts
{
	name: "Deployments",
	fields: [
		{
			name: 'redeploy',
			label: 'Redeploy',
			type: 'ui',
			admin: {
				components: {
					Field: DeploymentsField,
				}
			}
		},
		/**
		 * Workaround to fix problem with UI field:
		 * add a hidden text field alongside the ui field
		 * 
		 * https://github.com/payloadcms/payload/issues/4459
		 */
		{
			name: 'redeploy',
			type: 'text',
			admin: {
				hidden: true
			}
		}
	]
}
```

**Comment by JarrodMFlesch** [comment]
@matteo-naif in the next release you wont need that field, fyi
