### ISSUE TITLE
Can we pass supressReservedKeysWarning to mongoose? 

### ISSUE THREAD

**Issue by kantorcodes** [payloadcms/payload#4533]
### Describe the Bug

Some collections have reserved words in them, and there is no option to supress the warning. When it happens, it appears to not allow certain schemas that do not adhere to Mongoose.  

tierbot-admin-portal-payload-1  | (node:112) [MONGOOSE] Warning: `collection` is a reserved schema pathname and may break some functionality. You are allowed to use it, but use at your own risk. To disable this warning pass `supressReservedKeysWarning` as a schema option.
tierbot-admin-portal-payload-1  | (Use `node --trace-warnings ...` to show where the warning was created)
tierbot-admin-portal-payload-1  | 
tierbot-admin-portal-payload-1  | /home/node/app/node_modules/mongoose/lib/helpers/document/compile.js:204
tierbot-admin-portal-payload-1  |         this.$set.call(this.$__[scopeSymbol] || this, path, v);
tierbot-admin-portal-payload-1  |                                ^
tierbot-admin-portal-payload-1  | TypeError: Cannot read properties of undefined (reading 'Symbol(mongoose#Document#scope)')
tierbot-admin-portal-payload-1  |     at Model.set [as collection] (/home/node/app/node_modules/mongoose/lib/helpers/document/compile.js:204:32)
tierbot-admin-portal-payload-1  |     at Function.compile (/home/node/app/node_modules/mongoose/lib/model.js:5237:30)
tierbot-admin-portal-payload-1  |     at Mongoose._model (/home/node/app/node_modules/mongoose/lib/index.js:644:27)
tierbot-admin-portal-payload-1  |     at Mongoose.model (/home/node/app/node_modules/mongoose/lib/index.js:603:27)
tierbot-admin-portal-payload-1  |     at forEach (/home/node/app/node_modules/@payloadcms/db-mongodb/src/init.ts:61:28)
tierbot-admin-portal-payload-1  |     at Array.forEach (<anonymous>)
tierbot-admin-portal-payload-1  |     at Object.init (/home/node/app/node_modules/@payloadcms/db-mongodb/src/init.ts:24:35)
tierbot-admin-portal-payload-1  |     at BasePayload.init (/home/node/app/node_modules/payload/src/payload.ts:356:21)
tierbot-admin-portal-payload-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
tierbot-admin-portal-payload-1  |     at getPayload (/home/node/app/node_modules/payload/src/payload.ts:431:22)

### To Reproduce

Create a collection with any reserved name in the slug and run the application. 

### Payload Version

2.4.0

### Adapters and Plugins

db-mongodb

**Comment by jmikrut** [comment]
Hey @kantorcodes — sure thing! Would you like to open a PR? I will mark this as a Feature Request discussion in the meantime.

I think that the property should be added to either the Mongoose adapter itself, or collection configs under the `custom` property - i.e.:

```js
const Pages: CollectionConfig = {
  slug: 'pages',
  custom: {
    supressReservedKeysWarning: true
  },
} 
```

What do you think?
