### ISSUE TITLE
plugin-seo: Auto-generate title not working

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#4542]
Getting React errors after selecting auto-generate for the title and the browser screen gets blank:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {condition, initialValue, passesCondition, valid, validate, value}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (main.js:184307:9)
    at reconcileChildFibers (main.js:185248:7)
    at reconcileChildren (main.js:188589:28)
    at updateHostComponent (main.js:189339:3)
    at beginWork (main.js:191033:14)
    at HTMLUnknownElement.callCallback (main.js:173584:14)
    at Object.invokeGuardedCallbackDev (main.js:173633:16)
    at invokeGuardedCallback (main.js:173697:31)
    at beginWork$1 (main.js:196866:7)
    at performUnitOfWork (main.js:195972:12)
```

```
The above error occurred in the <a> component:

    at a
    at h4
    at div
    at div
    at Preview (http://localhost:3000/admin/main.js:32826:50)
    at Field
    at UI (http://localhost:3000/admin/main.js:141934:20)
    at CheckForCondition (http://localhost:3000/admin/main.js:142710:24)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:135728:13)
    at div
    at GroupProvider (http://localhost:3000/admin/main.js:138406:26)
    at div
    at Group (http://localhost:3000/admin/main.js:138271:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:142710:24)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:146337:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:135728:13)
    at div
    at http://localhost:3000/admin/main.js:125514:13
    at div
    at div
    at DocumentFields (http://localhost:3000/admin/main.js:123033:13)
    at DefaultCollectionEdit (http://localhost:3000/admin/main.js:153437:58)
    at CustomCollectionComponent (http://localhost:3000/admin/main.js:153529:13)
    at Route (http://localhost:3000/admin/main.js:203591:29)
    at Switch (http://localhost:3000/admin/main.js:203793:29)
    at CollectionRoutes (http://localhost:3000/admin/main.js:153694:13)
    at E.t.Provider (http://localhost:3000/admin/main.js:236884:639)
    at form
    at Form (http://localhost:3000/admin/main.js:134676:93)
    at main
    at DefaultEditView (http://localhost:3000/admin/main.js:153291:55)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:146337:13)
    at EditView (http://localhost:3000/admin/main.js:154226:25)
    at DocumentInfoProvider (http://localhost:3000/admin/main.js:145208:37)
    at Route (http://localhost:3000/admin/main.js:203591:29)
    at Switch (http://localhost:3000/admin/main.js:203793:29)
    at div
    at div
    at Default (http://localhost:3000/admin/main.js:144456:20)
    at Route (http://localhost:3000/admin/main.js:203591:29)
    at Switch (http://localhost:3000/admin/main.js:203793:29)
    at Route (http://localhost:3000/admin/main.js:203591:29)
    at Suspense
    at Routes (http://localhost:3000/admin/main.js:150689:63)
    at CustomProvider (http://localhost:3000/admin/main.js:145030:27)
    at NavProvider (http://localhost:3000/admin/main.js:127045:24)
    at DocumentEventsProvider (http://localhost:3000/admin/main.js:145114:35)
    at LoadingOverlayProvider (http://localhost:3000/admin/main.js:145725:35)
    at StepNavProvider (http://localhost:3000/admin/main.js:130662:28)
    at LocaleProvider (http://localhost:3000/admin/main.js:145918:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:146422:33)
    at ThemeProvider (http://localhost:3000/admin/main.js:146524:26)
    at PreferencesProvider (http://localhost:3000/admin/main.js:146207:32)
    at AuthProvider (http://localhost:3000/admin/main.js:144619:25)
    at ModalProvider (http://localhost:3000/admin/main.js:7859:29)
    at Router (http://localhost:3000/admin/main.js:203210:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:202315:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:8555:26)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:8832:29)
    at ConfigProvider (http://localhost:3000/admin/main.js:144971:27)
    at Root (http://localhost:3000/admin/main.js:120467:25)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ main.js:188107
```

**Comment by cbratschi** [comment]
@jacobsfletch yes, still happens with the 2.x version from today.

**Comment by cbratschi** [comment]
Checked this again and in generateTitle we returned doc.title instead of doc.title.value. It works now fine.
