### ISSUE TITLE
`transactionOptions` not respected by `migrate`

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#4719]
### Describe the Bug

I think this will be a simple/quick fix, but looks lke the recent work on `transactionOptions` (https://github.com/payloadcms/payload/pull/4599) did not propagate to the migrations command
(https://github.com/payloadcms/payload/blob/main/packages/payload/src/database/migrations/migrate.ts#L32)

### To Reproduce

n/a

### Payload Version

2.6.0

### Adapters and Plugins

db-mongodb

**Comment by wiesson** [comment]
When do you expect to merge this PR? We are currently trying to migrate 4 pages to 2.0 and the mentioned error is preventing us from doing so! 🙏

**Comment by wiesson** [comment]
If anybody has the same issue; I have downgraded to the previous version and was able to run the migrations 👍

**Comment by javierlinked** [comment]
With payload 2.7.0 and db-mongodb 1.3.0 now error is: 

I had to fix repo to db-mongodb 1.1.1.

`[10:33:42] INFO (payload): Migrating: 20231218_123846_create_serviceuser
[10:33:42] ERROR (payload): Error running migration 20231218_123846_create_serviceuser
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'db')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'db')
              at initTransaction (/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/utilities/initTransaction.js:22:24)
              at Object.migrate (/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/database/migrations/migrate.js:38:56)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async migrate (/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/bin/migrate.js:64:13)
    }
/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/utilities/initTransaction.js:22
    if (typeof payload.db.beginTransaction === 'function') {
                       ^

TypeError: Cannot read properties of undefined (reading 'db')
    at initTransaction (/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/utilities/initTransaction.js:22:24)
    at Object.migrate (/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/database/migrations/migrate.js:38:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async migrate (/Users/jrojo/sources/Portal/Portal.Cms/node_modules/payload/dist/bin/migrate.js:64:13)`

**Comment by Kristijan007v** [comment]
Hi @javierlinked I am having the same issue, but your solution somehow did not helped me, I also tested on their e-commerce template with both latest and previous versions and I get the same issue as you. Do you know is this fix pushed to latest version? If you have any ideas what could help me I would really appreciate it, we are preparing for production release soon 😅

![image](https://github.com/payloadcms/payload/assets/84925309/1fdff948-8c2e-4ce2-b5d9-e50d7ec9d7e0)

I also created a Discord post inside Payload Community https://discord.com/channels/967097582721572934/1194788265757245520

**Comment by DanRibbens** [comment]
I have a PR to fix this. I made a silly error on the last release that has caused this. https://github.com/payloadcms/payload/pull/4777 should be merged and released tomorrow.

Thanks for reporting!
