### ISSUE TITLE
Invalid configuration when using Postgresql: The table products has multiple blocks with slug cta, but the schemas do not match. One block includes the field links_link.type, while the other block does not.

### ISSUE THREAD

**Issue by rmatovu987** [payloadcms/payload#4775]
### Describe the Bug

When I run `yarn dev` and I got the error below:
`
yarn run v1.22.19
$ cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts nodemon
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server.ts
[nodemon] watching extensions: js,ts
[nodemon] starting `ts-node --project tsconfig.server.json src/server.ts -- -I`
unhandledRejection InvalidConfiguration: The table products has multiple blocks with slug cta, but the schemas do not match. One block includes the field links_link.type, while the other block does not.
    at validateExistingBlockIsIdentical (/Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/validateExistingBlockIsIdentical.ts:71:13)
    at forEach (/Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/traverseFields.ts:449:45)
    at Array.forEach (<anonymous>)
    at forEach (/Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/traverseFields.ts:372:22)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/traverseFields.ts:100:10)
    at forEach (/Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/traverseFields.ts:473:15)
    at Array.forEach (<anonymous>)
    at traverseFields (/Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/traverseFields.ts:100:10)
    at /Users/rmatovu987/Documents/personal/projects/nextjs/sabr/sabr/node_modules/@payloadcms/db-postgres/src/schema/traverseFields.ts:558:13 {
  data: null,
  isOperational: true,
  isPublic: false,
  status: 500
}
[nodemon] app crashed - waiting for file changes before starting...
`

### To Reproduce

1. Create a new project using `npx create-payload-app@latest`
2. Select ecommerce as the template
3. Select postgres as the database
4. Run `yarn dev`

### Payload Version

2.0.0

**Comment by justinburrow** [comment]
Same happens here after npx create-payload-app@latest, using Website template with Postgres option.

- npm install
- npm run dev

[nodemon] starting `ts-node src/server.ts -- -I`
unhandledRejection InvalidConfiguration: The table posts has multiple blocks with slug cta, but the schemas do not match. One block includes the field links_link.type, while the other block does not.

**Comment by asianburrito** [comment]
also having this same issue, first time trying payload cms

**Comment by companyofwords** [comment]
Same issue. First time trying the payload CMS template (Website) - Is there a way to fix it ourselves please?

**Comment by modulareverything** [comment]
Also getting this on the 'website' template. First 10 minutes with Payload, so not sure if I'm doing something wrong but not really sure where to go with this one 🤔

**Comment by knynkwl** [comment]
I am getting this issue as well, just installed.

```
    "@payloadcms/bundler-webpack": "^1.0.0",
    "@payloadcms/db-postgres": "^0.x",
    "@payloadcms/plugin-cloud": "^3.0.0",
    "@payloadcms/plugin-nested-docs": "^1.0.8",
    "@payloadcms/plugin-redirects": "^1.0.0",
    "@payloadcms/plugin-seo": "^1.0.10",
    "@payloadcms/richtext-slate": "^1.0.0",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "escape-html": "^1.0.3",
    "express": "^4.17.1",
    "next": "13.5.2",
    "payload": "^2.0.0",
    "payload-admin-bar": "^1.0.6",
    "qs": "6.11.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "7.45.4",
    "react-router-dom": "5.3.4"

**Comment by denisorehovsky** [comment]
Still having this issue. Installed payload website a couple of hours ago

**Comment by justinburrow** [comment]
> Still having this issue. Installed payload website a couple of hours ago

Same here - it looks like the @payloadcms/db-postgres module had a bit of updated code merged in, but I don't believe a new npm package was built from it.  If you want to fix it in the meantime, you can manually copy the fix in the PR mentioned above and it'll work.
