### ISSUE TITLE
Crop Image When Updating an Upload Collection Item

### ISSUE THREAD

**Issue by glettl** [payloadcms/payload#4779]
### Describe the Bug

When trying to crop and save an existing image, there's an error on save.

```ERROR (payload): FileUploadError: There was a problem while uploading the file.
    at generateFileData (../node_modules/payload/src/uploads/generateFileData.ts:80:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByID (../node_modules/payload/src/collections/operations/updateByID.ts:142:57)
    at async updateByIDHandler (../node_modules/payload/src/collections/requestHandlers/updateByID.ts:36:17)``` 
    
It works with version 2.4.0. **Breaks in 2.5.0**    

More specific error in generateFileData.ts:

```
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at parseURL (../node_modules/node-fetch/lib/index.js:1164:12)
    at new Request (../node_modules/node-fetch/lib/index.js:1210:17)
    at ../node_modules/node-fetch/lib/index.js:1449:19
    at new Promise (<anonymous>)
    at fetch (../node_modules/node-fetch/lib/index.js:1447:9)
    at getExternalFile (../node_modules/payload/src/uploads/getExternalFile.ts:17:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateFileData (../node_modules/payload/src/uploads/generateFileData.ts:76:17)
    at async updateByID (../node_modules/payload/src/collections/operations/updateByID.ts:142:57) {
  code: 'ERR_INVALID_URL',
  input: 'http://localhost:3000http://localhost:3000/media/stream.webp'
}
```

The Url input seams broken.

### To Reproduce

Upload Image
Save
Edit the Image
Crop it
Save it

### Payload Version

2.7.0

### Adapters and Plugins

_No response_

**Comment by Leere77** [comment]
I've encountered the same issue after updating to 2.5.0 and higher

**Comment by denolfe** [comment]
It looks like this is some sort of caching issue possibly. I run through the steps in this video, and it does appear to crop the image. However, it does not appear cropped until a full refresh of the page is done.

Recreated with `pnpm dev uploads` in the monorepo on v2.11.2

@Leere77 or @glettl , are either of you able to see if this is page reload issue or if the image is in-fact not being cropped?

https://github.com/payloadcms/payload/assets/65888/c55e1aa2-d3d6-4c3a-b8fc-0f8c19abc7a2

**Comment by PatrikKozak** [comment]
Hey @glettl - we've recently been making some updates to `Uploads` - can you update your project to the latest version of Payload (`2.24.1`) and let me know if you are still experiencing the issues above?

**Comment by glettl** [comment]
Hey @PatrikKozak, we are currently running 2.23.1 behind a reverse proxy and we don't have any issues.
I can't update to 2.24.1 right now.
