### ISSUE TITLE
db-mongodb TypeErrors with `transactionOptions: false` v1.3.0+

### ISSUE THREAD

**Issue by xHomu** [payloadcms/payload#4802]
### Link to reproduction

https://github.com/manawiki/repay/tree/mongo-1.3-typeerror

### Describe the Bug

`transactionOptions: false` was introduced in  v1.2 to disable transactions altogether in the mongo plugin.  

In v1.3.0+, turning on that option breaks all read operations.

```console
Express server listening on http://localhost:3000
[21:40:55] INFO (payload): Connected to MongoDB server successfully!
[21:40:55] INFO (payload): Starting Payload...
[21:40:55] INFO (payload): Payload Admin URL: http://localhost:3000/admin
TypeError: Cannot read properties of null (reading 'then')
    at initTransaction (C:\Users\Fred\Documents\GitHub\repay\node_modules\payload\src\utilities\initTransaction.ts:20:59)
    at find (C:\Users\Fred\Documents\GitHub\repay\node_modules\payload\src\collections\operations\find.ts:75:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### To Reproduce

1. Copy .env.example to .env and fill the required environment variables.
2. yarn; yarn dev
3. https://localhost:3000 should work as expected
4. uncomment out `transactionOptions: false` in payload.config.ts
5. Restart terminal and `yarn; yarn dev` again.
6. `TypeError: Cannot read properties of null (reading 'then')`

* db-mongodb v1.2.0 & `transactionOptions: false` work correctly
* db-mongodb v1.3.0+ & `// transactionOptions: false` work correctly

Seems like v1.3 introduced some new transaction init that didn't properly checked transactionOptions?

### Payload Version

v2.8.1

### Adapters and Plugins

db-mongodb

**Comment by xHomu** [comment]
Seems related but unresolved by #4777

**Comment by xHomu** [comment]
Can confirm that #4804 seemed to have resolved this, thanks!
