### ISSUE TITLE
Cannot filter on arrays in GraphQL API

### ISSUE THREAD

**Issue by piraka9011** [payloadcms/payload#4819]
### Describe the Bug

I have a field in a collection defined as:

```ts
...
{
  type: 'select',
  name: 'platform',
  label: 'Platform',
  hasMany: true,
  options: [
    { label: 'Android', value: 'ANDROID' },
    { label: 'iOS', value: 'IOS' },
  ],
  defaultValue: ['ANDROID', 'IOS'],
  required: true,
},
...
```

I am trying to filter on the `platform` field using the following query:

```graphql
query getHomeScreenCards(
  $where: HomeScreenCard_where
  $fallbackLocale: FallbackLocaleInputType = en
  $locale: LocaleInputType
  $sort: String
) {
  HomeScreenCards(
    where: $where
    fallbackLocale: $fallbackLocale
    locale: $locale
    sort: $sort
  ) {
    docs {
      id
      platform
    }
    totalDocs
  }
}
```

and with the following query variables:

```json
{
  "locale": "ar",
  "where": {
    "platform": {
      "in": ["IOS"]
    }
  }
}
```

I get this error in the server logs

```
[20:51:09] ERROR (payload): error: syntax error at or near "in"
    at /home/node/app/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/node/app/node_modules/drizzle-orm/node-postgres/index.cjs:41:28
    at async find (/home/node/app/node_modules/@payloadcms/db-postgres/dist/find/findMany.js:154:29)
    at async find (/home/node/app/node_modules/payload/dist/collections/operations/find.js:103:22)
    at async resolver (/home/node/app/node_modules/payload/dist/collections/graphql/resolvers/find.js:37:25)
    at async Promise.all (index 0)
    at async handler (/home/node/app/node_modules/graphql-http/lib/handler.js:212:22)
    at async requestListener (/home/node/app/node_modules/graphql-http/lib/use/express.js:27:34)
```

### To Reproduce

Create a `select` collection using the `hasMany: true` and try filtering on one of the values using graphql as described above.

My dependencies

```json
"dependencies": {
  "@payloadcms/bundler-webpack": "^1.0.5",
  "@payloadcms/db-postgres": "^0.x",
  "@payloadcms/plugin-cloud": "^2.0.0",
  "@payloadcms/plugin-cloud-storage": "^1.1.1",
  "@payloadcms/richtext-lexical": "^0.5.1",
  "cross-env": "^7.0.3",
  "dotenv": "^8.2.0",
  "express": "^4.17.1",
  "payload": "^2.7.0"
},
"devDependencies": {
  "@types/express": "^4.17.9",
  "copyfiles": "^2.4.1",
  "lint-staged": "^15.2.0",
  "nodemon": "^2.0.6",
  "prettier": "^3.1.1",
  "ts-node": "^9.1.1",
  "typescript": "^4.8.4"
},
"resolutions": {
  "jackspeak": "2.1.1"
},
```

### Payload Version

2.7.0

### Adapters and Plugins

db-postgres, bundler-webpack, plugin-cloud-storage

**Comment by piraka9011** [comment]
I just tested this with the latest payload version and deps:

```json
"dependencies": {
  "@aws-sdk/client-s3": "^3.490.0",
  "@aws-sdk/lib-storage": "^3.490.0",
  "@payloadcms/bundler-webpack": "^1.0.6",
  "@payloadcms/db-postgres": "^0.3.1",
  "@payloadcms/plugin-cloud-storage": "^1.1.1",
  "@payloadcms/richtext-lexical": "^0.5.2",
  "aws-crt": "^1.20.1",
  "cross-env": "^7.0.3",
  "dotenv": "^8.6.0",
  "express": "^4.18.2",
  "payload": "^2.8.1"
},
"devDependencies": {
  "@types/express": "^4.17.17",
  "copyfiles": "^2.4.1",
  "lint-staged": "^15.2.0",
  "nodemon": "^3.0.1",
  "prettier": "^3.1.1",
  "ts-node": "^9.1.1",
  "typescript": "^4.8.4"
},
```

Running into the same exact problem

```
[14:06:09] ERROR (payload): error: syntax error at or near "in"
    at /Users/allabana/tarteel_ws/payload-cms/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/allabana/tarteel_ws/payload-cms/node_modules/src/node-postgres/session.ts:64:19
    at find (/Users/allabana/tarteel_ws/payload-cms/node_modules/@payloadcms/db-postgres/src/find/findMany.ts:156:25)
    at find (/Users/allabana/tarteel_ws/payload-cms/node_modules/payload/src/collections/operations/find.ts:144:16)
    at resolver (/Users/allabana/tarteel_ws/payload-cms/node_modules/payload/src/collections/graphql/resolvers/find.ts:50:21)
    at async Promise.all (index 0)
    at handler (/Users/allabana/tarteel_ws/payload-cms/node_modules/graphql-http/lib/handler.js:212:22)
    at requestListener (/Users/allabana/tarteel_ws/payload-cms/node_modules/graphql-http/lib/use/express.js:27:34)
```

**Comment by piraka9011** [comment]
I dug a bit deeper and found the following in the SQL logs

```
2024-01-15 21:36:06.143 UTC [142] ERROR:  syntax error at or near "in" at character 64
2024-01-15 21:36:06.143 UTC [142] STATEMENT:  select count
                     (*) from "home_screen_cards" where  in ($1)
```

Notice how there's an extra space between the `where` and the `in` that should have the column name (but doesn't).

**Comment by maximeMD** [comment]
Hey there, I'm having exactly the same issue.
I tried also with REST API and Local API, with logically the same error as a result.
Example for the Local API (adapted for @piraka9011  use case) 
```
{
      path: "/filter",
      method: "get",
      handler: async (req, res) => {
        const { topic, profiles } = req.query;
        const parsedTopic = z.string().optional().parse(topic);
        const parsedProfiles = z.array(z.string()).optional().parse(profiles);
        const events = await req.payload.find({
          collection: "xxxxxxxxx",
          where: {
            platform: {
              in: "IOS",
            },
          },
        });
        res.send(events);
      },
    },
```

I also tried many different operators, none of them works. 
Maybe we are just quering wrong ? If so please explain and I'll be happy to update the doc.

@piraka9011 did you find a workaround for this ? I'm quite stuck without this feature

**Comment by piraka9011** [comment]
@maximeMD Our workaround was to manually filter the returned objects in our app and not in the GraphQL query.

@PatrikKozak Would appreciate prioritizing since the fix seems to be relatively simple, but will be a high QoL improvement!
I'm just not familiar enough with the Payload/Drizzle internals to propose a fix, even though I've identified the issue.
