### ISSUE TITLE
plugin-cloud-storage: ERROR (405): UnknownError on S3 bucket

### ISSUE THREAD

**Issue by honooapp** [payloadcms/payload#4833]
I keep receiving the following error when I try to upload a file on an S3 bucket 
```
[21:13:52] ERROR (payload): There was an error while uploading files corresponding to the collection media with filename marker.png:
[21:13:52] ERROR (405): UnknownError
    405: UnknownError
        at throwDefaultError (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
        at de_PutObjectCommandError (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5701:12)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
[21:13:53] ERROR (payload): QueryError: The following paths cannot be queried: _status, _status
    at Function.buildQuery (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/payload/src/mongoose/buildQuery.ts:593:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at find (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/payload/src/collections/operations/find.ts:103:17)
    at findHandler (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/payload/src/collections/requestHandlers/find.ts:23:20)
[21:13:53] ERROR (NotFound): UnknownError
    NotFound: UnknownError
        at throwDefaultError (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
        at de_GetObjectCommandError (/Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4314:20)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
        at /Users/marcoautiero/OUTOFTHEBOX/opera_webapp/payloadcms/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

my payload.config.ts file content is the following
```
import { buildConfig } from 'payload/config';
import path from 'path';
// import Examples from './collections/Examples';
import Users from './collections/Users';
import Places from './collections/Places';
import Media from './collections/Media';
import { cloudStorage } from '@payloadcms/plugin-cloud-storage';
import { s3Adapter } from '@payloadcms/plugin-cloud-storage/s3';

const adapter = s3Adapter({
  config: {
    forcePathStyle: true,
    region: process.env.S3_REGION,
    endpoint: process.env.S3_ENDPOINT,
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    }
  },
  bucket: process.env.S3_BUCKET,
})

export default buildConfig({
  // serverURL: process.env.SERVER_URL,
  admin: {
    user: Users.slug,
  },
  collections: [
    Users,
    Places,
    Media
    // Add Collections here
    // Examples,
  ],
  localization: {
    locales: [
      'en',
      'it',
      'fr',
    ],
    defaultLocale: 'it',
    fallback: true,
  },
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
  cors: ["*", "http://localhost:3001", "http://nextjs"],
  csrf: [ // whitelist of domains to allow cookie auth from
    'http://localhost:3001', "http://nextjs"
  ],
  plugins: [
    cloudStorage({
      collections: {
        'media': {
          adapter, // see docs for the adapter you want to use
          // disablePayloadAccessControl: true,
          // generateFileURL: (args) => process.env.S3_ENDPOINT + "/" + args.filename
        },
      },
    }),
  ],
  upload: {
    limits: {
      fileSize: 5000000, // 5MB, written in bytes
    },
  }
});
```

and my Media.ts is the following 
```
import { CollectionConfig } from 'payload/types';

const Media: CollectionConfig = {
  slug: 'media',
  admin: {
    useAsTitle: 'filename',
  },
  access: {
    create: (): boolean => true, // Everyone can read Media
    read: (): boolean => true, // Everyone can read Media
    update: (): boolean => true, // Everyone can read Media
    delete: (): boolean => true, // Everyone can read Media
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
    },
  ],
  upload: {
    staticURL: '/media',
    staticDir: 'media',
    disableLocalStorage: true,
  }
}

export default Media
```

I have tested the Amazon user credentials through the CLI, and they're correct, I can also upload a file from the CLI.
My S3 bucket is configured to have public access through the following policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::staging-aretamap/*"
        }
    ]
}
```

I can't understand where is the issue

**Comment by denolfe** [comment]
Unable to recreate and missing reproduction.
