### ISSUE TITLE
plugin-cloud-storage: S3 storage adapter with local minio: Upload works, staticurl does not

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/payload#4834]
```
[12:46:14] ERROR (NoSuchKey): The specified key does not exist.
    NoSuchKey: The specified key does not exist.
        at de_NoSuchKeyRes (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6070:23)
        at de_GetObjectCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4315:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
        at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
        at async /app/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
        at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
        at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

```payload.config.ts.ts
const s3AdapterConfig: Args = {
  config: {
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_ACCESS_SECRET,
    },
    endpoint: process.env.S3_ENDPOINT,
    region: 'unknown',
    forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
  },
  bucket: process.env.S3_BUCKET,
};

    cloudStorage({
      collections: {
        downloads: {
          adapter: s3Adapter(s3AdapterConfig),
          prefix: `${process.env.S3_ROOT_PATH}/downloads`,
        },
        images: {
          adapter: s3Adapter(s3AdapterConfig),
          prefix: `${process.env.S3_ROOT_PATH}/images`,
        },
        videos: {
          adapter: s3Adapter(s3AdapterConfig),
          prefix: `${process.env.S3_ROOT_PATH}/videos`,
        },
      },
    }),
```

media.ts
```ts
import type { CollectionConfig } from 'payload/types';
import { createdBy } from '../../fields/created-by';
import { isAdminOrHasRole } from '../../access/is-admin-or-has-role';
import { updatedBy } from '../../fields/updated-by';

export const media: Pick<CollectionConfig, 'admin' | 'access' | 'fields'> = {
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'createdAt', 'createdBy'],
    group: 'Media',
  },
  access: {
    create: isAdminOrHasRole('media_create'),
    read: isAdminOrHasRole('media_read'),
    update: isAdminOrHasRole('media_update'),
    delete: isAdminOrHasRole('media_delete'),
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      localized: true,
    },
    createdBy(),
    updatedBy(),
  ],
};
```
image.ts
```ts
import type { CollectionConfig } from 'payload/types';
import { media } from './media';

export const image: CollectionConfig = {
  ...media,
  slug: 'images',
  upload: {
    staticURL: '/media/images',
    adminThumbnail: 'thumbnail',
    imageSizes: [
      {
        height: 1920,
        width: 1920,
        crop: 'center',
        name: 'xlarge',
      },
      {
        height: 1536,
        width: 1536,
        crop: 'center',
        name: 'large',
      },
      {
        height: 896,
        width: 896,
        crop: 'center',
        name: 'medium',
      },
      {
        height: 448,
        width: 448,
        crop: 'center',
        name: 'small',
      },
    ],
    mimeTypes: ['image/jpeg', 'image/jpg', 'image/png'],
  },
};

```

**Comment by denolfe** [comment]
> I managed to get it working by removing the `endpoint` property from the `s3Adapter` config object. If I add it back it immediately starts throwing the same error "NoSuchKey".
> 
> @denolfe Thank you for the quick reply. It motivated me to keep trying, and not give up.

Solved by above.
