### ISSUE TITLE
plugin-cloud-storage: Create new file (and upload) from URL.

### ISSUE THREAD

**Issue by revnelson** [payloadcms/payload#4838]
I can't seem to figure out how to create a new Images document with the file uploaded to my S3 bucket via a given URL and alt string (required in collection config). Uploading from admin UI is working, so not a config issue.

Here is the code I'm using (assumes url and alt given):

```typescript
let fimg = await fetch(url)
let data = Buffer.from(await fimg.arrayBuffer())

const file: File = {
  data,
  name: url.split("/").at(-1) ?? "",
  mimetype: getMimeTypeFromArrayBuffer(data) ?? "",
  size: data.byteLength,
}

console.log("File info", file.name, file.mimetype, file.size, alt)

const newImage = await payload.create({ collection: "images", data: { alt }, file })

console.log("New image", newImage)
```
The error I'm getting is:

```
[22:12:38] ERROR (payload): There was an error while uploading files corresponding to the collection images with filename immersion-heaters.jpg:
[22:12:38] ERROR (payload): getStorageClient(...).putObject is not a function
    TypeError: getStorageClient(...).putObject is not a function
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:154:48)
        at step (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:107:23)
        at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:48:20)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:26:71)
        at new Promise (<anonymous>)
        at __awaiter (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:8:12)
        at Object.eval [as handleUpload] (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:141:16)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:209:57)
        at step (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:107:23)
        at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:48:20)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:26:71)
        at new Promise (<anonymous>)
        at __awaiter (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:8:12)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:203:36)
        at Array.map (<anonymous>)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:202:42)
        at step (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:107:23)
        at Object.eval [as next] (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:48:20)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:26:71)
        at new Promise (<anonymous>)
        at __awaiter (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:8:12)
        at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/beforeChange.js:133:16)
        at /FULL_SYSTEM_PATH/node_modules/payload/dist/collections/operations/create.js:105:23
        at async create (/FULL_SYSTEM_PATH/node_modules/payload/dist/collections/operations/create.js:103:5)
        at async createImageFromUrl (webpack-internal:///(rsc)/./PROJECT_PATH/utils/createImageFromUrl.ts:17:22)
        at async formatCategory (webpack-internal:///(rsc)/./PROJECT_PATH/utils/formatCategory.ts:35:30)
        at async syncCategories (webpack-internal:///(rsc)/./PROJECT_PATH/categories/route.ts:59:50)
        at async GET (webpack-internal:///(rsc)/./PROJECT_PATH/categories/route.ts:92:13)
        at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37)
```

Oddly enough the payload document still gets created and the last console.log outputs:

```
New image {
  id: '64e9275658eacfe6f6f1b23c',
  alt: 'immersion-heaters',
  prefix: 'CONFIGURED_PREFIX',
  filename: 'immersion-heaters.jpg',
  mimeType: 'image/jpeg',
  filesize: 5252,
  width: 500,
  height: 500,
  createdAt: '2023-08-25T22:12:38.547Z',
  updatedAt: '2023-08-25T22:12:38.547Z',
  url: 'FULL_URL/immersion-heaters.jpg'
}
```

-----------

Perhaps I am doing something wrong in getting/creating/passing the Buffer that's created from the URL?

**Comment by denolfe** [comment]
The proper way to read data into buffer would be to use `fs.readFileSync` or similar.

We use a [getFileByPath helper](https://github.com/payloadcms/payload/blob/main/packages/payload/src/uploads/getFileByPath.ts#L13) in our test suites to do this with the following:

```ts
const getFileByPath = async (filePath: string): Promise<File> => {
  if (typeof filePath === 'string') {
    const data = fs.readFileSync(filePath)
    const mimetype = fromFile(filePath)
    const { size } = fs.statSync(filePath)

    const name = path.basename(filePath)
    const ext = path.extname(filePath).slice(1)

    const mime = (await mimetype)?.mime || mimeTypeEstimate[ext]

    return {
      name,
      data,
      mimetype: mime,
      size,
    }
  }

  return undefined
}
```

I hope this provides you with some direction.

**Comment by revnelson** [comment]
Thank you for your response, but I was trying to create an image from a remote url without using the filesystem. Apparently I was missing the `new Uint8Array` conversion before passing it to `Buffer.from`. The code below has been working for me:


```
const imageResponse = await fetch(encodeURI(imageURL), {
  referrerPolicy: "origin"
})
const responseArray = await imageResponse.arrayBuffer()
const imageBufferArray = new Uint8Array(responseArray)
const imageBuffer = Buffer.from(imageBufferArray)

const mimetype = imageResponse.headers.get("content-type") || "image/jpeg"
const newImageFile: File = {
  data: imageBuffer,
  name: filename,
  size: imageBuffer.length,
  mimetype
}

const newImage = payload.create({
  collection,
  data: { alt: alt ?? filename, title: filename },
  file: newImageFile
})
```
