### ISSUE TITLE
`pnpm dev:generate-types` generates different types from upstream + crashes

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#4869]
### Describe the Bug

When I run `pnpm dev:generate-types`, it generates a `payload-types.ts` different from upstream, and crashes.

```
❯ pnpm dev:generate-types

> payload-monorepo@0.0.1 dev:generate-types /Users/tyteen4a03/Documents/CodeProjects/test/payload
> ts-node -T ./test/generateTypes.ts

(node:32811) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Compiling TS types for Collections and Globals...
[16:48:21] INFO (payload): Types written to /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/versions/payload-types.ts
[16:48:21] INFO (payload): Starting Payload...
Error: Cannot find module '../../../packages/payload/errors'
Require stack:
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/config.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/config/load.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/bin/generateTypes.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/generateTypes.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/tyteen4a03/Documents/CodeProjects/test/payload/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts:11:17)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module.m._compile (/Users/tyteen4a03/Documents/CodeProjects/test/payload/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.76_@types+node@20.5.7_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/tyteen4a03/Documents/CodeProjects/test/payload/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.76_@types+node@20.5.7_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/config.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/config/load.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/bin/generateTypes.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/generateTypes.ts'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

### To Reproduce

1. Clone the `payload` repo.
2. Run `pnpm install`, then `pnpm dev::generate-types`

### Payload Version

2.8.2

**Comment by tyteen4a03** [comment]
It does:

```
❯ pnpm dev:generate-types plugin-stripe

> payload-monorepo@0.0.1 dev:generate-types /Users/tyteen4a03/Documents/CodeProjects/test/payload
> ts-node -T ./test/generateTypes.ts "plugin-stripe"

Error: Cannot find module '../../../packages/payload/errors'
Require stack:
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/config.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/config/load.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/bin/generateTypes.ts
- /Users/tyteen4a03/Documents/CodeProjects/test/payload/test/generateTypes.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/tyteen4a03/Documents/CodeProjects/test/payload/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts:11:17)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module.m._compile (/Users/tyteen4a03/Documents/CodeProjects/test/payload/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.76_@types+node@20.5.7_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/tyteen4a03/Documents/CodeProjects/test/payload/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.3.76_@types+node@20.5.7_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/plugin-stripe/config.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/config/load.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/packages/payload/src/bin/generateTypes.ts',
    '/Users/tyteen4a03/Documents/CodeProjects/test/payload/test/generateTypes.ts'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by tyteen4a03** [comment]
Also to note that it also generated a different upstream payload-types files (sorry I forgot to add it to the initial issue):

```
diff --git a/test/versions/payload-types.ts b/test/versions/payload-types.ts
index 2a7c29f38..09ab2e331 100644
--- a/test/versions/payload-types.ts
+++ b/test/versions/payload-types.ts
@@ -1,4 +1,5 @@
 /* tslint:disable */
+/* eslint-disable */
 /**
  * This file was automatically generated by Payload.
  * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
@@ -7,59 +8,139 @@

 export interface Config {
   collections: {
-    'autosave-posts': AutosavePost
-    'draft-posts': DraftPost
-    'version-posts': VersionPost
-    users: User
-  }
+    'disable-publish': DisablePublish;
+    posts: Post;
+    'autosave-posts': AutosavePost;
+    'draft-posts': DraftPost;
+    'version-posts': VersionPost;
+    'custom-ids': CustomId;
+    users: User;
+    'payload-preferences': PayloadPreference;
+    'payload-migrations': PayloadMigration;
+  };
   globals: {
-    'autosave-global': AutosaveGlobal
-    'draft-global': DraftGlobal
-  }
+    'autosave-global': AutosaveGlobal;
+    'draft-global': DraftGlobal;
+    'disable-publish-global': DisablePublishGlobal;
+  };
+}
+export interface DisablePublish {
+  id: string;
```

**Comment by denolfe** [comment]
Sorry, I'm still not able to recreate this. Closing for now.
