### ISSUE TITLE
error after using npx create-payload-app: sharp@0.32.6 couldn't be built successfully

### ISSUE THREAD

**Issue by aadilayub** [payloadcms/payload#4877]
### Describe the Bug

When I run `yarn` after creating a project using `create-payload-app`, I get a build error:

```
~/sample-payload is 📦 v1.0.0 via  v18.17.1 took 3s 
❯ ~/sample-payload is 📦 v1.0.0 via  v18.17.1 took 6m4s 
❯ yarn
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 383ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 881ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ sharp@npm:0.32.6 must be built because it never has been before or the last one failed
➤ YN0009: │ sharp@npm:0.32.6 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-e8095929/build.log)
➤ YN0000: └ Completed in 0s 510ms
➤ YN0000: · Failed with errors in 1s 864ms
```

### To Reproduce

1. Run `npx create-payload-app` and follow the instructions
2. Run `yarn` to install dependencies

### Payload Version

2.0.0

### Adapters and Plugins

db-mongodb, bundler-webpack, plugin-cloud, richtext-slate

**Comment by aadilayub** [comment]
This step also fails when I try to run the same in an alpine docker container.

Here's the build log:

```
# This file contains the result of Yarn building a package (sharp@npm:0.32.6)
# Script name: install

node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module './process'
Require stack:
- /var/home/aadil/.yarn/berry/cache/detect-libc-npm-2.0.2-03afa59137-10c0.zip/node_modules/detect-libc/lib/detect-libc.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/install/libvips.js
Require stack:
- /var/home/aadil/.yarn/berry/cache/detect-libc-npm-2.0.2-03afa59137-10c0.zip/node_modules/detect-libc/lib/detect-libc.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/install/libvips.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at require$$0.Module._resolveFilename (/var/home/aadil/sample-payload/.pnp.cjs:20043:54)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at require$$0.Module._load (/var/home/aadil/sample-payload/.pnp.cjs:19957:31)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/var/home/aadil/.yarn/berry/cache/detect-libc-npm-2.0.2-03afa59137-10c0.zip/node_modules/detect-libc/lib/detect-libc.js:7:32)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at require$$0.Module._extensions..js (/var/home/aadil/sample-payload/.pnp.cjs:20109:33) {
  code: 'MODULE_NOT_FOUND'
}

Node.js v20.11.0
node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module './process'
Require stack:
- /var/home/aadil/.yarn/berry/cache/detect-libc-npm-2.0.2-03afa59137-10c0.zip/node_modules/detect-libc/lib/detect-libc.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/lib/platform.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/lib/libvips.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/install/can-compile.js
Require stack:
- /var/home/aadil/.yarn/berry/cache/detect-libc-npm-2.0.2-03afa59137-10c0.zip/node_modules/detect-libc/lib/detect-libc.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/lib/platform.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/lib/libvips.js
- /var/home/aadil/sample-payload/.yarn/unplugged/sharp-npm-0.32.6-6b3822c437/node_modules/sharp/install/can-compile.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at require$$0.Module._resolveFilename (/var/home/aadil/sample-payload/.pnp.cjs:20043:54)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at require$$0.Module._load (/var/home/aadil/sample-payload/.pnp.cjs:19957:31)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/var/home/aadil/.yarn/berry/cache/detect-libc-npm-2.0.2-03afa59137-10c0.zip/node_modules/detect-libc/lib/detect-libc.js:7:32)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at require$$0.Module._extensions..js (/var/home/aadil/sample-payload/.pnp.cjs:20109:33) {
  code: 'MODULE_NOT_FOUND'
}

Node.js v20.11.0
```

**Comment by aadilayub** [comment]
This may be related : https://github.com/lovell/sharp/issues/3833

**Comment by aadilayub** [comment]
This error also occurs when running `npx create-payload-app@latest` instead of `npx-create-payload`:
---
Log:

```
❯ npx create-payload-app@latest
Need to install the following packages:
create-payload-app@1.0.0
Ok to proceed? (y) y

  Welcome to Payload. Let's create a project! 

✔ Project name? … sample-payload
✔ Choose project template › blank
✔ Select a database › MongoDB
✔ Enter MongoDB connection string … mongodb://127.0.0.1/sample-payload

  Creating project in /var/home/aadil/sample-payload

⠧ Installing dependencies...{
  err: Error: Command failed with exit code 1: yarn
  ➤ YN0000: · Yarn 4.0.2
  ➤ YN0000: ┌ Resolution step
  ➤ YN0085: │ + @payloadcms/bundler-webpack@npm:1.0.6, @payloadcms/db-mongodb@npm:1.3.2, @payloadcms/plugin-cloud@npm:3.0.0, @payloadcms/richtext-slate@npm:1.3.1, and 1089 more.
  ➤ YN0000: └ Completed in 2s 412ms
  ➤ YN0000: ┌ Fetch step
  ➤ YN0000: └ Completed in 0s 738ms
  ➤ YN0000: ┌ Link step
  ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
  ➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
  ➤ YN0007: │ sharp@npm:0.32.6 must be built because it never has been before or the last one failed
  ➤ YN0007: │ @swc/core@npm:1.3.76 [ed3e5] must be built because it never has been before or the last one failed
  ➤ YN0009: │ sharp@npm:0.32.6 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-192d0d46/build.log)
  ➤ YN0000: └ Completed in 1s 781ms
  ➤ YN0000: · Failed with errors in 5s 100ms
      at makeError (/var/home/aadil/.npm/_npx/a78262c2ecc815d9/node_modules/execa/lib/error.js:60:11)
      at handlePromise (/var/home/aadil/.npm/_npx/a78262c2ecc815d9/node_modules/execa/index.js:118:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async installDeps (/var/home/aadil/.npm/_npx/a78262c2ecc815d9/node_modules/create-payload-app/dist/lib/create-project.js:50:9)
      at async createProject (/var/home/aadil/.npm/_npx/a78262c2ecc815d9/node_modules/create-payload-app/dist/lib/create-project.js:84:20)
      at async Main.init (/var/home/aadil/.npm/_npx/a78262c2ecc815d9/node_modules/create-payload-app/dist/main.js:79:21)
      at async main (/var/home/aadil/.npm/_npx/a78262c2ecc815d9/node_modules/create-payload-app/dist/index.js:8:5) {
    shortMessage: 'Command failed with exit code 1: yarn',
    command: 'yarn',
    escapedCommand: 'yarn',
    exitCode: 1,
    signal: undefined,
    signalDescription: undefined,
    stdout: '➤ YN0000: · Yarn 4.0.2\n' +
      '➤ YN0000: ┌ Resolution step\n' +
      '➤ YN0085: │ + @payloadcms/bundler-webpack@npm:1.0.6, @payloadcms/db-mongodb@npm:1.3.2, @payloadcms/plugin-cloud@npm:3.0.0, @payloadcms/richtext-slate@npm:1.3.1, and 1089 more.\n' +
      '➤ YN0000: └ Completed in 2s 412ms\n' +
      '➤ YN0000: ┌ Fetch step\n' +
      '➤ YN0000: └ Completed in 0s 738ms\n' +
      '➤ YN0000: ┌ Link step\n' +
      '➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental\n' +
      '➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed\n' +
      '➤ YN0007: │ sharp@npm:0.32.6 must be built because it never has been before or the last one failed\n' +
      '➤ YN0007: │ @swc/core@npm:1.3.76 [ed3e5] must be built because it never has been before or the last one failed\n' +
      "➤ YN0009: │ sharp@npm:0.32.6 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-192d0d46/build.log)\n" +
      '➤ YN0000: └ Completed in 1s 781ms\n' +
      '➤ YN0000: · Failed with errors in 5s 100ms',
    stderr: '',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
}
✖ Error installing dependencies
✔ .env file created
✔ Payload project successfully created

  ★ Launch Application:

    - cd ./sample-payload
    - yarn dev or follow directions in README.md

  ★ Documentation:

    - Getting Started
    - Configuration

**Comment by devhik0** [comment]
I have checked it as you said but didnt get any error or issue on mine. I am on windows and using yarn 1.8, maybe its related with your yarn version.

```
>npx create-payload-app@latest
Need to install the following packages:
create-payload-app@1.0.0
Ok to proceed? (y) y

  Welcome to Payload. Let's create a project!

√ Project name? ... test
√ Choose project template » blank
√ Select a database » MongoDB
√ Enter MongoDB connection string ... mongodb://127.0.0.1/test

  Creating project in .\test

√ Dependencies installed
√ .env file created
√ Payload project successfully created

  * Launch Application:

    - cd ./test
    - yarn dev
```

**Comment by craigrdaniels** [comment]
I had the same error when trying to build my payload app with pnpm on Ubuntu.

As per @aadilayub post, adding the following to package.json fixed the bug for me.

```
  "overrides": {
    "payload@latest": {
      "sharp": "^0.33.2"
    }
  },
```

**Comment by aadilayub** [comment]
@craigrdaniels this worked, thank you!

Also for the Docker error, shifting to `node:21-bookworm` instead of `node:18-alpine` as the base image got rid of the error

**Comment by aadilayub** [comment]
Ran into this error again today while creating a new payload app (both using `create-payload-app` and `create-payload-app@latest`). Unfortunately, @craigrdaniels' suggestion did not work this time.

I could try with pnpm, but I think it should work with yarn by default, since that's the package manager suggested in the README.

**Comment by craigrdaniels** [comment]
> Ran into this error again today while creating a new payload app (both using `create-payload-app` and `create-payload-app@latest`). Unfortunately, @craigrdaniels' suggestion did not work this time.
> 
> I could try with pnpm, but I think it should work with yarn by default, since that's the package manager suggested in the README.

Try this instead, I used an incorrect syntax before which I'm now not sure how it worked in my other project.

This got rid of the sharp errors for me. I tested this on a brand new create-payload-app demo page. And this build fine on docker node:20-alpine using pnpm.

Looks like the syntax is the same for yarn.


```
  "resolutions": {
    "sharp": "^0.33.2"
  },
```
