### ISSUE TITLE
Create new doc from relationship field throws error

### ISSUE THREAD

**Issue by dkirchhof** [payloadcms/payload#4900]
### Describe the Bug

I have a collection with articles. Somewhere else a block with a relationship field. This field relates to the articles collection. When I click on the plus button to create a new article instead of linking an existing one, I get a lot of errors and a white screen.

I tried to debug the error and found some behavior I don't understand.
For example in the DrawerContent.js the docPermissions are always null (I think this will cause one of the errors). While using another collection in the relationship field, the docPermissions aren't null anymore.

I also tried to reproduce it wich a minimal config, but I can't. The errors are gone.
Well, I copied the whole articles collection config, changed the slug and used this new one. No errors. So I have no idea if its something with the config or something else.

So sorry for this vague bug report.

```
index.js:78 Uncaught TypeError: Cannot use 'in' operator to search for 'create' in null
    at DocumentControls (index.js:78:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
DocumentControls @ index.js:78
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less

index.js:29 Uncaught TypeError: Cannot read properties of null (reading 'fields')
    at DocumentFields (index.js:29:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
DocumentFields @ index.js:29
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less

index.js:78 Uncaught TypeError: Cannot use 'in' operator to search for 'create' in null
    at DocumentControls (index.js:78:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
DocumentControls @ index.js:78
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 16 more frames
Show less

index.js:29 Uncaught TypeError: Cannot read properties of null (reading 'fields')
    at DocumentFields (index.js:29:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
DocumentFields @ index.js:29
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 16 more frames
Show less

react-dom.development.js:18687 The above error occurred in the <DocumentControls> component:

    at DocumentControls (http://localhost:4000/admin/main.js:169179:13)
    at http://localhost:4000/admin/main.js:165996:19
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at Content (http://localhost:4000/admin/main.js:169356:20)
    at DocumentInfoProvider (http://localhost:4000/admin/main.js:192174:37)
    at DocumentDrawerContent (http://localhost:4000/admin/main.js:169494:17)
    at div
    at http://localhost:4000/admin/main.js:172228:13
    at div
    at Modal (http://localhost:4000/admin/main.js:33165:26)
    at dialog
    at Transition (http://localhost:4000/admin/main.js:264550:30)
    at CSSTransition (http://localhost:4000/admin/main.js:263662:35)
    at ModalWrap (http://localhost:4000/admin/main.js:33745:44)
    at Drawer (http://localhost:4000/admin/main.js:170600:19)
    at DocumentDrawer (http://localhost:4000/admin/main.js:169623:13)
    at div
    at AddNewRelation (http://localhost:4000/admin/main.js:186317:27)
    at div
    at div
    at Relationship (http://localhost:4000/admin/main.js:186715:13)
    at CheckForCondition (http://localhost:4000/admin/main.js:189522:24)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at div
    at RenderFields (http://localhost:4000/admin/main.js:182520:13)
    at div
    at div
    at div
    at AnimateHeight (http://localhost:4000/admin/main.js:218212:5)
    at CollapsibleProvider (http://localhost:4000/admin/main.js:168278:32)
    at div
    at Collapsible (http://localhost:4000/admin/main.js:168150:24)
    at div
    at BlockRow (http://localhost:4000/admin/main.js:183332:21)
    at DraggableSortableItem (http://localhost:4000/admin/main.js:170332:13)
    at div
    at SortableContext (http://localhost:4000/admin/main.js:29855:5)
    at DndContext (http://localhost:4000/admin/main.js:28467:5)
    at DraggableSortable (http://localhost:4000/admin/main.js:170415:13)
    at div
    at BlocksField (http://localhost:4000/admin/main.js:183809:58)
    at CheckForCondition (http://localhost:4000/admin/main.js:189522:24)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at div
    at RenderFields (http://localhost:4000/admin/main.js:182520:13)
    at div
    at div
    at TabsProvider (http://localhost:4000/admin/main.js:188264:25)
    at div
    at TabsField (http://localhost:4000/admin/main.js:188087:20)
    at CheckForCondition (http://localhost:4000/admin/main.js:189522:24)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at div
    at RenderFields (http://localhost:4000/admin/main.js:182520:13)
    at div
    at http://localhost:4000/admin/main.js:172228:13
    at div
    at div
    at DocumentFields (http://localhost:4000/admin/main.js:169747:13)
    at div
    at http://localhost:4000/admin/main.js:165996:19
    at CustomCollectionComponent (http://localhost:4000/admin/main.js:200668:13)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Switch (http://localhost:4000/admin/main.js:256938:29)
    at CollectionRoutes (http://localhost:4000/admin/main.js:200833:13)
    at E.t.Provider (http://localhost:4000/admin/main.js:306768:639)
    at form
    at Form (http://localhost:4000/admin/main.js:181468:93)
    at main
    at DefaultEditView (http://localhost:4000/admin/main.js:200411:55)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at EditView (http://localhost:4000/admin/main.js:201365:25)
    at DocumentInfoProvider (http://localhost:4000/admin/main.js:192174:37)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Switch (http://localhost:4000/admin/main.js:256938:29)
    at div
    at div
    at Default (http://localhost:4000/admin/main.js:191326:20)
    at ActionsProvider (http://localhost:4000/admin/main.js:191479:28)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Switch (http://localhost:4000/admin/main.js:256938:29)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Suspense
    at Routes (http://localhost:4000/admin/main.js:197751:63)
    at CustomProvider (http://localhost:4000/admin/main.js:191996:27)
    at NavProvider (http://localhost:4000/admin/main.js:173834:24)
    at DocumentEventsProvider (http://localhost:4000/admin/main.js:192080:35)
    at LoadingOverlayProvider (http://localhost:4000/admin/main.js:192691:35)
    at StepNavProvider (http://localhost:4000/admin/main.js:177451:28)
    at LocaleProvider (http://localhost:4000/admin/main.js:192884:27)
    at SearchParamsProvider (http://localhost:4000/admin/main.js:193388:33)
    at ThemeProvider (http://localhost:4000/admin/main.js:193490:26)
    at PreferencesProvider (http://localhost:4000/admin/main.js:193173:32)
    at AuthProvider (http://localhost:4000/admin/main.js:191585:25)
    at ModalProvider (http://localhost:4000/admin/main.js:33380:29)
    at Router (http://localhost:4000/admin/main.js:256355:30)
    at BrowserRouter (http://localhost:4000/admin/main.js:255460:35)
    at ScrollInfoProvider (http://localhost:4000/admin/main.js:35230:26)
    at WindowInfoProvider (http://localhost:4000/admin/main.js:35507:29)
    at ConfigProvider (http://localhost:4000/admin/main.js:191937:27)
    at Root (http://localhost:4000/admin/main.js:167181:25)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less

react-dom.development.js:18687 The above error occurred in the <DocumentFields> component:

    at DocumentFields (http://localhost:4000/admin/main.js:169747:13)
    at div
    at http://localhost:4000/admin/main.js:165996:19
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at Content (http://localhost:4000/admin/main.js:169356:20)
    at DocumentInfoProvider (http://localhost:4000/admin/main.js:192174:37)
    at DocumentDrawerContent (http://localhost:4000/admin/main.js:169494:17)
    at div
    at http://localhost:4000/admin/main.js:172228:13
    at div
    at Modal (http://localhost:4000/admin/main.js:33165:26)
    at dialog
    at Transition (http://localhost:4000/admin/main.js:264550:30)
    at CSSTransition (http://localhost:4000/admin/main.js:263662:35)
    at ModalWrap (http://localhost:4000/admin/main.js:33745:44)
    at Drawer (http://localhost:4000/admin/main.js:170600:19)
    at DocumentDrawer (http://localhost:4000/admin/main.js:169623:13)
    at div
    at AddNewRelation (http://localhost:4000/admin/main.js:186317:27)
    at div
    at div
    at Relationship (http://localhost:4000/admin/main.js:186715:13)
    at CheckForCondition (http://localhost:4000/admin/main.js:189522:24)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at div
    at RenderFields (http://localhost:4000/admin/main.js:182520:13)
    at div
    at div
    at div
    at AnimateHeight (http://localhost:4000/admin/main.js:218212:5)
    at CollapsibleProvider (http://localhost:4000/admin/main.js:168278:32)
    at div
    at Collapsible (http://localhost:4000/admin/main.js:168150:24)
    at div
    at BlockRow (http://localhost:4000/admin/main.js:183332:21)
    at DraggableSortableItem (http://localhost:4000/admin/main.js:170332:13)
    at div
    at SortableContext (http://localhost:4000/admin/main.js:29855:5)
    at DndContext (http://localhost:4000/admin/main.js:28467:5)
    at DraggableSortable (http://localhost:4000/admin/main.js:170415:13)
    at div
    at BlocksField (http://localhost:4000/admin/main.js:183809:58)
    at CheckForCondition (http://localhost:4000/admin/main.js:189522:24)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at div
    at RenderFields (http://localhost:4000/admin/main.js:182520:13)
    at div
    at div
    at TabsProvider (http://localhost:4000/admin/main.js:188264:25)
    at div
    at TabsField (http://localhost:4000/admin/main.js:188087:20)
    at CheckForCondition (http://localhost:4000/admin/main.js:189522:24)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at div
    at RenderFields (http://localhost:4000/admin/main.js:182520:13)
    at div
    at http://localhost:4000/admin/main.js:172228:13
    at div
    at div
    at DocumentFields (http://localhost:4000/admin/main.js:169747:13)
    at div
    at http://localhost:4000/admin/main.js:165996:19
    at CustomCollectionComponent (http://localhost:4000/admin/main.js:200668:13)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Switch (http://localhost:4000/admin/main.js:256938:29)
    at CollectionRoutes (http://localhost:4000/admin/main.js:200833:13)
    at E.t.Provider (http://localhost:4000/admin/main.js:306768:639)
    at form
    at Form (http://localhost:4000/admin/main.js:181468:93)
    at main
    at DefaultEditView (http://localhost:4000/admin/main.js:200411:55)
    at RenderCustomComponent (http://localhost:4000/admin/main.js:193303:13)
    at EditView (http://localhost:4000/admin/main.js:201365:25)
    at DocumentInfoProvider (http://localhost:4000/admin/main.js:192174:37)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Switch (http://localhost:4000/admin/main.js:256938:29)
    at div
    at div
    at Default (http://localhost:4000/admin/main.js:191326:20)
    at ActionsProvider (http://localhost:4000/admin/main.js:191479:28)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Switch (http://localhost:4000/admin/main.js:256938:29)
    at Route (http://localhost:4000/admin/main.js:256736:29)
    at Suspense
    at Routes (http://localhost:4000/admin/main.js:197751:63)
    at CustomProvider (http://localhost:4000/admin/main.js:191996:27)
    at NavProvider (http://localhost:4000/admin/main.js:173834:24)
    at DocumentEventsProvider (http://localhost:4000/admin/main.js:192080:35)
    at LoadingOverlayProvider (http://localhost:4000/admin/main.js:192691:35)
    at StepNavProvider (http://localhost:4000/admin/main.js:177451:28)
    at LocaleProvider (http://localhost:4000/admin/main.js:192884:27)
    at SearchParamsProvider (http://localhost:4000/admin/main.js:193388:33)
    at ThemeProvider (http://localhost:4000/admin/main.js:193490:26)
    at PreferencesProvider (http://localhost:4000/admin/main.js:193173:32)
    at AuthProvider (http://localhost:4000/admin/main.js:191585:25)
    at ModalProvider (http://localhost:4000/admin/main.js:33380:29)
    at Router (http://localhost:4000/admin/main.js:256355:30)
    at BrowserRouter (http://localhost:4000/admin/main.js:255460:35)
    at ScrollInfoProvider (http://localhost:4000/admin/main.js:35230:26)
    at WindowInfoProvider (http://localhost:4000/admin/main.js:35507:29)
    at ConfigProvider (http://localhost:4000/admin/main.js:191937:27)
    at Root (http://localhost:4000/admin/main.js:167181:25)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less

index.js:78 Uncaught TypeError: Cannot use 'in' operator to search for 'create' in null
    at DocumentControls (index.js:78:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
DocumentControls @ index.js:78
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 13 more frames
Show less
```

### To Reproduce

Hmmm, can't reproduce it by myself. But using several different collections in a relationship field will cause the same error.

### Payload Version

2.6.0

**Comment by dkirchhof** [comment]
Okay, I figured out that it has something todo with a custom plugin.
