### ISSUE TITLE
DuplicateFieldName in user collection

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#4902]
### Link to reproduction

-

### Describe the Bug

When I declare a field that already exists in user collection to merge settings with mine the build process stop to report the following error:
`DuplicateFieldName: A field with the name 'email' was found multiple times on the same level. Field names must be unique.`
This way to extend the native fields worked with the previous version ("payload": "2.4.0") 

### To Reproduce

1. Add the user collection in the config

```ts
const Users: CollectionConfig = {
	slug: "users",
	auth: true,
	fields: [
		{
			name: "email",
			type: "email",
			label: "Email",
			access: {
				read: ({ req, id }) => {
					// Extend logic
					const isAdmin = accessUserWithRole(req.user, "admin");
					const isSelf = accessCurrentUser(req.user, id);
					return isAdmin || isSelf;
				},
			},
		}
	],
}
```

2. install dependencies `yarn install`
3. Execute the build `npm run build`
4. The build stop with the error

### Payload Version

"payload": "2.8.2",

### Adapters and Plugins

"@payloadcms/bundler-webpack": "1.0.6", 		"@payloadcms/db-mongodb": "1.3.2", 		"@payloadcms/plugin-cloud-storage": "1.1.1", 		"@payloadcms/plugin-form-builder": "1.2.0", 		"@payloadcms/plugin-nested-docs": "1.0.11", 		"@payloadcms/plugin-seo": "2.2.0", 		"@payloadcms/richtext-lexical": "0.5.2", 		"@payloadcms/richtext-slate": "1.3.1",

**Comment by DanRibbens** [comment]
I tried this on latest v2.8.3 and didn't have any trouble using this as my users collection:

```ts
const Users: CollectionConfig = {
  slug: 'users',
  auth: true,
  fields: [
    {
      name: 'email',
      type: 'email',
      required: true,
      access: {
        read: () => true,
      },
    },
  ],
}
```

I didn't use all the plugins you mentioned, though that should be irrelevant.

**Comment by matteo-naif** [comment]
@DanRibbens 
I found the problem, is the seo plugin, the tabbedUI setting. With the followind minimal configuration the error is still visible. Without the "TabbedUI" it works.

```ts
export default buildConfig({
    db: mongooseAdapter({
        url: process.env.MONGODB_URI,
        connectOptions: {},
    }),
    editor: lexicalEditor({}),
    admin: {
        bundler: webpackBundler(),
    },
    collections: [
        {
            slug: "users",
            auth: true,
            fields: [
                {
                    name: "email", // required
                    type: "email", // required
                    required: true,
                    access: {
                        read: () => true,
                    },
                }
            ],
        },
    ],
    plugins: [
        seo({
            collections: ['users'],
            tabbedUI: true, // This is the problem
            fields: []
        })
    ],
})
```

I report the full error message

```bash
DuplicateFieldName: A field with the name 'email' was found multiple times on the same level. Field names must be unique.
    at /Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/fields/config/sanitize.js:81:23
    at Array.map (<anonymous>)
    at sanitizeFields (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/fields/config/sanitize.js:25:19)
    at sanitizeCollection (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/collections/config/sanitize.js:135:53)
    at /Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/config/sanitize.js:81:85
    at Array.map (<anonymous>)
    at sanitizeConfig (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/config/sanitize.js:81:45)
    at buildConfig (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/config/build.js:18:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadConfig (/Users/matteotortelli/progetti/evoluzione/evoluzione-backend/node_modules/payload/dist/config/load.js:30:34) {
  data: null,
  isOperational: true,
  isPublic: false,
  status: 500
}
```

**Comment by matteo-naif** [comment]
@DanRibbens any updates?
