### ISSUE TITLE
An error occurred while fetching your account

### ISSUE THREAD

**Issue by richleach** [payloadcms/payload#4943]
### Link to reproduction

https://thebeatentrail-supabase.vercel.app/

### Describe the Bug

I created a site deployment on Vercel for my Payload CMS application - everything has tested OK/passed on my dev server. 
I received confirmation that my site built successfully - no errors. When I click the link https://thebeatentrail-supabase.vercel.app/ the site loads (my headers/footers/nav are all there) but any page that has content from the /admin is not loading, I get a 404 page displayed (by design). The console displays....

Uncaught (in promise) Error: An error occurred while fetching your account.

When I drill down into the error message I can see the following:

 n.useEffect)(()=>{
                let e = async()=>{
                    try {
                        let e = await fetch("".concat("https://thebeatentrail-supabase.vercel.app", "/api/users/me"), {
                            method: "GET",
                            credentials: "include",
                            headers: {
                                "Content-Type": "application/json"
                            }
                        });
                        if (e.ok) {
                            let {user: t} = await e.json();
                            l(t || null),
                            s(t ? "loggedIn" : void 0)
                        } else
                            throw Error("An error occurred while fetching your account.")
                    } catch (e) {
                        throw l(null),
                        Error("An error occurred while fetching your account.")
                    }
                };

### To Reproduce

I visit the link https://thebeatentrail-supabase.vercel.app/

.... the homepage, as an example, and even the page /terms (are pages I built using the /admin console of the CMS) will not load and the corresponding 404 messages are displayed.

The page /videos is a hard-coded file served from the file system (not my Supabase database). This page loads successfully.

### Payload Version

"payload": "^2.0.0",

**Comment by richleach** [comment]
To reproduce this error: 
Make sure you're on version "payload": "^2.0.0". (view in package.json)
I run the payload web app locally on my server - command line "npm run dev".
After building the Payload app locally, and creating at least one page via the /admin, I verified that the page displayed, as expected in my local browser (localhost:3000).
I checked in my files into my github repo, on the main branch.
I logged into my vercel account at vercel.com.
I created a deployment following the instructions to point my deployment to the appropriate git branch.
I manually created (and double checked) the environment variables in that section of the Vercel site of my deployment.
I created the deployment, with no errors being reported from the Vercel build report nor the log files.
I open a new browser and enter the url given to me as assigned by the Vercel DNS for my project.
The first request loads the shell/files from the file server so my application is visible (headers/footers/nav bar are all present). A 404 error is displayed.
In the console is the reported error:

Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
 
        
        
GET https://thebeatentrail-supabase.vercel.app/ 404 (Not Found)
C @ 864-6d7511f2f6e1717f.js:1
ro @ fd9d1056-35ddd8600555f926.js:9
lp @ fd9d1056-35ddd8600555f926.js:9
om @ fd9d1056-35ddd8600555f926.js:9
iD @ fd9d1056-35ddd8600555f926.js:9
(anonymous) @ fd9d1056-35ddd8600555f926.js:9
(anonymous) @ fd9d1056-35ddd8600555f926.js:9
ib @ fd9d1056-35ddd8600555f926.js:9
M @ 864-6d7511f2f6e1717f.js:25
thebeatentrail-supabase.vercel.app/:1 Refused to load the font 'data:font/woff2;base64,d09GMgABAAAAAQ5sABIAAAADuOQAAQ4EAAEAgwAAAAAAAAAAAAAAAAAAAAAAAAAAG4SpIhy4XhSHMgZgAJJmCF4JgnMREAqGskiFyggSgrVoATYCJAOdOAuOXgAEIAWPGAfGYAyDGFsKfLME/nOMvX+HnQoMqyRqK6tt2TW8K2BDX9Umu4PZkCXwtMjpcHYNTx6UUmu30UdwcxxnVMvcNgAim7rdXiPZ////////////C5dF2ObuXM7ZvQeSECARwueHlaLVtkJEIaLRAI3ulswSE13cSPdM15RCyYQuuS7A0mBqpQO9pYZWQQMqa9lQb0dpJzHxHpLyCHIi8uBdwF58nNH+YOA40OpJvEjJtaokKaUkx/N5UeSinp5TWoW1vSpFjimBgeFGeCF66U0n6ZUN/qSqC4XC11GKUNmzSy2d5Jxyqw5JzGUlJUnyi0lKkE8BlxadTZsyRm8c1/Cti2hEjzIHnuOZ0fU6OjKc...FVw9csGnQ1BnbMbfzgRj3WjPytwZYWpPh3OtmsLZaNcxxqaGVqMVqFffFpU8bbs/0N1vG3POWfS7LUeB81TfHn+VbD7x/UnT3lXyFltHfdX6+X6Rzmg9d4dAISK7GlTj2zgME/JUwAETAECwABAUgUmAysrKI5shRwAchnFSMheQ8UoKlvnVbkW9mMeq2+bbO9EQ2q09Z9wzsADarYt4ftoamBDi8gmfbZKnl+lkZWyRx1VYVSIpVFXs9VXy9ytCyTNYt09YIAGKjqpDT22SgOdP5OsdAK/vOCXFnrpEwA/PPTJiopB7HxZV+MlaGCT/04K/LY3kjPYV/YR146Ggg+9sX6na/c2So+Epz3PXve3PKRylPIhNZASBUYVDIGhikiWc1jj/claeVCJvljX7JfvO+xhfTDIjSXBs4HV16Ol/BMfcuFQ4NRmDOWEh6diOI6NZmGl87N9J+r2JfpW2+5NhV/fGHLO57Yavbq7zaCewa/RDxp/aSH+luOPwAA' because it violates the following Content Security Policy directive: "font-src 'self'".

408-09d1499de47de96d.js:1 
        
        
       GET https://thebeatentrail-supabase.vercel.app/api/users/me 404 (Not Found)
e @ 408-09d1499de47de96d.js:1
(anonymous) @ 408-09d1499de47de96d.js:1
ap @ fd9d1056-35ddd8600555f926.js:9
aM @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
iB @ fd9d1056-35ddd8600555f926.js:9
(anonymous) @ fd9d1056-35ddd8600555f926.js:9
M @ 864-6d7511f2f6e1717f.js:25
408-09d1499de47de96d.js:1 Uncaught (in promise) Error: An error occurred while fetching your account.
    at e (408-09d1499de47de96d.js:1:2824)
e @ 408-09d1499de47de96d.js:1
await in e (async)
(anonymous) @ 408-09d1499de47de96d.js:1
ap @ fd9d1056-35ddd8600555f926.js:9
aM @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
aR @ fd9d1056-35ddd8600555f926.js:9
aO @ fd9d1056-35ddd8600555f926.js:9
iB @ fd9d1056-35ddd8600555f926.js:9
(anonymous) @ fd9d1056-35ddd8600555f926.js:9
M @ 864-6d7511f2f6e1717f.js:25

Clicking onto the error reveals this code as the offending error generator:
n.useEffect)(()=>{
                let e = async()=>{
                    try {
                        let e = await fetch("".concat("https://thebeatentrail-supabase.vercel.app", "/api/users/me"), {
                            method: "GET",
                            credentials: "include",
                            headers: {
                                "Content-Type": "application/json"
                            }
                        });
                        if (e.ok) {
                            let {user: t} = await e.json();
                            l(t || null),
                            s(t ? "loggedIn" : void 0)
                        } else
                            throw Error("An error occurred while fetching your account.")
                    } catch (e) {
                        throw l(null),
                        Error("An error occurred while fetching your account.")
                    }
                }
                ;


...which appears to be running in the file 
/src/app/_providers/Auth

Specifically the line:
const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/api/users/me`, { ...

...that reports the 404 when attempting to call the parsed url:
thebeatentrail-supabase.vercel.app/api/users/me

I hope this helps and get us closer to a resolution.

Rich

**Comment by richleach** [comment]
@AlessioGr I hope these details were helpful, were you able to reproduce this issue? I can be available via chat to walk you through any questions about this. 
Thanks again, Rich

**Comment by richleach** [comment]
In an effort to expedite this issue I was searching for some possible insight, 
![image](https://github.com/payloadcms/payload/assets/1168807/c1412ba5-1806-41b7-be68-162d4716fed2)

appears like a possible config issue/error might be afoot... The screenshot above indicates more than one CORS issue so I thought I'd add one or more of these errors to my whitelist (payload.config.ts)..... Trouble is, the fonts - as I understand Next.js builds - don't they download the fonts at build time so that you don't have to request them at page load time? And there's even a stripe.com call getting a CORS flag, and that's already in the cors: and csrf: sections.... so perhaps my updated question now is how would I deal with solving these CORS errors in Payload?

**Comment by richleach** [comment]
I updated my payload.config.ts file to include a few sites in the csrf array to reflect the possible domains that Vercel dynamically assigned during their build process. Not only did that not improve this problem it actually spawned a few more warnings:
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
admin:1 
        
        
       GET https://thebeatentrail-supabase-jhico4t77-michael-herrmanns-projects.vercel.app/admin 404 (Not Found)
admin:1 Refused to load the font 'data:font/woff2;base64,d09GMgABAAAAAQ5sABIAAAADuOQAAQ4EAAEAgwAAAAAAAAAAAAAAAAAAAAAAAAAAG4SpIhy4XhSHMgZgAJJmCF4JgnMREAqGskiFyggSgrVoATYCJAOdOAuOXgAEIAWPGAfGYAyDGFsKfLME/nOMvX+HnQoMqyRqK6tt2TW8K2BDX9Umu4PZkCXwtMjpcHYNTx6UUmu30UdwcxxnVMvcNgAim7rdXiPZ////////////C5dF2ObuXM7ZvQeSECARwueHlaLVtkJEIaLRAI3ulswSE13cSPdM15RCyYQuuS7A0mBqpQO9pYZWQQMqa9lQb0dpJzHxHpLyCHIi8uBdwF58nNH+YOA40OpJvEjJtaokKaUkx/N5UeSinp5TWoW1vSpFjimBgeFGeCF66U0n6ZUN/qSqC4XC11GKUNmzSy2d5Jxyqw5JzGUlJUnyi0lKkE8BlxadTZsyRm8c1/Cti2hEjzIHnuOZ0fU6OjKc...FVw9csGnQ1BnbMbfzgRj3WjPytwZYWpPh3OtmsLZaNcxxqaGVqMVqFffFpU8bbs/0N1vG3POWfS7LUeB81TfHn+VbD7x/UnT3lXyFltHfdX6+X6Rzmg9d4dAISK7GlTj2zgME/JUwAETAECwABAUgUmAysrKI5shRwAchnFSMheQ8UoKlvnVbkW9mMeq2+bbO9EQ2q09Z9wzsADarYt4ftoamBDi8gmfbZKnl+lkZWyRx1VYVSIpVFXs9VXy9ytCyTNYt09YIAGKjqpDT22SgOdP5OsdAK/vOCXFnrpEwA/PPTJiopB7HxZV+MlaGCT/04K/LY3kjPYV/YR146Ggg+9sX6na/c2So+Epz3PXve3PKRylPIhNZASBUYVDIGhikiWc1jj/claeVCJvljX7JfvO+xhfTDIjSXBs4HV16Ol/BMfcuFQ4NRmDOWEh6diOI6NZmGl87N9J+r2JfpW2+5NhV/fGHLO57Yavbq7zaCewa/RDxp/aSH+luOPwAA' because it violates the following Content Security Policy directive: "font-src 'self'".

408-09d1499de47de96d.js:1 Refused to connect to 'https://thebeatentrail-supabase.vercel.app/api/users/me' because it violates the following Content Security Policy directive: "connect-src 'self' https://checkout.stripe.com https://api.stripe.com https://maps.googleapis.com".

e @ 408-09d1499de47de96d.js:1
(anonymous) @ 408-09d1499de47de96d.js:1
ap @ fd9d1056-35ddd8600555f926.js:9
(anonymous) @ fd9d1056-35ddd8600555f926.js:9
M @ 864-6d7511f2f6e1717f.js:25
408-09d1499de47de96d.js:1 Refused to connect to 'https://thebeatentrail-supabase.vercel.app/api/users/me' because it violates the document's Content Security Policy.
e @ 408-09d1499de47de96d.js:1
(anonymous) @ 408-09d1499de47de96d.js:1

iB @ fd9d1056-35ddd8600555f926.js:9
(anonymous) @ fd9d1056-35ddd8600555f926.js:9
M @ 864-6d7511f2f6e1717f.js:25
408-09d1499de47de96d.js:1 Uncaught (in promise) Error: An error occurred while fetching your account.
    at e (408-09d1499de47de96d.js:1:2824)
e @ 408-09d1499de47de96d.js:1
await in e (async)
(anonymous) @ 408-09d1499de47de96d.js:1
ap @ fd9d1056-35ddd8600555f926.js:9

(anonymous) @ fd9d1056-35ddd8600555f926.js:9
M @ 864-6d7511f2f6e1717f.js:25
admin:1 The resource https://thebeatentrail-supabase-jhico4t77-michael-herrmanns-projects.vercel.app/_next/static/css/e8484a29af24051f.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

If the consistently reported issue is always '/api/users/me' - which appears to be an authentication file, is there a possible missing step during installation (or, in my case during deployment on Vercel)?
