### ISSUE TITLE
Auth Payload example fails with Error: Cannot find module 'payload/dist/utilities/commitTransaction'

### ISSUE THREAD

**Issue by DrazenMatijacic** [payloadcms/payload#5011]
### Link to reproduction

Configure as documented to use postgres and r

### Describe the Bug

Configure as postgres, yarn && yarn dev

```
$ cross-env PAYLOAD_PUBLIC_SEED=true PAYLOAD_DROP_DATABASE=true PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node src/server.ts -- -I`
Error: Cannot find module 'payload/dist/utilities/commitTransaction'
Require stack:
- /home/node/payload/examples/auth/payload/node_modules/@payloadcms/db-postgres/dist/migrate.js
- /home/node/payload/examples/auth/payload/node_modules/@payloadcms/db-postgres/dist/index.js
- /home/node/payload/examples/auth/payload/src/payload.config.ts
- /home/node/payload/examples/auth/payload/node_modules/payload/dist/config/load.js
- /home/node/payload/examples/auth/payload/node_modules/payload/dist/payload.js
- /home/node/payload/examples/auth/payload/node_modules/payload/dist/initHTTP.js
- /home/node/payload/examples/auth/payload/node_modules/payload/dist/index.js
- /home/node/payload/examples/auth/payload/src/server.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/node/payload/examples/auth/payload/node_modules/@payloadcms/db-postgres/dist/migrate.js:12:28)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .js] (/home/node/payload/examples/auth/payload/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
```

### To Reproduce

In package,json:
```
  "dependencies": {
    "@payloadcms/bundler-webpack": "latest",
    "@payloadcms/db-postgres": "latest",
    "@payloadcms/richtext-slate": "latest",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "payload": "latest"
  },
```
In payload.config.ts:
```
import { webpackBundler } from '@payloadcms/bundler-webpack'
import { postgresAdapter } from '@payloadcms/db-postgres'
import { slateEditor } from '@payloadcms/richtext-slate'
```
and
```
  // Configure the Postgres adapter here
  db: postgresAdapter({
    // Postgres-specific arguments go here.
    // `pool` is required.
    pool: {
      connectionString: process.env.DATABASE_URI,
    }
  }),
```
and in .env:
```
PAYLOAD_PUBLIC_SITE_URL=http://localhost:3001
PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000
DATABASE_URI=postgres://127.0.0.1/payload_example_auth
PAYLOAD_SECRET=PAYLOAD_AUTH_EXAMPLE_SECRET_KEY
COOKIE_DOMAIN=localhost
PAYLOAD_PUBLIC_SEED=true
PAYLOAD_DROP_DATABASE=true
```
and postgres:
```
payload_example_auth-# \l
                                                       List of databases
             Name             |  Owner   | Encoding | Collate |  Ctype  | ICU Locale | Locale Provider |   Access privileges
------------------------------+----------+----------+---------+---------+------------+-----------------+-----------------------
 demo                         | postgres | UTF8     | C       | C.UTF-8 |            | libc            |
 payload_example_auth         | node     | UTF8     | C       | C.UTF-8 |            | libc            |
 payload_example_multi_tenant | node     | UTF8     | C       | C.UTF-8 |            | libc            |
 postgres                     | postgres | UTF8     | C       | C.UTF-8 |            | libc            |
 template0                    | postgres | UTF8     | C       | C.UTF-8 |            | libc            | =c/postgres          +
                              |          |          |         |         |            |                 | postgres=CTc/postgres
 template1                    | postgres | UTF8     | C       | C.UTF-8 |            | libc            | =c/postgres          +
                              |          |          |         |         |            |                 | postgres=CTc/postgres
```
Please note that multitenant app works as expected.

### Payload Version

main

### Adapters and Plugins

db-postgres

**Comment by kasbah** [comment]
`rm yarn.lock && yarn` helped when I ran into the same thing with the `draft-preview` example

**Comment by DanRibbens** [comment]
I tested on latest packages and I am not seeing this error. As Kasbah mentioned, delete the yarn.lock and node_modules to see if that clears it up after a fresh install.

Feel free to tag me if you still have any troubles and I will reopen this issue. Thanks!

**Comment by kasbah** [comment]
My understanding of it was that the yarn.lock in the examples needs to be
refreshed in this repo.

**Comment by DrazenMatijacic** [comment]
I can confirm removing yarn.lock has resolved the issue.

Kind regards,
Drazen

**Comment by lekterable** [comment]
For the people experiencing this error straight out of the template:

1. Update `payload` - 2.0.0 -> 2.19.3 in my case
2. Remove `node_modules` and `package-lock.json` / `yarn.lock` / `pnpm-lock.yaml`
3. Reinstall

@DanRibbens maybe it would make sense to update dependencies in the `create-payload-app` templates? 

they seem to be broken out of the box which is a bit frustrating
