### ISSUE TITLE
Lexical: Omitted RichText field's `editor` property in Block fields causes type generation errors

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#5163]
### Describe the Bug

When using `lexicalEditor` and using `richText` fields in a Block's `fields`, omitting the `editor` property will cause a type generation error. This does not happen when `editor` is omitted in a Collection's `fields`.

I don't know if Slate has the same issue (there doesn't seem to be tests for Slate in `test/fields`)

```
> payload-monorepo@0.0.1 dev:generate-types /Users/tyteen4a03/Documents/CodeProjects/payload
> ts-node -T ./test/generateTypes.ts "fields"

[15:18:43] INFO (payload): Compiling TS types for Collections and Globals...
[15:18:43] INFO (payload): Starting Payload...
/Users/tyteen4a03/Documents/CodeProjects/payload/packages/payload/src/utilities/configToJSONSchema.ts:147
            if (field.editor.outputSchema) {
                             ^
TypeError: Cannot read properties of undefined (reading 'outputSchema')
    at reduce (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/payload/src/utilities/configToJSONSchema.ts:147:30)
    at Array.reduce (<anonymous>)
    at fieldsToJSONSchema (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/payload/src/utilities/configToJSONSchema.ts:98:14)
    at map (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/payload/src/utilities/configToJSONSchema.ts:321:45)
    at Array.map (<anonymous>)
    at reduce (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/payload/src/utilities/configToJSONSchema.ts:320:37)
    at Array.reduce (<anonymous>)
    at fieldsToJSONSchema (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/payload/src/utilities/configToJSONSchema.ts:98:14)
    at modifyOutputSchema (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/richtext-lexical/src/field/features/Blocks/index.ts:43:31)
    at Object.outputSchema (/Users/tyteen4a03/Documents/CodeProjects/payload/packages/richtext-lexical/src/index.ts:161:24)
```

### To Reproduce

1. Modify `test/fields/collections/Lexical/blocks.ts`, and comment out the `editor` property for `RichTextBlock`'s `richText` field.
2. Run `pnpm dev:generate-types fields`

### Payload Version

2.11.1

### Adapters and Plugins

richtext-lexical

**Comment by carstenblt** [comment]
This is #5050

**Comment by revnelson** [comment]
> This is #5050

While true, that issue is still tagged as `[can't-reproduce]`, so more attention on this is good.

**Comment by carstenblt** [comment]
;) True. Though the other issue has a reproduction repo now.

**Comment by AlessioGr** [comment]
Closing in favor of #5050
