### ISSUE TITLE
Trying to create new app but getting type "serial" does not exist on startup

### ISSUE THREAD

**Issue by brynshanahan** [payloadcms/payload#5263]
### Link to reproduction

https://github.com/brynshanahan/brynshanahan-com

### Describe the Bug

When trying to start a new app with Postgres + Docker I am getting `unhandledRejection error: type "serial" does not exist`.

I'm starting the database in docker and I am running payload from WSL

![image](https://github.com/payloadcms/payload/assets/37826020/6c6b0922-806e-4b0d-bba8-d0377c9903c2)

### To Reproduce

I dont think I've modified anything from the starter template

### Payload Version

2.11.2

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by fofoy** [comment]
It seems like your `DATABASE_URI` is not defined ?

The error code `42704` indicates that there is an undefined object definition somewhere.
![image](https://github.com/payloadcms/payload/assets/1737124/4e2fab7d-7149-4648-8cf2-b460a4af3138)

**Comment by j-mcgregor** [comment]
@fofoy  I'm getting this too; I'll trying to connect to a Xata database - the tables have been created in Xata but I get the following stack tract

```
 ⨯ Internal error: error: type "serial" does not exist
    at /<root>/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/<root>/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/<root>/node_modules/drizzle-kit/payload.js:36648:9)
    at async pushDevSchema (../../node_modules/@payloadcms/db-postgres/dist/utilities/pushDevSchema.js:47:5)
    at async Object.connect (../../node_modules/@payloadcms/db-postgres/dist/connect.js:84:5)
    at async BasePayload.init (../../node_modules/payload/dist/index.js:215:13)
digest: "1337719887"
 ⨯ Internal error: error: type "serial" does not exist
    at /<root>/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/<root>/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/<root>/node_modules/drizzle-kit/payload.js:36648:9)
    at async pushDevSchema (../../node_modules/@payloadcms/db-postgres/dist/utilities/pushDevSchema.js:47:5)
    at async Object.connect (../../node_modules/@payloadcms/db-postgres/dist/connect.js:84:5)
    at async BasePayload.init (../../node_modules/payload/dist/index.js:215:13)
digest: "1337719887"
 ⨯ Internal error: error: type "serial" does not exist
    at /<root>/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/<root>/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/<root>/node_modules/drizzle-kit/payload.js:36648:9)
    at async pushDevSchema (../../node_modules/@payloadcms/db-postgres/dist/utilities/pushDevSchema.js:47:5)
    at async Object.connect (../../node_modules/@payloadcms/db-postgres/dist/connect.js:84:5)
    at async BasePayload.init (../../node_modules/payload/dist/index.js:215:13)
```

**Comment by r1tsuu** [comment]
Hey @brynshanahan, @fofoy is probably right, you didn't configure you `.env` with `DATABASE_URI` and so it's `undefined` from your screenshot.
![image](https://github.com/user-attachments/assets/dc3bc80d-4526-48b6-9994-842f715478d3)

If you still can reproduce it on the latest beta we can look again, closing.
