### ISSUE TITLE
Error while uploading some images

### ISSUE THREAD

**Issue by jacopotabani** [payloadcms/payload#539]
# Bug Report

I have created a collection Media, following the docs example. 
Some images are uploaded successfully, others not. Every time I try to upload a specific image, it give me “unknown error” and the deployment crash. I don’t understand why some images can be uploaded and some not.

## Expected Behavior

It should upload correctly all the images
## Current Behavior

Some images are uploaded correctly, others not.

## Detailed Description

Here are the Media collections created and the error log retrieved by k8s.

Media:
````
const Media: any = {
  slug: "media",
  upload: {
    staticURL: "/media",
    staticDir: "/media",
    imageSizes: [
      {
        name: "thumbnail",
        width: 400,
        height: 300,
        crop: "centre",
      },
      {
        name: "card",
        width: 768,
        height: 1024,
        crop: "centre",
      },
      {
        name: "tablet",
        width: 1024,
        // By specifying `null` or leaving a height undefined,
        // the image will be sized to a certain width,
        // but it will retain its original aspect ratio
        // and calculate a height automatically.
        height: null,
        crop: "centre",
      },
    ],
    adminThumbnail: "thumbnail",
    mimeTypes: ["image/*", "application/pdf"],
  },
};

export default Media;
````
Error log:
````
/app/node_modules/payload/dist/uploads/mimeTypeValidator.js:6
`````
````
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at /app/node_modules/payload/dist/uploads/mimeTypeValidator.js:6:46
    at Array.some (<anonymous>)
    at Object.validate (/app/node_modules/payload/dist/uploads/mimeTypeValidator.js:6:30)
    at validationPromise (/app/node_modules/payload/dist/fields/validationPromise.js:13:49)
    at /app/node_modules/payload/dist/fields/traverseFields.js:305:79
    at /app/node_modules/payload/dist/fields/performFieldOperations.js:70:45
    at Array.forEach (<anonymous>)
    at Payload.performFieldOperations (/app/node_modules/payload/dist/fields/performFieldOperations.js:70:24)
    at async Payload.create (/app/node_modules/payload/dist/collections/operations/create.js:91:31)
    at async Payload.create (/app/node_modules/payload/dist/collections/requestHandlers/create.js:10:21)
`````

**Comment by DanRibbens** [comment]
@jacopotabani, you should be good to go after upgrading to `0.16.0`!
