### ISSUE TITLE
Error ZlibError: zlib: unexpected end of file no create project in folder

### ISSUE THREAD

**Issue by lliccien** [payloadcms/payload#5402]
### Describe the Bug

When I run `npx create-payload-app@latest` it asks me for the template folder and the database and after a while it throws the error: 

ZlibError: zlib: unexpected end of file

### To Reproduce

npx create-payload-app@latest

Welcome to Payload. Let's create a project!

✔ Project name? … resume-dev
✔ Choose project template › blank
✔ Select a database › MongoDB
✔ Enter MongoDB connection string … mongodb://127.0.0.1/resume-dev

Creating project in /Users/lliccien/www/resume-dev

ZlibError: zlib: unexpected end of file
at Unzip.write (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:1322:22)
at Unzip.flush (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:1273:10)
at Unzip.end (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:1279:10)
at Unpack.end (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:3989:21)
at Yallist. (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:903:18)
at Yallist.forEach (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:240:8)
at ReadStream.emit (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:900:18)
at ReadStream.emit (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:3262:22)
at [maybeEmitEnd] (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:864:12)
at ReadStream.end (/Users/lliccien/.npm/_npx/a78262c2ecc815d9/node_modules/degit/dist/index-688c5d50.js:744:27) {
code: 'Z_BUF_ERROR',
errno: -5,
recoverable: false,
file: '/Users/lliccien/.degit/github/payloadcms/payload/1c0d43c61a0e29bc9de50a4e608cb7dff9d5cd48.tar.gz',
cwd: '/Users/lliccien/www/resume-dev',
tarCode: 'TAR_ABORT'
}

### Payload Version

node -v && npm -v v20.11.1 10.2.4

**Comment by paulpopus** [comment]
Hey, I failed to reproduce this. Have you verified that your installation of node is without issues?

Can reopen this issue with more reproducible information.

**Comment by TimSchulzRC** [comment]
Might be related to issue #7463. The same fix could work here as well.
