### ISSUE TITLE
could not find commit hash for HEAD

### ISSUE THREAD

**Issue by ppzhuya** [payloadcms/payload#5422]
### Describe the Bug

when i create payload app and i'm sure i follow the guide step by step,it make a mistake

### To Reproduce

PS C:\Users\ppzhu> npx create-payload-app@latest
Need to install the following packages:
create-payload-app@1.0.0
Ok to proceed? (y) y

  Welcome to Payload. Let's create a project!

√ Project name? ... my-website
√ Choose project template » website
√ Select a database » MongoDB
√ Enter MongoDB connection string ... mongodb+srv://***************************.mongodb.net/?retryWrites=true&w=majority&appName=my-website

  Creating project in C:\Users\ppzhu\nextjs\my-website

DegitError: could not find commit hash for HEAD
    at Degit._cloneWithTar (C:\Users\ppzhu\AppData\Local\npm-cache\_npx\a78262c2ecc815d9\node_modules\degit\dist\index-688c5d50.js:14258:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Degit.clone (C:\Users\ppzhu\AppData\Local\npm-cache\_npx\a78262c2ecc815d9\node_modules\degit\dist\index-688c5d50.js:14096:4)
    at async createProject (C:\Users\ppzhu\AppData\Local\npm-cache\_npx\a78262c2ecc815d9\node_modules\create-payload-app\dist\lib\create-project.js:67:9)
    at async Main.init (C:\Users\ppzhu\AppData\Local\npm-cache\_npx\a78262c2ecc815d9\node_modules\create-payload-app\dist\main.js:79:21)
    at async main (C:\Users\ppzhu\AppData\Local\npm-cache\_npx\a78262c2ecc815d9\node_modules\create-payload-app\dist\index.js:8:5) {
  code: 'MISSING_REF',
  ref: 'HEAD'
}

### Payload Version

latest

**Comment by denolfe** [comment]
Looks like this error could come from a few things:

- Network connection issues. Are behind a proxy of some sort? A spotty internet connection?
- Old version of git. What version are you running?

**Comment by denolfe** [comment]
Happy to re-open if you can consistently recreate.
