### ISSUE TITLE
richtext-lexical: Deleting a linked upload crashes Payload

### ISSUE THREAD

**Issue by GeekPro101** [payloadcms/payload#5493]
### Describe the Bug

If you link a file through Upload in Lexical, then delete that item, on opening the collection containing the lexical field, Payload will crash completely

It's also not possible to then delete the offending item through the Payload admin UI, as it crashes!

```txt
/home/node/app/node_modules/payload/dist/collections/operations/findByID.js:72
                throw new _errors.NotFound(t);
                      ^

NotFound: The requested resource was not found.
    at findByID (/home/node/app/node_modules/payload/dist/collections/operations/findByID.js:72:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.converter (/home/node/app/node_modules/@payloadcms/richtext-lexical/dist/field/features/Upload/index.js:77:60)
    at async Promise.all (index 1)
    at async convertLexicalNodesToHTML (/home/node/app/node_modules/@payloadcms/richtext-lexical/dist/field/features/converters/html/converter/index.js:31:23)
    at async convertLexicalToHTML (/home/node/app/node_modules/@payloadcms/richtext-lexical/dist/field/features/converters/html/converter/index.js:21:16)
    at async hooks.afterRead (/home/node/app/node_modules/@payloadcms/richtext-lexical/dist/field/features/converters/html/field/index.js:116:28)
    at async /home/node/app/node_modules/payload/dist/fields/hooks/afterRead/promise.js:151:41
    at async promise (/home/node/app/node_modules/payload/dist/fields/hooks/afterRead/promise.js:128:13) {
  data: null,
  isOperational: true,
  isPublic: false,
  status: 404
}

Node.js v20.11.1
```

### To Reproduce

1. Create a collection (A) that permits uploads and upload a file
2. Create a collection (B) with a richtext-lexical field with the Upload Feature
3. Link to the file using the Upload feature in lexical
4. Delete the file
5. Attempt to access collection B through the admin UI - crashes

### Payload Version

2.11.2

### Adapters and Plugins

bundler-webpack, db-mongodb, lexical-richtext

**Comment by AlessioGr** [comment]
Fixed in #5752
