### ISSUE TITLE
Server won't start when using long relation slug

### ISSUE THREAD

**Issue by MattRvt** [payloadcms/payload#572]
# Bug Report

## Expected Behavior
Create a relationship between test and longLongLongLongLongLongLongLong with the following code

### Test.ts
``` typescript

import { CollectionConfig } from 'payload/types';

const Test: CollectionConfig = {
  slug: 'test',
  admin: {
    defaultColumns: [],
    useAsTitle: 'name',
  },
  access: {
    create: () => true,
    read: () => true,
    update: () => true,
    delete: () => true,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
    },
    {
      name: 'longRelation',
      type: 'relationship',
      relationTo: 'longLongLongLongLongLongLongLong'
    },
  ],
}

export default Test;
```

### LongLongLongLongLongLongLongLong.ts
``` typescript

import { CollectionConfig } from 'payload/types';

const LongLongLongLongLongLongLongLong: CollectionConfig = {
  slug: 'longLongLongLongLongLongLongLong',
  admin: {
    defaultColumns: [],
    useAsTitle: 'name',
  },
  access: {
    create: () => true,
    read: () => true,
    update: () => true,
    delete: () => true,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
    },
  ],
}

export default LongLongLongLongLongLongLongLong;
```

## Current Behavior

I get the following error:
```
[15:46:10] INFO (payload): Starting Payload...
TypeError: Cannot read properties of undefined (reading 'config')
    at relationship (C:\depots_git\magellan\magellan_backend\node_modules\payload\src\graphql\schema\buildMutationInputType.ts:107:68)
    at C:\depots_git\magellan\magellan_backend\node_modules\payload\src\graphql\schema\buildMutationInputType.ts:147:29
    at Array.reduce (<anonymous>)
    at InitializeGraphQL.buildMutationInputType (C:\depots_git\magellan\magellan_backend\node_modules\payload\src\graphql\schema\buildMutationInputType.ts:142:29)
    at C:\depots_git\magellan\magellan_backend\node_modules\payload\src\collections\graphql\init.ts:114:68
    at Array.forEach (<anonymous>)
    at InitializeGraphQL.registerCollections (C:\depots_git\magellan\magellan_backend\node_modules\payload\src\collections\graphql\init.ts:26:33)
    at new InitializeGraphQL (C:\depots_git\magellan\magellan_backend\node_modules\payload\src\graphql\index.ts:99:10)
    at Payload.init (C:\depots_git\magellan\magellan_backend\node_modules\payload\src\index.ts:181:30)
    at Object.<anonymous> (C:\depots_git\magellan\magellan_backend\src\server.ts:15:9)
Waiting for the debugger to disconnect...
[nodemon] app crashed - waiting for file changes before starting...
```

## Steps to Reproduce
1. create two entities with the child on having a long slug
2. start the server
3. get the error and cry

**Comment by jmikrut** [comment]
Hey @MattRvt — turns out this isn't related to _**length**_—it's actually related to the fact that your `longLongLongLongLongLongLongLong` slug is not "URL-friendly". Collection slugs should be "kebab-case", and if you change it to `long-long-long-long`-etc, your issue will go away.

We attempt to sanitize collection and global slugs for you on the backend, but clearly in `buildMutationType`, we missed a spot. In the future, we will build further validation rules into config `slug`s to ensure that you _**can't**_ pass a non-URL-friendly `slug`, which will improve the dev experience here.

What do you think? Going to close for now but we'll improve `slug` validation in the future. 👍

**Comment by MattRvt** [comment]
Of cours... this is what happen when I try new thing on Friday evening.

Indeed, error could be more explicit.

Thanks @jmikrut  for your help, the framework look very promising, and I love the UI design.
