### ISSUE TITLE
plugin-cloud-storage: S3 upload error

### ISSUE THREAD

**Issue by johnark88** [payloadcms/payload#5956]
### Describe the Bug

Trying to get a media gallery going but can not seem to figure this bug out. Any help would be great! 
I have the plugin setup, the collection created, but when I click save to upload a new image I get 
`Expected closing tag 'META' (opened in line 2, col 13) instead of closing tag 'HEAD'.:4:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.",` 

I have not been able to resolve this and not really sure what the cause could be. I have tried many different images and am getting the same error. 

Thanks!
    
  Full Error: 
  ```
  err: {
      "type": "Error",
      "message": "Expected closing tag 'META' (opened in line 2, col 13) instead of closing tag 'HEAD'.:4:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.",
      "stack":
          Error: Expected closing tag 'META' (opened in line 2, col 13) instead of closing tag 'HEAD'.:4:1
            Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
              at XMLParser.parse (/Users/john.arkema/Documents/Work/payloadTest/payload/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:30:21)
              at /Users/john.arkema/Documents/Work/payloadTest/payload/node_modules/@aws-sdk/core/dist-cjs/index.js:388:26
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at runNextTicks (node:internal/process/task_queues:64:3)
              at listOnTimeout (node:internal/timers:540:9)
              at processTimers (node:internal/timers:514:7)
              at async parseXmlErrorBody (/Users/john.arkema/Documents/Work/payloadTest/payload/node_modules/@aws-sdk/core/dist-cjs/index.js:409:17)
              at async de_CommandError (/Users/john.arkema/Documents/Work/payloadTest/payload/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4723:11)
              at async /Users/john.arkema/Documents/Work/payloadTest/payload/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
              at async /Users/john.arkema/Documents/Work/payloadTest/payload/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
      "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
      }
    }
   ```
   
   s3 Adapter: 
   ```
 cloudStorage({
      enabled: true,
      collections: {
        media: {
          adapter: s3Adapter({
            config: {
              region: process.env.REGION,
              endpoint: process.env.CDN_URL,
              forcePathStyle: true,
              bucketEndpoint: false,
            },
            acl: 'private',
            bucket: process.env.AWS_BUCKET_NAME,
          }),
        },
      },
    }),
```    
   
   
   Media.ts collection config: 
   ```
     slug: 'media',
  upload: {
    adminThumbnail: 'thumbnail',
    crop: false,
    disableLocalStorage: true,
    focalPoint: false,
    mimeTypes: ['image/*', 'application/pdf'],
    staticURL: `${process.env.URL}${process.env.ROOT_PATH}`,
    imageSizes: [
      {
        name: 'thumbnail',
        width: 150,
        height: undefined,
        withoutEnlargement: true,
        withoutReduction: true,
        formatOptions: { format: 'webp', options: { lossless: true } },
      },

      {
        name: 'medium',
        width: 300,
        height: undefined,
        withoutEnlargement: true,
        withoutReduction: true,
        formatOptions: { format: 'webp', options: { lossless: true } },
      },
      {
        name: 'large',
        width: 1024,
        height: undefined,
        withoutEnlargement: true,
        withoutReduction: true,
        formatOptions: { format: 'webp', options: { lossless: true } },
      },
    ],
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: false,
    },
  ],
}
``` 
    
    

### To Reproduce

Install payload
Install payload-cloud-storage
Setup payload config with media following Upload overview
Setup adapter for s3 - I have CLI profiles & SSO setup so I am not using keys or tokens
Attempt upload. 

### Payload Version

2.12.1

### Adapters and Plugins

plugin-cloud-storage: 1.1.2

**Comment by denolfe** [comment]
Awesome, glad you were able to sort it out.
