### ISSUE TITLE
Cannot create first user because of form validation

### ISSUE THREAD

**Issue by TSFoster** [payloadcms/payload#5980]
### Describe the Bug

This is my first time trying out Payload, I'm really excited to try it out (specifically v3).

I'm having trouble creating my first user. I've tried with the `blank-3.0` template across every release of the beta. I've tried with a fresh install of Chrome with no extensions. The form always complains about the password field or the confirm-password field:

![2024-04-23 20 11 10](https://github.com/payloadcms/payload/assets/510520/40891c3a-18fc-4e5c-a2c4-695ed3a0aa3f)

I tried with the `blank` template (i.e. v2) and it works as expected.

Using mongo (but also tried Postgres). On an M1 MacBook Pro. I am definitely typing the same password in to both fields.

This is the error in the console:

```
ERROR: ValidationError: The following field is invalid: password
    at generatePasswordSaltHash (webpack-internal:///(rsc)/./node_modules/payload/dist/auth/strategies/local/generatePasswordSaltHash.js:23:15)
    at registerLocalStrategy (webpack-internal:///(rsc)/./node_modules/payload/dist/auth/strategies/local/register.js:30:120)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createOperation (webpack-internal:///(rsc)/./node_modules/payload/dist/collections/operations/create.js:166:19)
    at async registerFirstUserOperation (webpack-internal:///(rsc)/./node_modules/payload/dist/auth/operations/registerFirstUser.js:25:24)
    at async Object.registerFirstUser [as first-register] (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/rest/auth/registerFirstUser.js:25:20)
    at async eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/rest/index.js:412:35)
    at async /path/to/payload/templates/blank-3.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53466
    at async e_.execute (/path/to/payload/templates/blank-3.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44747)
    at async e_.handle (/path/to/payload/templates/blank-3.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54720)
    at async doRender (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:1364:42)
    at async cacheEntry.responseCache.get.routeKind (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:1578:40)
    at async DevServer.renderToResponseWithComponentsImpl (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:1498:28)
    at async DevServer.renderPageComponent (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:1915:24)
    at async DevServer.renderToResponseImpl (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:1953:32)
    at async DevServer.pipeImpl (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:900:25)
    at async NextNodeServer.handleCatchallRenderRequest (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/base-server.js:796:17)
    at async /path/to/payload/templates/blank-3.0/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/path/to/payload/templates/blank-3.0/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/path/to/payload/templates/blank-3.0/node_modules/next/dist/server/lib/start-server.js:142:13)
```

### To Reproduce

```sh
git checkout v3.0.0-beta12
cd templates/beta-3.0
cp .env.example .env
yarn && yarn dev
```

### Payload Version

3.0.0-beta.12

**Comment by paulpopus** [comment]
We're investigating right now and adding an e2e test to catch this in the future

**Comment by ThnxFredrik** [comment]
Hey ya'll 👋🏼

I had the same issue as @TSFoster. Bu, after updating to beta-15 I'm having a different experience. Now it tells me that I've not entered a valid email.

![image](https://github.com/payloadcms/payload/assets/96437476/df5065a3-1d97-4849-b41f-4cb2e0f48790)

**Comment by ThnxFredrik** [comment]
> Hey ya'll 👋🏼
> 
> I had the same issue as @TSFoster. Bu, after updating to beta-15 I'm having a different experience. Now it tells me that I've not entered a valid email.
> 
> ![image](https://private-user-images.githubusercontent.com/96437476/325627619-df5065a3-1d97-4849-b41f-4cb2e0f48790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTE4MTUsIm5iZiI6MTcxNDA1MTUxNSwicGF0aCI6Ii85NjQzNzQ3Ni8zMjU2Mjc2MTktZGY1MDY1YTMtMWQ5Ny00ODQ5LWI0MWYtNGNiMmUwZjQ4NzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Mzc1NzBkY2Q2N2JkNDU2N2Q3OTQ1ZGMyZjZjOWRlNzgxMjNjZTMzYmI4MzYxNjY1YzU0YzVjYjdmMDVkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hlW80EV6ivXNQjWbE9uXlbNIZ2x3LgkzQ7meTtKVBHA)

Well, it was kina a false alarm. I've been having this issue whole day, but after I posted above comment I tried the email "admin@me.com" and it worked 🤔 Previous emails I tested ended with `.se` or `.email`. Do not know if this matters though...

**Comment by joedawson** [comment]
> Well, it was kina a false alarm. I've been having this issue whole day, but after I posted above comment I tried the email "[admin@me.com](mailto:admin@me.com)" and it worked 🤔 Previous emails I tested ended with `.se` or `.email`. Do not know if this matters though...

I experienced similar issues, with a `.me` TLD. However it was intermittent too with a `.com` also.

I raised this in Discord and was advised to use `beta.11` for the time being which seemed to work locally. However when I deployed it to Vercel for testing, I still had the issue I had on 15 so I'm bit unsure if the issues exists further back than 14/15.

But as I mentioned it was intermittent for me so it's been hard to replicate.

**Comment by joedawson** [comment]
Just confirming I am able to create a first user (including a `.me` TLD, if this at all relevant) with `beta.18` in a fresh Next app.
