### ISSUE TITLE
Docker cannot Build without access to database - ERROR (payload): Error: cannot connect to MongoDB. Details: getaddrinfo ENOTFOUND mongo

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [payloadcms/payload#6330]
### Describe the Bug

Currently trying to build and deploy an docker image for payload. Maybe there is a different process in mind for how to deploy this to production, but my flow is:

```
1. Commit code to main 
2. CI builds the image with the changes to the site 
3. Deploy to docker image repository 
4. CD pulls this image and deploys it to an already running cluster
```
Now when I go to build the project using the `Dockerfile` it looks that it is trying to access the database during build:

```
 > [builder 2/2] RUN yarn build:
0.557 yarn run v1.22.19
0.580 $ cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next
0.755 $ cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload build
16.94 $ tsc --project tsconfig.server.json
19.88 $ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
20.23 $ cross-env PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js NEXT_BUILD=true node dist/server.js
53.35 [22:30:01] ERROR (payload): Error: cannot connect to MongoDB. Details: getaddrinfo ENOTFOUND mongo
53.38 error Command failed with exit code 1.
53.38 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
53.40 error Command failed with exit code 1.
53.40 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Which makes this not possible as you cannot deploy without already having access to the DB. Meaning either the CI pipeline has to be within the cluster with the MongoDB instance, or you have to expose the MongoDB instance outside the cluster to the CI pipeline.

Is there any way to build this as an image, then deploy? Or is this a limitation that this cannot be used in Swarm/K8s? 

Is it possible to have the DB scripts run once the image has deployed, instead of having them run while building?

Thanks! :)

### To Reproduce

1. Clone the demo website.
2. Update the .env file to have valid values
3. Run `docker build .` 

### Payload Version

2.13.0

**Comment by Nathan-Nesbitt** [comment]
Looks that it might be possible? The problem of using the dockerfile provided is that the build command looks like the following

```json
{
    "build": "cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next",
}
```

The `yarn build:next` is a problem because it assumes that the DB is available, so by adding a new command option we can avoid it and run it when the app is deployed:

```json
{
    "build:docker": "cross-env NODE_ENV=production yarn build:payload && yarn build:server && yarn copyfiles",
}
```

Then it might be possible to build the dockerfile a little differently. 

```dockerfile
FROM node:20.13-alpine as base

#... all the lines before this point, update the yarn build process
FROM installer as builder
COPY . .
RUN yarn build:docker

# ... all the other lines in the basic dockerfile 
CMD ["yarn", "build:next"]
```

The only thing I am running into is the following once we run it:

```sh
payload-1  | unhandledRejection Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
payload-1  |     at findPagesDir (/home/node/app/node_modules/next/dist/lib/find-pages-dir.js:42:15)
payload-1  |     at /home/node/app/node_modules/next/dist/build/index.js:404:73
payload-1  |     at async Span.traceAsyncFn (/home/node/app/node_modules/next/dist/trace/trace.js:154:20)
payload-1  |     at async build (/home/node/app/node_modules/next/dist/build/index.js:366:9)

```

Which doesn't make sense to me, as this is the contents of the docker image, which shows that the `app` folder exists. Unless it's not supposed to be in that folder, and rather in the root?

![image](https://github.com/payloadcms/payload/assets/12765521/e089c30c-ec14-489b-85ad-c657374e4854)

**Comment by Nathan-Nesbitt** [comment]
I'm actually going to close this as it may be better to address this on the demo github repo in a conversation, as I think it's just that this isn't set up to be run using docker?
