### ISSUE TITLE
bug(db-postgres): Duplicated ID error when duplicate array/block includes array/block.

### ISSUE THREAD

**Issue by SimYunSup** [payloadcms/payload#6583]
### Link to reproduction

https://github.com/SimYunSup/example-list/tree/payload/bug-postgres-nested-id

### Describe the Bug

Duplicated ID error when duplicate Array/Block that includes Array/Block.

<details>
<summary>
Reported Bug
</summary>

```text
[16:56:40] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'nested_blocks_just_text_pkey')
    at upsertRow (D:\GithubProject\example-list\node_modules\.pnpm\@payloadcms+db-postgres@0.8.4_@types+react@18.3.3_payload@2.18.3_@swc+helpers@0.5.11_@types+r_utjmzo3j7ceboprn5scvypgwvm\node_modules\@payloadcms\db-postgres\src\upsertRow\index.ts:318:57)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.updateOne (D:\GithubProject\example-list\node_modules\.pnpm\@payloadcms+db-postgres@0.8.4_@types+react@18.3.3_payload@2.18.3_@swc+helpers@0.5.11_@types+r_utjmzo3j7ceboprn5scvypgwvm\node_modules\@payloadcms\db-postgres\src\update.ts:44:18)
    at async updateByID (D:\GithubProject\example-list\node_modules\.pnpm\payload@2.18.3_@swc+helpers@0.5.11_@types+react@18.3.3_esbuild@0.19.12_typescript@5.4.5_webpa_w2wwwoljy4lt2mm3kbswof65oi\node_modules\payload\src\collections\operations\updateByID.ts:269:16)
    at async updateByIDHandler (D:\GithubProject\example-list\node_modules\.pnpm\payload@2.18.3_@swc+helpers@0.5.11_@types+react@18.3.3_esbuild@0.19.12_typescript@5.4.5_webpa_w2wwwoljy4lt2mm3kbswof65oi\node_modules\payload\src\collections\requestHandlers\updateByID.ts:43:17)
```

</details>

### To Reproduce

1. Create a `Nested` collection item.
2. Fill in the fields in one of the order listed below.
  1. Block in Block
    - Create `nested-block` in `blocks`
    - Create `just-text` in `nested`
    - Fill `title`(optional)
  2. Array in Block
    - Create `nested-array` in `blocks`
    - Create item in `nested`
    - Fill `title`(optional)
  3. Block in Array
    - Create item in `nestedArrayBlocks`
    - Create `just-text` in `nested`
    - Fill `title`(optional)
  4. Block in Block
    - Create item in `nestedArrayArray`
    - Create item in `nested`
    - Fill `title`(optional)
3. Duplicates any top-level Block or Array.
4. When you submit, you should get an error.

I think It must replace nested ID.

And I think Same in `3.0.0-beta.39` because `DUPLICATE_ROW` has same logic.

### Payload Version

2.18.3

### Adapters and Plugins

@payloadcms/db-postgres@0.8.4, @payloadcms/bundler-webpack@1.0.6

**Comment by siobahnschuck** [comment]
Seeing the same issue with `3.0.0-beta.36` - but have been seeing this for a while.

**Comment by wkentdag** [comment]
Same error on payload 2.23.1, db-postgres 0.8.5. I can trigger it for any document that has a nested array field, regardless of whether it was duplicated or not. In my case it also seems related to draft/publish, I observed this strange behavior:

1.  Save a draft change to any document that has a nested array (succeeds)
2. Publish that change (fails w/ OP's error)
3. Delete the nested array items, save draft change (succeeds)
4. Publish that change (succeeds.... and the deleted array items have been magically restored 🤯 )
5. Repeat and see the same results, even if you delete the entire parent field in step 3 rather than just the nested array

This is causing issues in prod for me so hoping to follow up with more debugging and a repro later tonight 👍

**Comment by PatrikKozak** [comment]
Hey @SimYunSup @siobahnschuck @wkentdag - we just merged the fix for this on [v3](https://github.com/payloadcms/payload/pull/8790) and have a PR for it on v2 [here](https://github.com/payloadcms/payload/pull/8814).

Thanks for your patience and we'll get all of this merged and released asap!
