### ISSUE TITLE
TypeError: Cannot assign to read only property 'visibleEntities' of object '#<Object>'

### ISSUE THREAD

**Issue by muhammaddadu** [payloadcms/payload#6612]
### Payload Version

3.0.0-beta.40

### Node Version

node v18.20.2

### Next.js Version

15.0.0-rc.0

### Describe the Bug

The error when I try to access /admin after authenticating successfully
```
 ⨯ Internal error: TypeError: Cannot assign to read only property 'visibleEntities' of object '#<Object>'
    at /.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:133681
    at ee (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:130764)
    at ec (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:132250)
    at Q (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:130553)
    at ai (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55393)
    at au (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:59313)
    at as (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:58394)
    at ai (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55444)
    at ai (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55416)
    at /.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64092
    at /.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64821
    at ag (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64829)
    at Timeout._onTimeout (/.../app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6918)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
digest: "3547026990"
 GET /admin 500 in 41ms
 GET /api/users/me 200 in 62ms
 GET /admin 200 in 143ms
```

My package.json
```
  "engines": {
    "node": "^18.20.2 || >=20.6.0"
  },
  "dependencies": {
    "@payloadcms/db-mongodb": "^3.0.0-beta.40",
    "@payloadcms/next": "^3.0.0-beta.40",
    "@payloadcms/richtext-lexical": "^3.0.0-beta.40",
    "cross-env": "^7.0.3",
    "graphql": "^16.8.1",
    "next": "15.0.0-rc.0",
    "payload": "^3.0.0-beta.40",
    "react": "19.0.0-rc-f994737d14-20240522",
    "react-dom": "19.0.0-rc-f994737d14-20240522",
    "sharp": "0.32.6",
    "babel-plugin-react-compiler": "^0.0.0-experimental-592953e-20240517"
  },
  "devDependencies": {
    "@types/node": "^20.12.12",
    "@types/react": "npm:types-react@19.0.0-beta.2",
    "@types/react-dom": "npm:types-react-dom@19.0.0-beta.2",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.2.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.4.5"
  },
  "resolutions": {
    "react": "19.0.0-rc-f994737d14-20240522",
    "react-dom": "19.0.0-rc-f994737d14-20240522",
    "react-toastify": "10.0.4",
    "@types/react": "npm:types-react@19.0.0-beta.2",
    "@types/react-dom": "npm:types-react-dom@19.0.0-beta.2"
  }
  ```

### Reproduction Steps

- Created NextX App
- Installed Payload through steps in documentation
- Start App
- Login to PayloadCMS
- Page does not load

### Adapters and Plugins

db-mongodb

**Comment by muhammaddadu** [comment]
Issue only occurs if using `yarn`. Doesn't occur when using `npm`.

**Comment by szpolny** [comment]
I'm using bun and im getting same error.

"payload": 3.0.0-beta.40
"next": 15.0.0-rc.0

bun: 1.1.10
node: v22.2.0
