### ISSUE TITLE
Build fails when using Payload and Postgres in a Next.js custom server

### ISSUE THREAD

**Issue by riley-pearce-airteam** [payloadcms/payload#6716]
### Describe the Bug

Build fails intermittently when using a variation of the [custom server approach](https://github.com/payloadcms/payload/tree/main/examples/custom-server) for Payload v2. As far as I can tell it's due to Payload not being available intermittently when Next.js needs it.

It looks like this has been flagged previously but nothing concrete has been found to resolve it.

```
[11:42:27] INFO (payload): Starting Payload...
[11:42:28] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[11:42:28] INFO (payload): Next.js is now building...
   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/5)  [=   ][11:42:34] INFO (payload): Starting Payload...
error: constraint "_pages_v_rels_users_fk" of relation "_pages_v_rels" does not exist
    at /Users/company/Projects/my-project/my-project-web/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/Users/company/Projects/my-project/my-project-web/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/Users/company/Projects/my-project/my-project-web/node_modules/drizzle-kit/payload.js:36648:9)
    at async Object.connect (/Users/company/Projects/my-project/my-project-web/node_modules/@payloadcms/db-postgres/dist/connect.js:112:5)
    at async BasePayload.init (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/payload.js:221:13)
    at async getPayload (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/payload.js:265:26)
    at async initHTTP (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/initHTTP.js:39:21)
    at async Payload.init (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/index.js:27:25) {
  length: 148,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '11546',
  routine: 'ATExecDropConstraint'
}
error: constraint "_pages_v_rels_users_fk" of relation "_pages_v_rels" does not exist
    at /Users/company/Projects/my-project/my-project-web/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/Users/company/Projects/my-project/my-project-web/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/Users/company/Projects/my-project/my-project-web/node_modules/drizzle-kit/payload.js:36648:9)
    at async Object.connect (/Users/company/Projects/my-project/my-project-web/node_modules/@payloadcms/db-postgres/dist/connect.js:112:5)
    at async BasePayload.init (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/payload.js:221:13)
    at async getPayload (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/payload.js:265:26)
    at async initHTTP (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/initHTTP.js:39:21)
    at async Payload.init (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/index.js:27:25) {
  length: 148,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '11546',
  routine: 'ATExecDropConstraint'
}

Error occurred prerendering page "/production-page". Read more: https://nextjs.org/docs/messages/prerender-error

error: constraint "_pages_v_rels_users_fk" of relation "_pages_v_rels" does not exist
    at /Users/company/Projects/my-project/my-project-web/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/Users/company/Projects/my-project/my-project-web/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/Users/company/Projects/my-project/my-project-web/node_modules/drizzle-kit/payload.js:36648:9)
    at async Object.connect (/Users/company/Projects/my-project/my-project-web/node_modules/@payloadcms/db-postgres/dist/connect.js:112:5)
    at async BasePayload.init (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/payload.js:221:13)
    at async getPayload (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/payload.js:265:26)
    at async initHTTP (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/initHTTP.js:39:21)
    at async Payload.init (/Users/company/Projects/my-project/my-project-web/node_modules/payload/dist/index.js:27:25)
 ✓ Generating static pages (5/5) 
unhandledRejection ExportError: Export encountered errors on following paths:
        /[slug]/page: /production-page
    at exportAppImpl (/Users/company/Projects/my-project/my-project-web/node_modules/next/dist/export/index.js:665:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/company/Projects/my-project/my-project-web/node_modules/next/dist/export/index.js:681:16
    at async Span.traceAsyncFn (/Users/company/Projects/my-project/my-project-web/node_modules/next/dist/trace/trace.js:151:20)
    at async /Users/company/Projects/my-project/my-project-web/node_modules/next/dist/build/index.js:1494:42
    at async Span.traceAsyncFn (/Users/company/Projects/my-project/my-project-web/node_modules/next/dist/trace/trace.js:151:20)
    at async /Users/company/Projects/my-project/my-project-web/node_modules/next/dist/build/index.js:1341:17
    at async Span.traceAsyncFn (/Users/company/Projects/my-project/my-project-web/node_modules/next/dist/trace/trace.js:151:20)
    at async build (/Users/company/Projects/my-project/my-project-web/node_modules/next/dist/build/index.js:373:9) {
  code: 'NEXT_EXPORT_ERROR'
}
error Command failed with exit code 1.
```

### To Reproduce

- Unfortunately it is not easily reproduced.
- Starting with a fresh DB seems to resolve the issue temporarily but after making some changes in dev the issue will re-appear.
- DB migrations do not seem to resolve the issue.
- I am only using the Payload Local API, not REST or GraphQL.
- I am using `generateStaticParams`.

### Payload Version

2.18.3

### Adapters and Plugins

db-postgres@^0.8.4, bundler-webpack@^1.0.6, next@14.1.4

**Comment by denolfe** [comment]
> error: constraint "_pages_v_rels_users_fk" of relation "_pages_v_rels" does not exist

This to me reads like a migration needs to be generated and run first.

@riley-pearce-airteam Have you run `payload migrate:create` ? Does it generate anything?

**Comment by sinan2000** [comment]
> For anyone else who runs into this in the future, I was able to resolve it by setting the below in `next.config.js`:
> 
> ```
> experimental: {
>     workerThreads: false,
>     cpus: 1
> }
> ```
> 
> For some reason payload wasn't working across next.js build threads in the custom server example. This change has the potential to slow down build times but I haven't noticed any drastic slow downs yet for my use case.
> 
> I'm going to leave this open and leave it up to @denolfe to decide whether this should be closed.

This helped me, thank you very much!

**Comment by denolfe** [comment]
Let's close for now. This should turn up if someone searches for this issue.
