### ISSUE TITLE
TypeError: Cannot assign to read only property 'visibleEntities' of object '#<Object>'

### ISSUE THREAD

**Issue by szpolny** [payloadcms/payload#6722]
### Payload Version

3.0.0-beta.40

### Node Version

v20.14.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When trying to enter admin panel i get this error. I have tried different package managers and different node versions, but i always get same error. However build on Vercel works.

### Reproduction Steps

```
⨯ Internal error: TypeError: Cannot assign to read only property 'visibleEntities' of object '#<Object>'
    at /Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:133681
    at ee (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:130764)
    at ec (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:132250)
    at Q (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:130553)
    at ai (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55393)
    at au (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:59313)
    at as (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:58394)
    at ai (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55444)
    at ai (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55416)
    at /Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64092
    at /Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64821
    at ag (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64829)
    at Timeout._onTimeout (/Users/szpolny/Repo/pobandzie/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6918)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
digest: "2557407766"
```

### Adapters and Plugins

db-postgres, storage-uploadthing, richtext-lexical

**Comment by AlessioGr** [comment]
You might have a conflicting older payload version installed somewhere. Try using pnpm, then run `pnpm why @payloadcms/next`
