### ISSUE TITLE
Can't update fields of an already uploaded media using the S3 adapter

### ISSUE THREAD

**Issue by fofoy** [payloadcms/payload#7037]
### Payload Version

3.0.0-beta.56

### Node Version

20.12.2

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Whenever I want to update a field (e.g. Alt field), I get a 500 error when I try to submit the form.

Here is the log from the console
![image](https://github.com/payloadcms/payload/assets/1737124/d7931332-59b4-4de4-9e59-8f89a3635475)

### Reproduction Steps

Install `Payload` v3.0.0-beta.56 with the default `Media` Collection
Install `@payloadcms/storage-s3` v3.0.0-beta.56 
Set up S3 storage (I tried both on minIO and AWS S3 and I get the same behavior)
Upload a first Media
Update the Alt field and submit the form

### Adapters and Plugins

@payloadcms/db-postgres v3.0.0-beta.56
@payloadcms/storage-s3 v3.0.0-beta.56

**Comment by fofoy** [comment]
Any news on this one ? Is there anything I can help you with @PatrikKozak ?

**Comment by PatrikKozak** [comment]
Hey @fofoy - we'll get right on this!

**Comment by PatrikKozak** [comment]
Hi @fofoy - I did some testing on my end and was not able to reproduce the above issue.

It may have something to do with your S3 storage setup - do you have a reverse proxy setup?

Is this purely local?

Just want to get some additional information before I can dig deeper into this - thank you!

**Comment by fofoy** [comment]
Hi @PatrikKozak I have the same issue in local (using a dockerized MinIO instance) and on my staging environment using an AWS S3 bucket so it doesn't seem to be a setup issue.

**Comment by PatrikKozak** [comment]
@fofoy Thanks for the info - hmm unfortunately there isn't enough here to fully understand what could be causing this issue.

A couple things though, could you try and log out some of the info in that function where the error is coming from (in your node_modules) - this may be able to give us some more information

Also, could you update your payload packages versions to latest (just in case) - I'd like to get to the bottom of this but just will need more info to continue

**Comment by fofoy** [comment]
@PatrikKozak Thanks, I had the time to update my project to latest beta version 91 and the problem remains, I'll dig further to see where it's going wrong and I'll let you know.

**Comment by fofoy** [comment]
Hi @PatrikKozak here is the result of logging the Promise `getExternalFile` on line 41 of `generateFileData.js` file: 
```
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 652801,
  [Symbol(trigger_async_id_symbol)]: 652790,
  [Symbol(kResourceStore)]: {
    url: {
      pathname: '/api/media/c26034b9-71ab-4e88-8ff1-2dfc5a980261',
      search: '?depth=0&fallback-locale=null'
    },
    headers: [Getter],
    cookies: [Getter],
    mutableCookies: [Getter],
    draftMode: [Getter],
    reactLoadableManifest: {},
    assetPrefix: '',
    afterContext: undefined,
    isHmrRefresh: undefined,
    serverComponentsHmrCache: undefined
  },
  [Symbol(kResourceStore)]: {
    isStaticGeneration: false,
    page: '/(payload)/api/[...slug]/route',
    fallbackRouteParams: null,
    route: '/api/[...slug]',
    incrementalCache: IncrementalCache {
      locks: Map(0) {},
      unlocks: Map(0) {},
      hasCustomCacheHandler: false,
      dev: true,
      disableForTestmode: false,
      minimalMode: false,
      requestHeaders: [Object],
      requestProtocol: 'https',
      allowedRevalidateHeaderKeys: undefined,
      prerenderManifest: [Object],
      revalidateTimings: [SharedRevalidateTimings],
      fetchCacheKeyPrefix: '',
      cacheHandler: [FileSystemCache]
    },
    isRevalidate: false,
    isPrerendering: undefined,
    fetchCache: undefined,
    isOnDemandRevalidate: undefined,
    isDraftMode: undefined,
    requestEndedState: undefined,
    revalidate: 0,
    tags: [
      '_N_T_/layout',
      '_N_T_/(payload)/layout',
      '_N_T_/(payload)/api/layout',
      '_N_T_/(payload)/api/[...slug]/layout',
      '_N_T_/(payload)/api/[...slug]/route',
      '_N_T_/api/media/c26034b9-71ab-4e88-8ff1-2dfc5a980261'
    ],
    nextFetchId: 2
  },
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: undefined,
  [Symbol(kResourceStore)]: { isAppRoute: true, isAction: false }
}
```

and here is the actual error when trying to fetch the file : 
```
TypeError: fetch failed
     at node:internal/deps/undici/undici:12618:11
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async getExternalFile (webpack-internal:///(rsc)/../node_modules/.pnpm/payload@3.0.0-beta.108_graphql@16.9.0_monaco-editor@0.38.0_react-dom@19.0.0-rc-fb9a90f
 a48-202_bgnc5eiwwsaz2mukappcno4s3m/node_modules/payload/dist/uploads/getExternalFile.js:18:21) {
   cause: Error: connect ECONNREFUSED 127.0.0.1:443
       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
     errno: -111,
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 443
   }
 }
  ⨯ unhandledRejection: TypeError: fetch failed
     at node:internal/deps/undici/undici:12618:11
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async getExternalFile (webpack-internal:///(rsc)/../node_modules/.pnpm/payload@3.0.0-beta.108_graphql@16.9.0_monaco-editor@0.38.0_react-dom@19.0.0-rc-fb9a90f
 a48-202_bgnc5eiwwsaz2mukappcno4s3m/node_modules/payload/dist/uploads/getExternalFile.js:18:21) {
   cause: Error: connect ECONNREFUSED 127.0.0.1:443
       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
     errno: -111,
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 443
   }
 }
  ⨯ unhandledRejection: TypeError: fetch failed
     at node:internal/deps/undici/undici:12618:11
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async getExternalFile (webpack-internal:///(rsc)/../node_modules/.pnpm/payload@3.0.0-beta.108_graphql@16.9.0_monaco-editor@0.38.0_react-dom@19.0.0-rc-fb9a90f
 a48-202_bgnc5eiwwsaz2mukappcno4s3m/node_modules/payload/dist/uploads/getExternalFile.js:18:21) {
   cause: Error: connect ECONNREFUSED 127.0.0.1:443
       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
     errno: -111,
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 443
   }
 }
```

So it seems like it's something to do with the network. I'm running everything in Docker with several containers for the postgres db, the S3 instance (minIO) and the payload admin but it also does the same on our dev cluster (kubernetes) with an AWS S3 instance connected to it.

**Comment by nickejoha** [comment]
Hi @PatrikKozak and @fofoy 

I'm having the same problem as well. I can't edit any fields of an already uploaded file, and I got the same error as described above. 

We also run our environments in kubernetes and we use Google cloud storage for storing files. I have however noticed that when I'm running payload locally (and still using google cloud storage for storing files) it works. When I'm running payload in docker I get the same error we got in our kubernetes environments.

@fofoy Have you found any temporary workaround for this problem?

**Comment by fofoy** [comment]
Hi @nickejoha, I didn't have the time to dig any further than this yet as I need to make progress on my current project but that's definitely something that needs to be sorted, I'll try to invest more time in a bit.

**Comment by denolfe** [comment]
I also attempted to recreate this issue, but I was unable to. I'm not sure there's much more we can do on our end to troubleshoot this.

If you have any more info or a way to consistently reproduce that would be helpful.

**Comment by fofoy** [comment]
Hi @denolfe, I updated to the latest version of beta v122 and the same problem remains, let me know if I can help you in any way to help you debug this.

**Comment by nickejoha** [comment]
I think we have found the issue here and we have implemented a workaround. 

In short, the problem in our case seems to be connected our firewall in Google cloud plattform and locally that we use a different external port in our docker build. 

The problem here seems to be is that when we edit a field of media file that has been uploaded already, payload tries to fetch the file but the fetch fails. The problem in our case was that when payload tries to fetch the file, it uses the external url which works fine when used from a frontend client or when running a docker config that doesn't alter the ports, but because the request is executed from the container itself the url is invalid. In our local docker config the external url is localhost:3077, but inside the container the app runs on port 3000. So when we access file from outside the container localhost:3077 is valid, but when trying to fetch the same file from inside the container the url is invalid because the application runs on port 3000. The problem in our Google cloud plattform was due the same fact that the external url isn't valid from inside the cluster.

So with that figured out we implemented a bit of a hack as a workaround. By temporarily changing the files url to a valid url (from the containers perspective) with a hook, and the error is gone and editing the file works :)
```
import { CollectionBeforeOperationHook, CollectionBeforeReadHook } from 'payload'

const fixMediaUrl = (req: any) => {
  if (req.data?.url) {
    const prefix = process.env.CMS_INTERNAL_URL || ''
    if (req.data.url.startsWith('/')) {
      req.data.url = prefix + req.data.url
    }
    if (req.data?.sizes) {
      for (const key in req.data.sizes) {
        if (req.data.sizes[key].url?.startsWith('/')) {
          req.data.sizes[key].url = prefix + req.data.sizes[key].url
        }
      }
    }
  }
}

export const fixMediaUrlOperation: CollectionBeforeOperationHook = async ({ req }) =>
  fixMediaUrl(req)

export const fixMediaUrlRead: CollectionBeforeReadHook = async ({ req }) => fixMediaUrl(req)
```

**Comment by eduhdev12** [comment]
I'm running in the same issue, also with MinIO. I will open a PR that fixes this.

**Comment by firatciftci** [comment]
I'm also experiencing the same issue; I'm using the S3 Adapter with a Cloudflare R2 bucket, and everything works fine when it comes to creating, reading, and deleting operations, but update does not work. Here is my error printout when I try to update the `"description"` field:
```
[01:56:38] ERROR: There was a problem while uploading the file. Blocked unsafe attempt to http://localhost:6002/api/media/file/SCR-20250523-jnsh.png
    err: {
      "type": "FileRetrievalError",
      "message": "There was a problem while uploading the file. Blocked unsafe attempt to http://localhost:6002/api/media/file/SCR-20250523-jnsh.png",
      "stack":
          FileRetrievalError: There was a problem while uploading the file. Blocked unsafe attempt to http://localhost:6002/api/media/file/SCR-20250523-jnsh.png
              at generateFileData (file:///Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/payload@3.43.0_graphql@16.11.0_typescript@5.8.3/node_modules/payload/dist/uploads/generateFileData.js:53:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
              at async updateByIDOperation (file:///Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/payload@3.43.0_graphql@16.11.0_typescript@5.8.3/node_modules/payload/dist/collections/operations/updateByID.js:80:61)
              at async updateByIDHandler (file:///Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/payload@3.43.0_graphql@16.11.0_typescript@5.8.3/node_modules/payload/dist/collections/endpoints/updateByID.js:16:17)
              at async handleEndpoints (file:///Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/payload@3.43.0_graphql@16.11.0_typescript@5.8.3/node_modules/payload/dist/utilities/handleEndpoints.js:169:26)
              at async /Users/firatciftci/Developer/misc/artsumer/.next/server/chunks/node_modules__pnpm_94f68aa0._.js:29799:26
              at async AppRouteRouteModule.do (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/compiled/next-server/app-route-turbo.runtime.dev.js:26:34112)
              at async AppRouteRouteModule.handle (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/compiled/next-server/app-route-turbo.runtime.dev.js:26:41338)
              at async doRender (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/base-server.js:1518:42)
              at async DevServer.renderToResponseWithComponentsImpl (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/base-server.js:1920:28)
              at async DevServer.renderPageComponent (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/base-server.js:2408:24)
              at async DevServer.renderToResponseImpl (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/base-server.js:2445:32)
              at async DevServer.pipeImpl (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/base-server.js:1008:25)
              at async NextNodeServer.handleCatchallRenderRequest (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/next-server.js:305:17)
              at async DevServer.handleRequestImpl (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/base-server.js:900:17)
              at async /Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/dev/next-dev-server.js:371:20
              at async Span.traceAsyncFn (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/trace/trace.js:157:20)
              at async DevServer.handleRequest (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/dev/next-dev-server.js:368:24)
              at async invokeRender (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/lib/router-server.js:237:21)
              at async handleRequest (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/lib/router-server.js:428:24)
              at async requestHandlerImpl (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/lib/router-server.js:452:13)
              at async Server.requestListener (/Users/firatciftci/Developer/misc/artsumer/node_modules/.pnpm/next@15.3.3_@babel+core@7.27.4_babel-plugin-react-compiler@19.1.0-rc.2_react-dom@19.1.0_b5160444ab580599d92acf97540046d0/node_modules/next/dist/server/lib/start-server.js:158:13)
      "data": null,
      "isOperational": true,
      "isPublic": false,
      "status": 500,
      "name": "FileRetrievalError"
    }
 PATCH /api/media/1977?depth=0&fallback-locale=null 500 in 406ms
```

Important to note that, if I turn off the `upload.filesRequiredOnCreate` flag, create a new Media item with no image, and then edit its `"description"` field, I have no issues updating it. This only occurs when there is an image attached.

I have also checked the `Content-Length` and the `"origin"` header of the update request, and those seem to be all fine.

**Comment by tsemachh** [comment]
Happens also to me on local storage and also on GCS storage so it's not related to S3
Look at [https://github.com/payloadcms/payload/pull/12622#issuecomment-2987818304](https://github.com/payloadcms/payload/pull/12622#issuecomment-2987818304)
Same error occurs in other places

**Comment by thopedam** [comment]
I think this is a new error (@firatciftci and @tsemachh and also me 😀 are having) It seems to have started with version **0.43.0**. 
Downgrading to 0.42.0 fixes it for me. I also tested **0.39.0-0.42.0** no issues there as well.

EDIT: a new issue has been added: https://github.com/payloadcms/payload/issues/12876

**Comment by kendelljoseph** [comment]
@firatciftci #12927 should fix the problem.

**Comment by greenlover1991** [comment]
Just want to share based on our setup in [above comment](https://github.com/payloadcms/payload/issues/7037#issuecomment-2673251002) after upgrading to **v3.46.0**:

**Production setup:**
1. Behind nginx
2. Self-host on Openshift cluster
3. Payloadcms container is served on port 3000

The `pasteURL` that **didn't** worked:
```javascript
allowList: [
    {
      hostname: "my-internal-openshift-pod-svc-name.my-namespace", # Openshift service name
      port: "80", # node port
      protocol: 'http',
    },
  ]
```

The `pasteURL` that **finally worked**:
```javascript
allowList: [
    {
      hostname: "localhost",
      port: "3000",
      protocol: 'http',
    },
  ]
```

------

Openshift service name as hostname will **not** work because `safeFetch()` will attempt to do a DNS lookup and **disallow** private IP address. Which I think is a bug on Payloadcms side cc @kendelljoseph @DanRibbens 

https://github.com/payloadcms/payload/blob/v3.46.0/packages/payload/src/uploads/safeFetch.ts#L20

```typescript
const isSafeIp = (ip: string) => {
  try {
    ...
    if (range !== 'unicast') {
      return false // Private IP Range
    }
   ...
}
```

Related to #13146

**Comment by JessRynkar** [comment]
This issue hasn’t had activity in a while and relates to several releases ago, so we’re going to close it for now. If it’s still occurring on the latest version, please open a new issue with updated reproduction steps and environment details so we can investigate.
