### ISSUE TITLE
Next dev & mongo adapter

### ISSUE THREAD

**Issue by ScapersClub** [payloadcms/payload#7255]
### Payload Version

58-67

### Node Version

latest

### Next.js Version

recommend

### Describe the Bug

When using MongoDB in development mode on Next.js, it is impossible to use the admin panel, meaning you can't edit or create collections when a collection has many fields and locales, as if it were a real site. To edit collections, I have to first build and run the application; then it works fine. However, in development mode, I constantly get an error that crashes the entire application:
```
MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_ABORTED] to [TRANSACTION_ABORTED]
    at Transaction.transition (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6172:15)
    at commandHandler (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6639:33)
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6698:9
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:1850:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(errorLabels)]: Set(0) {}
}
MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_ABORTED] to [TRANSACTION_COMMITTED]
    at Transaction.transition (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6172:15)
    at commandHandler (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6648:29)
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6698:9
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:1850:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(errorLabels)]: Set(0) {}
}
 ⨯ unhandledRejection: MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_ABORTED] to [TRANSACTION_ABORTED]
    at Transaction.transition (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6172:15)
    at commandHandler (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6639:33)
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6698:9
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:1850:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(errorLabels)]: Set(0) {}
}
 ⨯ unhandledRejection: MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_ABORTED] to [TRANSACTION_COMMITTED]
    at Transaction.transition (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6172:15)
    at commandHandler (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6648:29)
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6698:9
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:1850:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(errorLabels)]: Set(0) {}
}
 ⨯ unhandledRejection: MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_ABORTED] to [TRANSACTION_COMMITTED]
    at Transaction.transition (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6172:15)
    at commandHandler (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6648:29)
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6698:9
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:1850:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(errorLabels)]: Set(0) {}
}
 ⨯ unhandledRejection: MongoRuntimeError: Attempted illegal state transition from [TRANSACTION_ABORTED] to [TRANSACTION_ABORTED]
    at Transaction.transition (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6172:15)
    at commandHandler (/Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6639:33)
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:6698:9
    at /Users/admin/Developer/project/.next/server/chunks/ssr/286e7_mongodb_f31753._.js:1850:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(errorLabels)]: Set(0) {}
}
```

### Reproduction Steps

Try creating a collection with many different fields, then edit it, then add more fields, edit the old fields, and then try editing the content in the admin panel.

### Adapters and Plugins

db-mongodb

**Comment by tsemachh** [comment]
Do you have filterOptions in your code ?
Look at [https://github.com/payloadcms/payload/issues/7196](https://github.com/payloadcms/payload/issues/7196)
There's similar issue there , for now we disabled filterOptions until this is resolved.

**Comment by paulpopus** [comment]
Hey @ScapersClub is the above issue related? If not please provide reproduction, otherwise I will close this issue for now and we'll track progress in the other one
