### ISSUE TITLE
Attempting to query text field with hasMany within an array fails

### ISSUE THREAD

**Issue by max-degterev** [payloadcms/payload#7671]
### Describe the Bug

I have a collection with this field config:

```
const fields: Field[] = [
  {
    name: 'texts',
    dbName: 'e_texts',
    type: 'array',
    defaultValue: [],
    admin: {
      initCollapsed: true,
    },
    fields: [
      {
        name: 'value',
        type: 'text',
        required: true,
        index: true,
        hasMany: true,
      },
    ],
  },
];

export default fields;

```

attempting to query like this: ``` where: { 'texts.value': { contains: filter } };```

Fails with an error:

```/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/getTableColumnFromPath.ts:266
            eq(adapter.tables[tableName].id, adapter.tables[newTableName].parent),
                                                                          ^
TypeError: Cannot read properties of undefined (reading 'parent')
    at getTableColumnFromPath (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/getTableColumnFromPath.ts:266:75)
    at getTableColumnFromPath (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/getTableColumnFromPath.ts:320:16)
    at parseParams (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/parseParams.ts:85:43)
    at buildAndOrConditions (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/buildAndOrConditions.ts:38:39)
    at parseParams (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/parseParams.ts:55:61)
    at buildAndOrConditions (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/buildAndOrConditions.ts:38:39)
    at parseParams (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/parseParams.ts:55:61)
    at buildQuery (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/queries/buildQuery.ts:105:30)
    at find (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/find/findMany.ts:44:80)
    at Object.find (/Volumes/Data/Projects/bldry-db/node_modules/@payloadcms/db-postgres/src/find.ts:28:18)
```

Any idea how to fix? Have to manually store JSON in a text field for now. Using JSON field also fails  since it seems searching within jsonb not implemented correctly

### To Reproduce

Create a collection as described, attempt to query.

### Payload Version

2.25.0

**Comment by r1tsuu** [comment]
Hey @max-degterev, fixed in https://github.com/payloadcms/payload/pull/8003

**Comment by r1tsuu** [comment]
Ported to 2.0 as well https://github.com/payloadcms/payload/pull/8033
