### ISSUE TITLE
Error: Package subpath './api' is not defined by "exports" 

### ISSUE THREAD

**Issue by alsherif-khalaf** [payloadcms/payload#7770]
### Payload Version

3.0.0-beta.86

### Node Version

v20.16.0

### Next.js Version

15.0.0-canary.120

### Describe the Bug

Just after upgrading website template from 3.0.0-beta.84 to 3.0.0-beta.86

Error: Package subpath './api' is not defined by "exports" in /home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/node_modules/drizzle-kit/package.json

```bash
 ⨯ Internal error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './api' is not defined by "exports" in /home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/node_modules/drizzle-kit/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:592:36)
    at Module._findPath (node:internal/modules/cjs/loader:669:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at /home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/next@15.0.0-canary.120_babel-plugin-react-compiler@0.0.0-experimental-1f3db3d-20240818_react-_rqfkhogt5n2fvqlo4encehp2ke/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at mod.require (/home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/next@15.0.0-canary.120_babel-plugin-react-compiler@0.0.0-experimental-1f3db3d-20240818_react-_rqfkhogt5n2fvqlo4encehp2ke/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.requireDrizzleKit (../node_modules/.pnpm/@payloadcms+drizzle@3.0.0-beta.86_@libsql+client@0.5.6_@types+react@18.2.42_knex@3.1.0_pg@8.1_geplkdckm5wi5lvx6l6emukxxu/node_modules/@payloadcms/drizzle/dist/postgres/requireDrizzleKit.js:8:31)
    at pushDevSchema (../node_modules/.pnpm/@payloadcms+drizzle@3.0.0-beta.86_@libsql+client@0.5.6_@types+react@18.2.42_knex@3.1.0_pg@8.1_geplkdckm5wi5lvx6l6emukxxu/node_modules/@payloadcms/drizzle/dist/utilities/pushDevSchema.js:13:36)
    at Object.connect (../node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.86_@libsql+client@0.5.6_@types+react@18.2.42_knex@3.1.0_pg_ygrsu4ol6dqzwjkgwek4gfjxee/node_modules/@payloadcms/db-postgres/dist/connect.js:85:81)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BasePayload.init (../node_modules/.pnpm/payload@3.0.0-beta.86_graphql@16.9.0_typescript@5.5.4/node_modules/payload/dist/index.js:559:13)
digest: "3398702718"
 ⨯ Internal error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './api' is not defined by "exports" in /home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/node_modules/drizzle-kit/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:592:36)
    at Module._findPath (node:internal/modules/cjs/loader:669:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at /home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/next@15.0.0-canary.120_babel-plugin-react-compiler@0.0.0-experimental-1f3db3d-20240818_react-_rqfkhogt5n2fvqlo4encehp2ke/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at mod.require (/home/alsherif-khalaf/Dev/Fronted/node_modules/.pnpm/next@15.0.0-canary.120_babel-plugin-react-compiler@0.0.0-experimental-1f3db3d-20240818_react-_rqfkhogt5n2fvqlo4encehp2ke/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.requireDrizzleKit (../node_modules/.pnpm/@payloadcms+drizzle@3.0.0-beta.86_@libsql+client@0.5.6_@types+react@18.2.42_knex@3.1.0_pg@8.1_geplkdckm5wi5lvx6l6emukxxu/node_modules/@payloadcms/drizzle/dist/postgres/requireDrizzleKit.js:8:31)
    at pushDevSchema (../node_modules/.pnpm/@payloadcms+drizzle@3.0.0-beta.86_@libsql+client@0.5.6_@types+react@18.2.42_knex@3.1.0_pg@8.1_geplkdckm5wi5lvx6l6emukxxu/node_modules/@payloadcms/drizzle/dist/utilities/pushDevSchema.js:13:36)
    at Object.connect (../node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.86_@libsql+client@0.5.6_@types+react@18.2.42_knex@3.1.0_pg_ygrsu4ol6dqzwjkgwek4gfjxee/node_modules/@payloadcms/db-postgres/dist/connect.js:85:81)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BasePayload.init (../node_modules/.pnpm/payload@3.0.0-beta.86_graphql@16.9.0_typescript@5.5.4/node_modules/payload/dist/index.js:559:13)
digest: "3398702718"
 GET /admin 500 in 37718ms
```

### Reproduction Steps

Just  upgrading website template from 3.0.0-beta.84 to 3.0.0-beta.86

**Comment by paulpopus** [comment]
The website template has just been updated to a much newer version and I haven't noticed this error. Let me know if you still encounter it and with some reproduction steps please!
