### ISSUE TITLE
Issues with Media Uploads and Blog Post Visibility

### ISSUE THREAD

**Issue by MuhammadKaifNazeer** [payloadcms/payload#7850]
### Payload Version

beta

### Node Version

"node": "^18.20.2 || >=20.9.0"

### Next.js Version

15.0.0-canary.104

### Describe the Bug

I'm encountering two issues with my Payload CMS setup (beta version):

**1. Media Uploads:** Media uploads fail with a 500 Internal Server Error in the deployed environment, though they work fine locally.

**2. Blog Post Visibility:** Blog posts created in the deployed environment are not showing on the website, even though they appear correctly in MongoDB Atlas. The database URI is correctly configured. (in total that's 5 posts but its only showing 4 posts and that four created when I'm in local environment and next post I created on the deployed environment, this post all saved in the MongoDB atlas but that's no showing on the website, and also when I change the title of the 4th blog post (fourth post to 4th post) it's still showing fourth post title not 4th post title)

![Screenshot (108)](https://github.com/user-attachments/assets/533d1de9-838a-4939-a3a0-f0d996b3803c)
![Screenshot (109)](https://github.com/user-attachments/assets/398a9a8c-cd38-4850-8913-fdfe23c4dcab)
![Screenshot (110)](https://github.com/user-attachments/assets/c9354fed-e81d-4828-ac50-6ec48fdfd32f)

Could you please assist with resolving these issues?

### Reproduction Steps

I don't know how this happened. It works perfectly fine locally, but when I deploy it on Vercel, this problem occurs.

**Comment by bmamouri** [comment]
@MuhammadKaifNazeer, can I please post [runtime logs](https://vercel.com/docs/observability/runtime-logs) of your vercel instance to investigate the cause of 500 Internal Server Error?

**Comment by TomoyaKuroda** [comment]
I'm getting the same error on Vercel.

Reproduction Steps
npx create-payload-app@beta --use-pnpm -t website
I chose postgres during the installation and set up database.
After deploying to Vercel, go to admin/collections/media/create and upload media


Doesn't Vercel support Upload first of all?

```
[20:05:56] [31mERROR[39m: [36mError: ENOENT: no such file or directory, mkdir '/vercel/path0/public/media'
at mkdirSync (node:fs:1372:26)
at G (/var/task/.next/server/chunks/4858.js:357:121518)
at T (/var/task/.next/server/chunks/4858.js:357:14875)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.tP [as create] (/var/task/.next/server/chunks/9969.js:12:88922)
at async /var/task/.next/server/chunks/9969.js:12:105111
at async /var/task/node_modules/.pnpm/next@15.0.0-canary.104_react-dom@19.0.0-rc-06d0b89e-20240801_react@19.0.0-rc-06d0b89e-2024080_ouccyy7kk6qcxyqbefi33gxaae/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:38858
at async eP.execute (/var/task/node_modules/.pnpm/next@15.0.0-canary.104_react-dom@19.0.0-rc-06d0b89e-20240801_react@19.0.0-rc-06d0b89e-2024080_ouccyy7kk6qcxyqbefi33gxaae/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:28966)
at async eP.handle (/var/task/node_modules/.pnpm/next@15.0.0-canary.104_react-dom@19.0.0-rc-06d0b89e-20240801_react@19.0.0-rc-06d0b89e-2024080_ouccyy7kk6qcxyqbefi33gxaae/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:40159)
at async ed (/var/task/node_modules/.pnpm/next@15.0.0-canary.104_react-dom@19.0.0-rc-06d0b89e-20240801_react@19.0.0-rc-06d0b89e-2024080_ouccyy7kk6qcxyqbefi33gxaae/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:24:26900)[39m
```

**Comment by MuhammadKaifNazeer** [comment]
> @MuhammadKaifNazeer, can you please post [runtime logs](https://vercel.com/docs/observability/runtime-logs) of your vercel instance to investigate the cause of 500 Internal Server Error?

here the logs

[20:10:34.172] Running build in Washington, D.C., USA (East) – iad1
[20:10:34.290] Cloning github.com/MuhammadKaifNazeer/payloadcms-website-v3 (Branch: main, Commit: 4f5dc2d)
[20:10:34.324] Skipping build cache, deployment was triggered without cache.
[20:10:34.882] Cloning completed: 592.333ms
[20:10:35.206] Running "vercel build"
[20:10:35.918] Vercel CLI 37.1.1
[20:10:36.299] Warning: Detected "engines": { "node": "^18.20.2 || >=20.9.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[20:10:36.309] Running "install" command: `npm install --legacy-peer-deps`...
[20:10:40.750] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[20:10:42.120] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[20:10:42.397] npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
[20:10:45.302] npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[20:10:45.341] npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[20:11:01.106] 
[20:11:01.106] added 976 packages, and audited 977 packages in 25s
[20:11:01.107] 
[20:11:01.107] 206 packages are looking for funding
[20:11:01.107]   run `npm fund` for details
[20:11:01.119] 
[20:11:01.119] 3 vulnerabilities (2 moderate, 1 high)
[20:11:01.119] 
[20:11:01.119] To address all issues, run:
[20:11:01.119]   npm audit fix --force
[20:11:01.119] 
[20:11:01.119] Run `npm audit` for details.
[20:11:01.157] Detected Next.js version: 15.0.0-canary.104
[20:11:01.165] Running "npm run build"
[20:11:02.616] 
[20:11:02.617] > payloadcms-website@1.0.0 build
[20:11:02.617] > cross-env NODE_OPTIONS=--no-deprecation next build
[20:11:02.617] 
[20:11:03.222] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[20:11:03.223] This information is used to shape Next.js' roadmap and prioritize features.
[20:11:03.223] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[20:11:03.223] https://nextjs.org/telemetry
[20:11:03.223] 
[20:11:03.288]   ▲ Next.js 15.0.0-canary.104
[20:11:03.289]   - Experiments (use with caution):
[20:11:03.289]     · turbo
[20:11:03.289] 
[20:11:03.375]    Creating an optimized production build ...
[20:12:11.637]  ✓ Compiled successfully
[20:12:11.675]    Linting and checking validity of types ...
[20:12:27.411]    Collecting page data ...
[20:12:37.949]    Generating static pages (0/9) ...
[20:12:38.019]    Generating static pages (2/9) 
[20:12:38.049]    Generating static pages (4/9) 
[20:12:38.086]    Generating static pages (6/9) 
[20:12:38.993]  ✓ Generating static pages (9/9)
[20:12:40.509]    Finalizing page optimization ...
[20:12:40.510]    Collecting build traces ...
[20:12:52.697] 
[20:12:52.701] Route (app)                              Size     First Load JS
[20:12:52.701] ┌ ○ /                                    156 B           184 kB
[20:12:52.701] ├ ○ /_not-found                          903 B          93.3 kB
[20:12:52.701] ├ ● /[slug]                              156 B           184 kB
[20:12:52.701] ├ ƒ /admin/[[...segments]]               829 B           544 kB
[20:12:52.702] ├ ƒ /api/[...slug]                       0 B                0 B
[20:12:52.702] ├ ƒ /api/graphql                         0 B                0 B
[20:12:52.702] ├ ƒ /api/graphql-playground              0 B                0 B
[20:12:52.702] ├ ƒ /next/exit-preview                   0 B                0 B
[20:12:52.702] ├ ƒ /next/preview                        0 B                0 B
[20:12:52.702] ├ ○ /posts                               147 B           118 kB
[20:12:52.702] ├ ● /posts/[slug]                        2.51 kB         142 kB
[20:12:52.702] └ ○ /posts/page/[pageNumber]             147 B           118 kB
[20:12:52.702] + First Load JS shared by all            92.4 kB
[20:12:52.702]   ├ chunks/3182-e142ff1570615944.js      37.3 kB
[20:12:52.702]   ├ chunks/4bd1b696-2f2adf227181cab8.js  52 kB
[20:12:52.702]   └ other shared chunks (total)          3.1 kB
[20:12:52.702] 
[20:12:52.702] 
[20:12:52.702] ○  (Static)   prerendered as static content
[20:12:52.702] ●  (SSG)      prerendered as static HTML (uses getStaticProps)
[20:12:52.702] ƒ  (Dynamic)  server-rendered on demand
[20:12:52.702] 
[20:12:52.859] Traced Next.js server files in: 37.761ms
[20:12:53.831] Created all serverless functions in: 970.514ms
[20:12:53.845] Collected static files (public/, static/, .next/static): 8.949ms
[20:12:53.906] Build Completed in /vercel/output [2m]
[20:12:54.162] Deploying outputs...
[20:13:09.338] 
[20:13:09.608] Deployment completed
[20:13:21.419] Uploading build cache [171.87 MB]...
[20:13:24.189] Build cache uploaded: 2.769s

**Comment by bmamouri** [comment]
Thanks @MuhammadKaifNazeer for posting.

That's the build long, not the [runtime logs](https://vercel.com/docs/observability/runtime-logs). The reason for 500 Internal server errors can be found in the runtime logs.
