### ISSUE TITLE
Missing dependancies error when run node dist/server.js in production

### ISSUE THREAD

**Issue by EmanueleGuidotti** [payloadcms/payload#8233]
### Describe the Bug

After making a production build and uploaded all the `dist` `build` and `.env` on remote I try to launch the `node dist/server.js` command in order to run the node server but I got this error:
```
staging.arkage.it_uf77x2cbf9@host613:~/arkage-website.staging.arkage.it$ node dist/server.js
node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/dist/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/dist/server.js:42:32)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/dist/server.js'
  ]
}

Node.js v21.7.3
```

How I have to proceed? Anyone as facing the same issue?

### To Reproduce

Copy the website template: `npx create-payload-app@latest my-project -t website`
Run `yarn install`
Run `yarn build`
Upload the `dist`, `build` and `.env` on remote
Connect to remote with ssh
Launch the `node dist/server.js` command on remote

### Payload Version

"payload": "^2.0.0"

### Adapters and Plugins

db-mongodb

**Comment by denolfe** [comment]
If you are building the application, _then_ moving the application files, you will need to also move the `node_modules` folder which contains all of your dependencies. This error indicates you are missing that directory.

**Comment by EmanueleGuidotti** [comment]
I moved the `node_modules` folder in the root directory. Now I get this other error:

```
uncaughtException Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/sharp/lib/sharp.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/sharp/lib/constructor.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/sharp/lib/index.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/uploads/generateFileData.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/collections/operations/create.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/collections/requestHandlers/create.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/collections/buildEndpoints.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/collections/initHTTP.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/initHTTP.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/payload/dist/index.js
- /var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/dist/server.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at mod.require (/var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/var/www/vhosts/staging.arkage.it/arkage-website.staging.arkage.it/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    ```
