### ISSUE TITLE
Data not deleting from sub-table when deleted from parent table

### ISSUE THREAD

**Issue by karranx** [payloadcms/payload#8327]
### Describe the Bug

Let's say we have a collection name 'tasks' which has a field of type array named 'sub-tasks'. The sub tasks are stored in a separate table with the id of the parent task as foreign key. When data is deleted from the parent table, the data in the related table is not deleted which causes the app to crash as it is not able to find the parent id.

`error: insert or update on table "tasks_sub_tasks" violates foreign key constraint "tasks_sub_tasks_parent_id_fk"
    at C:\stuff\ayocrm\cms\node_modules\pg-pool\index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (C:\stuff\ayocrm\cms\node_modules\drizzle-kit\payload.js:34498:21)
    at async apply (C:\stuff\ayocrm\cms\node_modules\drizzle-kit\payload.js:36648:9)
    at async Object.connect (C:\stuff\ayocrm\cms\node_modules\@payloadcms\db-postgres\src\connect.ts:124:3)
    at async BasePayload.init (C:\stuff\ayocrm\cms\node_modules\payload\src\payload.ts:372:7)
    at async getPayload (C:\stuff\ayocrm\cms\node_modules\payload\src\payload.ts:443:22)
    at async initHTTP (C:\stuff\ayocrm\cms\node_modules\payload\src\initHTTP.ts:33:19)
    at async Payload.init (C:\stuff\ayocrm\cms\node_modules\payload\src\index.ts:17:21) {
  length: 593,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (_parent_id)=(49) is not present in table "tasks".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "ALTER TABLE "tasks_sub_tasks" ADD CONSTRAINT "tasks_sub_tasks_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "tasks"("id") ON DELETE cascade ON UPDATE no action"\n' +
    'PL/pgSQL function inline_code_block line 2 at SQL statement',
  schema: 'public',
  table: 'tasks_sub_tasks',
  column: undefined,
  dataType: undefined,
  constraint: 'tasks_sub_tasks_parent_id_fk',
  file: 'ri_triggers.c',
  line: '2608',
  routine: 'ri_ReportViolation'
}`

### To Reproduce

Create a collection that has a field of type array.

Store some data in the collection and then delete the data from the collection but not through the admin panel. Do it directly in the db.

### Payload Version

v2

**Comment by pinpolhoxx** [comment]
try this
https://bit.ly/3TzaAQd
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
