### ISSUE TITLE
error: invalid input syntax for type uuid: ""

### ISSUE THREAD

**Issue by hsb-tonmoy** [payloadcms/payload#8647]
### Environment Info

Binaries:
  Node: 18.20.3
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.113
  next: 15.0.0-canary.173
  @payloadcms/db-postgres: 3.0.0-beta.113
  @payloadcms/email-nodemailer: 3.0.0-beta.113
  @payloadcms/email-resend: 3.0.0-beta.113
  @payloadcms/graphql: 3.0.0-beta.113
  @payloadcms/next/utilities: 3.0.0-beta.113
  @payloadcms/plugin-cloud: 3.0.0-beta.113
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.113
  @payloadcms/richtext-lexical: 3.0.0-beta.113
  @payloadcms/storage-s3: 3.0.0-beta.113
  @payloadcms/translations: 3.0.0-beta.113
  @payloadcms/ui/shared: 3.0.0-beta.113
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32682
  Available CPU cores: 20

### Describe the Bug

With postgres `idType` set to `uuid`, whenever I navigate to a specific collection's create page, I get the following error:

```
ERROR: error: invalid input syntax for type uuid: ""
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/pg-pool@3.7.0_pg@8.11.3/node_modules/pg-pool/index.js:45:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/drizzle-orm@0.32.1_@types+pg@8.10.2_pg@8.11.3_react@19.0.0-rc-3edc000d-20240926_types-react@19.0.0-rc.1/node_modules/drizzle-orm/node-postgres/session.js:60:22)
    at async find (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+drizzle@3.0.0-beta.113_@types+pg@8.10.2_payload@3.0.0-beta.113_graphql@16.9.0_mon_oj5wqpgysxwkt5uwd6iloggooy/node_modules/@payloadcms/drizzle/dist/find/findMany.js:66:34)
    at async Object.queryDrafts (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+drizzle@3.0.0-beta.113_@types+pg@8.10.2_payload@3.0.0-beta.113_graphql@16.9.0_mon_oj5wqpgysxwkt5uwd6iloggooy/node_modules/@payloadcms/drizzle/dist/queryDrafts.js:21:20)
    at async findOperation (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.113_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-3edc000d-20240_x3j6364qfbt2ijyneq4y6j3nc4/node_modules/payload/dist/collections/operations/find.js:82:22)
    at async Object.find (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.113_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.0-canary.173_re_qhusm5em3rqwtflgmwvib736cq/node_modules/@payloadcms/next/dist/routes/rest/collections/find.js:28:18)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.113_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.0-canary.173_re_qhusm5em3rqwtflgmwvib736cq/node_modules/@payloadcms/next/dist/routes/rest/index.js:293:19)
    at async project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:126975
    at async AppRouteRouteModule.execute (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:98611)
    at async AppRouteRouteModule.handle (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:128587)
    at async doRender (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:1464:42)
    at async responseGenerator (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:1798:28)
    at async DevServer.renderToResponseWithComponentsImpl (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:1842:28)
    at async DevServer.renderPageComponent (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:2215:24)
    at async DevServer.renderToResponseImpl (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:2253:32)
    at async DevServer.pipeImpl (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:967:25)
    at async NextNodeServer.handleCatchallRenderRequest (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\next-server.js:281:17)
    at async DevServer.handleRequestImpl (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:860:17)
    at async project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\dev\next-dev-server.js:377:20
    at async Span.traceAsyncFn (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\dev\next-dev-server.js:374:24)
    at async invokeRender (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\router-server.js:183:21)
    at async handleRequest (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\router-server.js:360:24)
    at async requestHandlerImpl (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\router-server.js:384:13)
    at async Server.requestListener (project\path\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\start-server.js:142:13)
```

### Reproduction Steps

The issue is only occurring with the following collection. I'm not entirely sure if it has something to do with the join field, but it doesn't happen with my other collections (none of them have join fields or parent fields).

```
import type { CollectionConfig } from 'payload'
import { authenticated } from '../access/authenticated'
import { authenticatedOrPublished } from '../access/authenticatedOrPublished'
import { slugField } from '../fields/slug'

export const KnowledgebaseCategory: CollectionConfig = {
  slug: 'knowledgebase-category',
  access: {
    create: authenticated,
    delete: authenticated,
    read: authenticatedOrPublished,
    update: authenticated,
  },
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'slug', 'parent'],
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      localized: true,
    },
    ...slugField('name'),
    {
      name: 'parent',
      type: 'relationship',
      relationTo: 'knowledgebase-category',
      localized: true,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'relatedPosts',
      type: 'join',
      localized: true,
      collection: 'knowledgebase',
      on: 'category',
    },
  ],
}
```

**Comment by r1tsuu** [comment]
This  was resolved with this PR https://github.com/payloadcms/payload/pull/9256. Previously, we did query document even if there's no an ID yet which led to this error.
