### ISSUE TITLE
exception on graphql query using "{ hidden: { exists: false }"

### ISSUE THREAD

**Issue by megetron3** [payloadcms/payload#8722]
### Environment Info

node 20

### Describe the Bug

the following graphql query  gives exception

```
query getMenu {
  menu: Collections(
    where: {

OR: [{ hidden: { equals: false } }, { hidden: { exists: false } }]
    }
  ) {
    items: docs {
      title: name
      url: id
    }
  }
}

```
removing the `{ hidden: { exists: false } ` solves the problem.

exception:
```
[00:36:21] ERROR: CastError: Cast to Boolean failed for value "" (type string) at path "hidden" for model "collections"
    at model.Query.exec (webpack-internal:///(rsc)/../node_modules/.pnpm/mongoose@6.12.3_@aws-sdk+client-sso-oidc@3.654.0_@aws-sdk+client-sts@3.654.0_/node_modules/mongoose/lib/query.js:4921:21)
    at Function.paginate (webpack-internal:///(rsc)/../node_modules/.pnpm/mongoose-paginate-v2@1.7.22/node_modules/mongoose-paginate-v2/dist/index.js:147:53)
    at Object.find (webpack-internal:///(rsc)/../node_modules/.pnpm/@payloadcms+db-mongodb@3.0.0-beta.108_@aws-sdk+client-sso-oidc@3.654.0_@aws-sdk+client-sts@3._4krrnnhb6edmzyz3mumxm2ulem/node_modules/@payloadcms/db-mongodb/dist/find.js:96:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async findOperation (webpack-internal:///(rsc)/../node_modules/.pnpm/payload@3.0.0-beta.108_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-06d0b89e-20240_bmx4ytkgqinwhimpknjpqbs6ui/node_modules/payload/dist/collections/operations/find.js:99:22)
    at async resolver (webpack-internal:///(rsc)/../node_modules/.pnpm/@payloadcms+graphql@3.0.0-beta.108_graphql@16.9.0_payload@3.0.0-beta.108_graphql@16.9.0_monac_jpjasj6cvxhrtsaejrgaz6wcqe/node_modules/@payloadcms/graphql/dist/resolvers/collections/find.js:38:25)
    at async Promise.all (index 0)
    at async handler (webpack-internal:///(rsc)/../node_modules/.pnpm/graphql-http@1.22.1_graphql@16.9.0/node_modules/graphql-http/lib/handler.mjs:326:22)
    at async handleRequest (webpack-internal:///(rsc)/../node_modules/.pnpm/graphql-http@1.22.1_graphql@16.9.0/node_modules/graphql-http/lib/use/fetch.mjs:102:34)
    at async eval (webpack-internal:///(rsc)/../node_modules/.pnpm/@payloadcms+next@3.0.0-beta.108_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.0-canary.113_@b_6lh4iz6qb4klhahu2inz3dseiy/node_modules/@payloadcms/next/dist/routes/graphql/handler.js:100:23)
    at async /Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:99392
    at async AppRouteRouteModule.execute (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:82277)
    at async AppRouteRouteModule.handle (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:101160)
    at async doRender (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:1435:42)
    at async responseGenerator (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:1714:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:1721:28)
    at async DevServer.renderPageComponent (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:2058:24)
    at async DevServer.renderToResponseImpl (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:2096:32)
    at async DevServer.pipeImpl (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:946:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/next-server.js:277:17)
    at async DevServer.handleRequestImpl (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/base-server.js:839:17)
    at async /Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/dev/next-dev-server.js:378:20
    at async Span.traceAsyncFn (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/trace/trace.js:157:20)
    at async DevServer.handleRequest (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/dev/next-dev-server.js:375:24)
    at async invokeRender (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/lib/router-server.js:176:21)
    at async handleRequest (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/guy.eliyahu/repo/contra/node_modules/.pnpm/next@15.0.0-canary.113_@babel+core@7.24.7_babel-plugin-macros@3.1.0_babel-plugin-react-compil_k2p4my35m4gnuly2r6ygdacdha/node_modules/next/dist/server/lib/start-server.js:142:13)
```

### Reproduction Steps

the query below is an example where using the collection:
```

const collections: CollectionConfig = {
  slug: 'collections',

  fields: [
    {
      name: 'id',
      type: 'text',
      admin: {
        position: 'sidebar'
      },


    {
      name: 'hidden',
      type: 'checkbox',
      admin: {
        position: 'sidebar'
      }
    },

```

**Comment by JessRynkar** [comment]
Hi! Apologies for the long delay in getting a response here, are you still experiencing this on the latest version `v3.72.0`?

**Comment by JessRynkar** [comment]
This issue hasn’t had activity in a while and relates to several releases ago, so we’re going to close it for now. If it’s still occurring on the latest version, please open a new issue with updated reproduction steps and environment details so we can investigate.
