### ISSUE TITLE
Unauthorized Error about payload post requests

### ISSUE THREAD

**Issue by WhityGhost** [payloadcms/payload#8793]
On the payload admin panel, I have several errors.
![image](https://github.com/user-attachments/assets/6ed38b99-1f2e-4208-9802-ad0d32cd7e3a)

Here, I get 401 Unauthorized error about post requests to the payload's default endpoints.
As you can see, the token is included and it's valid which means there's req.user.
But on the backend, I got these error messages:

POST /api/payload-preferences/users-list 401
ERROR: UnauthorizedError: Unauthorized, you must be logged in to make this request.

POST /api/form-state 401
ERROR: There was an error building form state

One detailed of them is like following:
<details><summary>UnauthorizedError</summary>

```
[01:58:34] ERROR: UnauthorizedError: Unauthorized, you must be logged in to make this request.
    at update (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.116_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-3edc000d-20240_nqrfhptuu7w2jhpr2a52ldkhbe/node_modules/payload/dist/preferences/operations/update.js:10:15)
    at Object.updateHandler [as handler] (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.116_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-3edc000d-20240_nqrfhptuu7w2jhpr2a52ldkhbe/node_modules/payload/dist/preferences/requestHandlers/update.js:23:84)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleCustomEndpoints (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.116_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.0-canary.173_re_teoz65sbecf336jcq6qvejlca4/node_modules/@payloadcms/next/dist/routes/rest/index.js:198:19)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.116_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.0-canary.173_re_teoz65sbecf336jcq6qvejlca4/node_modules/@payloadcms/next/dist/routes/rest/index.js:478:38)
    at async D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:126975
    at async AppRouteRouteModule.execute (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:98611)
    at async AppRouteRouteModule.handle (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:128587)
    at async doRender (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:1464:42)
    at async responseGenerator (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:1798:28)
    at async DevServer.renderToResponseWithComponentsImpl (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:1842:28)
    at async DevServer.renderPageComponent (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:2215:24)
    at async DevServer.renderToResponseImpl (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:2253:32)
    at async DevServer.pipeImpl (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:967:25)
    at async NextNodeServer.handleCatchallRenderRequest (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\next-server.js:281:17)
    at async DevServer.handleRequestImpl (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\base-server.js:860:17)
    at async D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\dev\next-dev-server.js:377:20
    at async Span.traceAsyncFn (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\trace\trace.js:157:20)
    at async DevServer.handleRequest (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\dev\next-dev-server.js:374:24)
    at async invokeRender (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\router-server.js:183:21)
    at async handleRequest (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\router-server.js:360:24)
    at async requestHandlerImpl (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\router-server.js:384:13)
    at async Server.requestListener (D:\_Workspace\Development\Web\PayloadCMS\playcv\node_modules\.pnpm\next@15.0.0-canary.173_react-dom@19.0.0-rc-3edc000d-20240926_react@19.0.0-rc-3edc000d-2024092_x55oex4qbzquceggzfwiekr2om\node_modules\next\dist\server\lib\start-server.js:142:13)
```

</details>

I really need help, thank you.

Here's config of my users collection.
<details><summary>Users collection config:</summary>

```
import type { CollectionConfig } from 'payload'

import { readAccess } from './access/read'
import { deleteAccess } from './access/delete'
import { createIndividualAccount, createEntityAccount, joinAccount } from './endpoints/createUser'
import { isSuperAdmin } from '@/access/isSuperAdmin'
import { registerEntity } from './endpoints/registerEntity'
import { userSetting } from './endpoints/setting'

const Users: CollectionConfig = {
  slug: 'users',
  access: {
    create: () => true,
    read: () => true,
    delete: () => true,
    update: () => true,
  },
  admin: {
    useAsTitle: 'email',
  },
  auth: {
    tokenExpiration: 28800, // 8 hours
    cookies: {
      sameSite: 'Strict',
      secure: process.env.NODE_ENV === 'production',
    },
  },
  endpoints: [
    createIndividualAccount,
    createEntityAccount,
    joinAccount,
    registerEntity,
    userSetting,
  ],
  fields: [
    {
      name: 'roles',
      type: 'select',
      defaultValue: ['platform-user'],
      hasMany: true,
      options: ['platform-admin', 'platform-user'],
    },
    {
      type: 'text',
      name: 'name',
      required: true,
      index: true,
    },
    ...
    {
      name: 'entity',
      type: 'group',
      fields: [
        {
          name: 'tenant',
          type: 'relationship',
          index: true,
          relationTo: 'tenants',
          saveToJWT: true,
        },
        {
          name: 'role',
          type: 'select',
          defaultValue: 'staff',
          options: ['owner', 'staff'],
        },
      ],
      saveToJWT: true,
    },
  ],
}

export default Users
```

</details>

**Comment by azivkovi** [comment]
Would you kindly post what the problem was and how you resolved it?
