### ISSUE TITLE
Error when editing link in lexical

### ISSUE THREAD

**Issue by udany** [payloadcms/payload#8802]
### Describe the Bug

When clicking the edit button on a link in lexical the following error happens:
```
Uncaught TypeError: toggleModal is not a function
    at onClick (index.tsx:307:19)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12
```

The error points to the fact toggleModal is undefined [when called](https://github.com/payloadcms/payload/blob/e5d6cdae38323edfb10804745ae9b6a4184b0fcc/packages/richtext-lexical/src/field/features/Link/plugins/floatingLinkEditor/LinkEditor/index.tsx#L307).

Debugging in devtools I found out `useModal` is returning `{}`.

### To Reproduce

It's a relatively fresh project, started with `npx create-payload-app@latest` and added `@payloadcms/richtext-lexical`

Here's my payload config:
```typescript
export default buildConfig({
	admin: {
		user: Users.slug,
		bundler: webpackBundler(),
		meta: {
			favicon: '/public/favicon.png'
		},
		dateFormat: 'dd/MM/yyyy HH:mm:ss',
	},
	editor: lexicalEditor(),
	collections: [
		Users, Articles, Media
	],
	typescript: {
		outputFile: path.resolve(__dirname, 'payload-types.ts'),
	},
	graphQL: {
		schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
	},
	plugins: [payloadCloud(), addLastModified],
	db: postgresAdapter({
		pool: {
			connectionString: process.env.DATABASE_URI,

		},
	})
})
```

```json
  "dependencies": {
    "@payloadcms/bundler-vite": "^0.1.7",
    "@payloadcms/bundler-webpack": "^1.0.0",
    "@payloadcms/db-postgres": "^0.x",
    "@payloadcms/plugin-cloud": "^3.0.0",
    "@payloadcms/richtext-lexical": "^0.11.3",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "express": "^4.19.2",
    "payload": "^2.0.0"
  },
```

### Payload Version

2.0.0

### Adapters and Plugins

db-postgres, bundler-webpack,

**Comment by udany** [comment]
Updating to `^0.11.4` magically fixed it
