### ISSUE TITLE
Block Field: Labels required?

### ISSUE THREAD

**Issue by SuddenDev** [payloadcms/payload#90]
# Bug Report

So I tried out the block builder and did get an error when not using the labels key on the block itself.
The documentation does not state, that labels is required. After setting the labels it's okay.
I'm not using Typescript.

```
C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\schema\buildBlockType.js:8
const { slug, labels: { singular, }, } = block;
                            ^

TypeError: Cannot read property 'singular' of undefined
    at InitializeGraphQL.buildBlockType (C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\schema\buildBlockType.js:8:29)
    at C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\schema\buildObjectType.js:323:22
    at Array.map (<anonymous>)
    at blocks (C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\schema\buildObjectType.js:322:45)
    at C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\schema\buildObjectType.js:353:65
    at Array.reduce (<anonymous>)
    at fields (C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\schema\buildObjectType.js:346:30)
    at resolveThunk (C:\Development\portfolio-21\cms\node_modules\graphql\type\definition.js:480:40)
    at defineFieldMap (C:\Development\portfolio-21\cms\node_modules\graphql\type\definition.js:692:18)
    at GraphQLObjectType.getFields (C:\Development\portfolio-21\cms\node_modules\graphql\type\definition.js:633:27)
    at collectReferencedTypes (C:\Development\portfolio-21\cms\node_modules\graphql\type\schema.js:366:81)
    at collectReferencedTypes (C:\Development\portfolio-21\cms\node_modules\graphql\type\schema.js:368:9)
    at new GraphQLSchema (C:\Development\portfolio-21\cms\node_modules\graphql\type\schema.js:153:7)
    at new InitializeGraphQL (C:\Development\portfolio-21\cms\node_modules\payload\dist\graphql\index.js:99:23)
    at Payload.init (C:\Development\portfolio-21\cms\node_modules\payload\dist\index.js:177:36)
    at Object.<anonymous> (C:\Development\portfolio-21\cms\server.js:8:9)
[nodemon] app crashed - waiting for file changes before starting...
```

## Possible Solution

Update the documentation here [https://payloadcms.com/docs/fields/blocks#block-configs](https://payloadcms.com/docs/fields/blocks#block-configs), that labels is required

## Steps to Reproduce

```
// ./blocks/Quote.js

const QuoteBlock = {
  slug: "Quote", // required
  imageURL:
    "https://images.unsplash.com/photo-1612831198181-fe18661c31b6?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  imageAltText: "A nice thumbnail image to show what this block looks like",
  // labels: {  // <- this here
  //   singular: "Quote",
  //   plural: "Qoutes",  
  // },
  fields: [
    // required
    {
      name: "text",
      label: "Quote Text",
      type: "text",
      required: true,
      localized: true,
    },
    {
      name: "quotee",
      label: "Quotee",
      type: "text",
      localized: true,
    },
  ],
};

export default QuoteBlock;

```

## Detailed Description

OS: Windows 10
Payload Version: 0.4.3
Node: v14.15.1

**Comment by jmikrut** [comment]
Hey @SuddenDev — thanks for the report!

We are actually planning on having labels _**not**_ be required in this PR:

https://github.com/payloadcms/payload/pull/42

So that will close this issue. But good catch on the documentation. The above PR will be merged shortly so keep an eye out!

**Comment by denolfe** [comment]
Continued Discussion in #123
