### ISSUE TITLE
Unhandeled CastError in dataloader

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#923]
### Discussed in https://github.com/payloadcms/payload/discussions/911

<div type='discussions-op-text'>

<sup>Originally posted by **chladog** August 10, 2022</sup>
I encoutered following error already with #884 which since then was fixed.
Now the topic is regarding an error handling of this error. Sometimes I get this error, probably because of old invalid type data in my mongodb. Ofc invalid data shouldn't get stored in DB in the first place, but it happens - in this particular case it was a saved JSON in the relationship field where only ID should be stored.

The problem is that this error currently 1) kills the server process 2) therefore breaks whole GQL request so it's not possible to generate at least partial view with valid data and displaying an error to user.

```JS
const castError = new CastError();
                    ^
CastError: Cast to ObjectId failed for value "[object Object]" (type string) at path "_id" for model "media"
    at model.Query.exec (\node_modules\mongoose\lib\query.js:4777:21)
    at Function.paginate (\node_modules\mongoose-paginate-v2\dist\index.js:197:26)
    at find (\node_modules\payload\src\collections\operations\find.ts:146:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async \node_modules\payload\src\collections\dataloader.ts:66:20
    at async Promise.all (index 3)
    at async DataLoader._batchLoadFn (\node_modules\payload\src\collections\dataloader.ts:97:3) {
  messageFormat: undefined,
  stringValue: '"[object Object]"',
  kind: 'ObjectId',
  value: '[object Object]',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new BSONTypeError (\node_modules\bson\src\error.ts:16:5)
      at new ObjectId (\node_modules\bson\src\objectid.ts:88:15)
      at castObjectId (\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (\node_modules\mongoose\lib\schema\objectid.js:246:12)
      at ObjectId.SchemaType.applySetters (\node_modules\mongoose\lib\schematype.js:1189:12)
      at ObjectId.SchemaType._castForQuery (\node_modules\mongoose\lib\schematype.js:1623:15)
      at ObjectId.SchemaType.castForQuery (\node_modules\mongoose\lib\schematype.js:1613:15)
      at \node_modules\mongoose\lib\schematype.js:1555:18
      at Array.map (<anonymous>)
      at ObjectId.handle$in (\node_modules\mongoose\lib\schematype.js:1551:14),
  valueType: 'string'
```

Could this be handled the way that as much of valid data is returned back along with error message reporting the field of the problem so it doesn't break the app UX?</div>

**Comment by jmikrut** [comment]
**More context from discussion copy / pasted over:**

This also happens randomly on existing documents with relationship fields. I suspect that relationship field JSONs are being mixed with relationship fields IDs in dataloader.

I have following local API query in custom GQL resolver:
```JS
            const result = await payload.find({
              collection: "pages",
              where,
              user: context.req.user,
              locale: context.req.locale,
              fallbackLocale: context.req.fallbackLocale,
              depth: 1,
            });
```

Stored document looks like this:
![image](https://user-images.githubusercontent.com/15977485/184368411-49d13ed9-62a7-4fcd-a50a-cd15eefcb2a4.png)

Error I'm getting:
```Cast to ObjectId failed for value \"[object Object]\" (type string) at path \"_id\" for model \"users\"```

When I set depth: 0 I would expect id of a user, however I get user's JSON.
