### ISSUE TITLE
Cannot read properties of undefined (reading 'type') using relationTo

### ISSUE THREAD

**Issue by romanslonov** [payloadcms/payload#9608]
### Describe the Bug

Hello,

I have encountered problem using latest payload version when using relations. I reproduced the issue in linked repo below.

I just created two collections (Products, Allergens), and inside products I have a block which uses allergens like so:

```ts
  {
    name: 'allergens',
    type: 'relationship',
    hasMany: true,
    relationTo: 'allergens',
    label: 'Allergens',
  },
```

On the admin side everything works, api response looks correctly in API tab, but got the error on the client side page.

error:
```bash
 ⨯ node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/sanitizeQueryValue.js (92:1) @ sanitizeQueryValue
 ⨯ Internal error: TypeError: Cannot read properties of undefined (reading 'type')
    at sanitizeQueryValue (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/sanitizeQueryValue.js:98:22)
    at buildSearchParam (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/buildSearchParams.js:57:111)
    at parseParams (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/parseParams.js:45:126)
    at buildAndOrConditions (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/buildAndOrConditions.js:14:94)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseParams (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/parseParams.js:26:41)
    at async Function.buildQuery (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/buildQuery.js:27:28)
    at async Object.find (./node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/find.js:36:19)
    at async findOperation (./node_modules/.pnpm/payload@3.2.1_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-65a56d0e-20241020_react_jqjkbuafwviv24bimp3tgs6jda/node_modules/payload/dist/collections/operations/find.js:116:22)
    at async eval (./node_modules/.pnpm/payload@3.2.1_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-65a56d0e-20241020_react_jqjkbuafwviv24bimp3tgs6jda/node_modules/payload/dist/collections/dataloader.js:73:28)
    at async DataLoader.eval [as _batchLoadFn] (./node_modules/.pnpm/payload@3.2.1_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-65a56d0e-20241020_react_jqjkbuafwviv24bimp3tgs6jda/node_modules/payload/dist/collections/dataloader.js:69:9)
digest: "2411937340"
  90 |         'group',
  91 |         'tab'
> 92 |     ].includes(field.type) && path.includes('.')) {
     | ^
  93 |         const segments = path.split('.');
  94 |         segments.shift();
  95 |         const foundField = getFieldFromSegments({
 ⨯ node_modules/.pnpm/@payloadcms+db-mongodb@3.2.1_@aws-sdk+credential-providers@3.699.0_@aws-sdk+client-sso-oidc@3_wtupchxbjl7z2gv34xpzbfsaiu/node_modules/@payloadcms/db-mongodb/dist/queries/sanitizeQueryValue.js (92:1) @ sanitizeQueryValue
```

For some reason a field in https://github.com/payloadcms/payload/blob/c4327f22946f3a1c47dbd316a62f9b291546da40/packages/db-mongodb/src/queries/sanitizeQueryValue.ts#L89 is `undefined` in my case which is cause the error.

```bash
@PAYLOADCMS/MONGO { field: undefined, path: '_status', value: 'published' }
```

### Link to the code that reproduces this issue

https://github.com/romanslonov/payload-website-bug

### Reproduction Steps

1. Create allergen in it's collection
2. Create product, fill all fields and attach allergen in it's field (select)
3. Go to /products/[your_slug] and see error

### Which area(s) are affected? (Select all that apply)

area: core, db-mongodb

### Environment Info

```text
Binaries:
  Node: 20.11.0
  npm: 10.3.0
  Yarn: 1.22.22
  pnpm: 9.12.3
Relevant Packages:
  payload: 3.2.1
  next: 15.0.3
  @payloadcms/db-mongodb: 3.2.1
  @payloadcms/email-nodemailer: 3.2.1
  @payloadcms/graphql: 3.2.1
  @payloadcms/live-preview: 3.2.1
  @payloadcms/live-preview-react: 3.2.1
  @payloadcms/next/utilities: 3.2.1
  @payloadcms/payload-cloud: 3.2.1
  @payloadcms/plugin-form-builder: 3.2.1
  @payloadcms/plugin-nested-docs: 3.2.1
  @payloadcms/plugin-redirects: 3.2.1
  @payloadcms/plugin-search: 3.2.1
  @payloadcms/plugin-seo: 3.2.1
  @payloadcms/richtext-lexical: 3.2.1
  @payloadcms/translations: 3.2.1
  @payloadcms/ui/shared: 3.2.1
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
```

**Comment by r1tsuu** [comment]
Hey @romanslonov. It's not a bug with Payload, but with your queries

The Allergens collection https://github.com/romanslonov/payload-website-bug/blob/main/src/collections/Allergens.ts has `access: authenticatedOrPublished` which adds this `where` when you don't have `user`:
```js
{
  _status: {
    equals: 'published',
  },
}
```

The problem is that the `_status` field doesn't exist in your collection, because you don't have `versions.drafts` enabled. Either add `versions.drafts` or replace `access` with `authenticated`.

However, I think we can improve this part with querying by non-existing fields (and specifically with drafts and `_status`) with providing more detailed error messages
