### ISSUE TITLE
multi tenant error: invalid input syntax for type integer: "NaN"

### ISSUE THREAD

**Issue by judocode** [payloadcms/payload#9821]
### Describe the Bug

Hi all -

I am attempting to use the multi-tenant example from https://github.com/payloadcms/payload/tree/example/multi-tenant-single-domain/examples/multi-tenant and if I attempt to create a page as a tenant admin I get the following error:
```shell
[10:22:07] ERROR: invalid input syntax for type integer: "NaN"
    err: {
      "type": "DatabaseError",
      "message": "invalid input syntax for type integer: \"NaN\"",
      "stack":
          error: invalid input syntax for type integer: "NaN"
              at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/pg-pool@3.7.0_pg@8.11.3/node_modules/pg-pool/index.js:45:11)
              at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
              at async eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/drizzle-orm@0.36.1_@types+pg@8.10.2_@types+react@19.0.1_pg@8.11.3_react@19.0.0/node_modules/drizzle-orm/node-postgres/session.js:96:22)
              at async Object.countDistinct (webpack-internal:///(rsc)/../../node_modules/.pnpm/@payloadcms+drizzle@3.5.0_@types+pg@8.10.2_@types+react@19.0.1_payload@3.5.0_graphql@16.9.0_m_jt25wndeyl5pjinrhpigry42oe/node_modules/@payloadcms/drizzle/dist/postgres/countDistinct.js:20:25)
              at async find (webpack-internal:///(rsc)/../../node_modules/.pnpm/@payloadcms+drizzle@3.5.0_@types+pg@8.10.2_@types+react@19.0.1_payload@3.5.0_graphql@16.9.0_m_jt25wndeyl5pjinrhpigry42oe/node_modules/@payloadcms/drizzle/dist/find/findMany.js:109:21)
              at async findOperation (webpack-internal:///(rsc)/../../node_modules/.pnpm/payload@3.5.0_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_typescript@5.7.2/node_modules/payload/dist/collections/operations/find.js:116:22)
              at async ensureUniqueSlug (webpack-internal:///(rsc)/./src/collections/Pages/hooks/ensureUniqueSlug.ts:17:32)
              at async eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/payload@3.5.0_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_typescript@5.7.2/node_modules/payload/dist/fields/hooks/beforeValidate/promise.js:188:37)
              at async promise (webpack-internal:///(rsc)/../../node_modules/.pnpm/payload@3.5.0_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_typescript@5.7.2/node_modules/payload/dist/fields/hooks/beforeValidate/promise.js:186:13)
              at async Promise.all (index 1)
              at async traverseFields (webpack-internal:///(rsc)/../../node_modules/.pnpm/payload@3.5.0_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_typescript@5.7.2/node_modules/payload/dist/fields/hooks/beforeValidate/traverseFields.js:28:5)
              at async beforeValidate (webpack-internal:///(rsc)/../../node_modules/.pnpm/payload@3.5.0_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_typescript@5.7.2/node_modules/payload/dist/fields/hooks/beforeValidate/index.js:18:5)
              at async createOperation (webpack-internal:///(rsc)/../../node_modules/.pnpm/payload@3.5.0_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_typescript@5.7.2/node_modules/payload/dist/collections/operations/create.js:93:16)
              at async Object.create (webpack-internal:///(rsc)/../../node_modules/.pnpm/@payloadcms+next@3.5.0_@types+react@19.0.1_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.4_re_dtdvovxj3e2lmg33wqlo6wlpwi/node_modules/@payloadcms/next/dist/routes/rest/collections/create.js:27:15)
              at async eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@payloadcms+next@3.5.0_@types+react@19.0.1_graphql@16.9.0_monaco-editor@0.52.0_next@15.0.4_re_dtdvovxj3e2lmg33wqlo6wlpwi/node_modules/@payloadcms/next/dist/routes/rest/index.js:487:19)
              at async AppRouteRouteModule.do (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:33313)
              at async AppRouteRouteModule.handle (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40382)
              at async doRender (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:1455:42)
              at async responseGenerator (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:1814:28)
              at async DevServer.renderToResponseWithComponentsImpl (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:1824:28)
              at async DevServer.renderPageComponent (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:2240:24)
              at async DevServer.renderToResponseImpl (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:2278:32)
              at async DevServer.pipeImpl (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:960:25)
              at async NextNodeServer.handleCatchallRenderRequest (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/next-server.js:281:17)
              at async DevServer.handleRequestImpl (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/base-server.js:853:17)
              at async /Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/dev/next-dev-server.js:373:20
              at async Span.traceAsyncFn (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/trace/trace.js:153:20)
              at async DevServer.handleRequest (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/dev/next-dev-server.js:370:24)
              at async invokeRender (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/lib/router-server.js:183:21)
              at async handleRequest (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/lib/router-server.js:360:24)
              at async requestHandlerImpl (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/lib/router-server.js:384:13)
              at async Server.requestListener (/Users/judocode/Web/app/node_modules/.pnpm/next@15.0.4_react-dom@19.0.0_react@19.0.0__react@19.0.0_sass@1.77.4/node_modules/next/dist/server/lib/start-server.js:142:13)
      "length": 141,
      "name": "error",
      "severity": "ERROR",
      "code": "22P02",
      "where": "unnamed portal parameter $1 = '...'",
      "file": "numutils.c",
      "line": "323",
      "routine": "pg_strtoint32"
    }
```

This works if I am a super admin or a tenant-admin with multiple tenants because then the tenant is explicitly set in the frontend, but when I am a tenant-admin with 1 tenant and it's inferred in beforeValidation, it doesn't seem to pick it up. I did verify beforeValidation is correctly returning the tenant id, which is the same return value that I see in beforeValidation when this works as a super admin. Therefore, it seems like Payload doesn't care what you set in beforeValidation (or beforeChange) as it seems to not use what's output from them and is instead still looking at data from the original request.

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/tree/example/multi-tenant-single-domain/examples/multi-tenant

### Reproduction Steps

1. Use multi-tenant example (except instead of mongo, use postgres - not sure if same issue with mongo as I don't have it setup)
2. Create super-admin
3. Creat a tenant
4. Create tenant-admin
5. Login as tenant admin
6. Create a page
7. See error

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: 1.22.19
  pnpm: 9.14.2
Relevant Packages:
  payload: 3.5.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8

Nextjs: 15.0.4
```

**Comment by sBhavish** [comment]
I'm encountering the same issue at `/admin/create-first-user` endpoint.

**Comment by sbhavish87** [comment]
I've cloned the [main](https://github.com/payloadcms/payload/tree/main/examples/multi-tenant) branch, Configured to use the postgres database and did not seed the default users. 

I've configured to use the `idType` as `uuid`. And I'm getting the same error
```
type": "DatabaseError",
      "message": "invalid input syntax for type uuid: \"undefined\"",
```

**Comment by judocode** [comment]
@sbhavish87 Have you found a solution yet? I too get the same error as you if I switch to uuid

**Comment by sbhavish87** [comment]
@judocode we're discussing this on the discord thread, but the proposed solutions are not working for me sadly. You can give it a try and let us know
https://discord.com/channels/967097582721572934/1311681123151122555

**Comment by judocode** [comment]
I just tried this with mongo and it works (although was a bug I had to fix with actually having access to create a new Page), so this seems an issue with Postgres not using the value returned from `beforeValidate`

**Comment by judocode** [comment]
Actually sorry this is an order of operations thing. `ensureUniqueSlug` is executed before we attach the tenantId from the beforeValidate in the tenant field. Mongo seems fine when you pass `undefined` in the find query to see if the page's slug matches some other slug in the current tenant, but Postgres (drizzle) is trying to convert `undefined` to a string during the find query.

So if there is a way to ensure the `beforeValidate` on the tenant field always runs first, then I think this can be avoided and fix both issues with mongo and postgres behavior because it's not correctly validating Page slug per Tenant right now

**Comment by judocode** [comment]
It seems that if I define the tenant field before the slug field, and add a property such as "tenantId" on the context iduring beforeValidate on the tenant field, then I can access this in `ensureUniqueSlug`.

**Comment by janbiasi** [comment]
In my case I was able to find another issue within the `ensureUniqueUsername`; as the hook isn't properly typed in the example, one can miss that `data?.tenant` is never defined (as the field is called `tenants` and can have multiple tenants attached).

**Comment by SVronskiy** [comment]
@janbiasi  may be you have solution how to fix the same error on list of pages if tenant selector (left top corner) is not selected (empty tenant)?

**Comment by SVronskiy** [comment]
After applying https://github.com/payloadcms/payload/issues/10874#issuecomment-2623857886 I'm still have a lot of problems on postgres with this multi-tanant plugin, it is not possible to use it at all (((. 1) Then I login as super admin, list with tenants is empty with NAN error, it works only when I select tenant in tenant selector.  2) When I'm adding item, I get error if tenant selector is empty. 3) When adding item I select one tenant, but created item is in another tenant. 4) It is not possible to see tenantid in item in admin interface, have to open postgres and select data manualy.

**Comment by janbiasi** [comment]
> [@janbiasi](https://github.com/janbiasi) may be you have solution how to fix the same error on list of pages if tenant selector (left top corner) is not selected (empty tenant)?

@SVronskiy as I'm not the author of the new plugin I can't provide you with an answer in this case. As I understood it; if you're using a multi-tenant setup, you always need to access a certain tenant to [propagate the tenant to the cookie](https://github.com/payloadcms/payload/blob/main/packages/plugin-multi-tenant/src/utilities/getTenantFromCookie.ts#L10) (controlled by the domain). However the default administrator account (aka super-admin) doesn't belong to any tenant which causes the issue. So you could either try to:
- Grant the super-admin account access to all tenants 
- Login via a tenant domain to enforce the tenant selection

Maybe someone else from the team or the plugin author [JarrodMFlesch](https://github.com/payloadcms/payload/commits?author=JarrodMFlesch) could provide a better answer with more insights as I didn't read through the whole code.

> After applying https://github.com/payloadcms/payload/issues/10874#issuecomment-2623857886 I'm still have a lot of problems on postgres with this multi-tanant plugin, it is not possible to use it at all (((. 1) Then I login as super admin, list with tenants is empty with NAN error, it works only when I select tenant in tenant selector. 2) When I'm adding item, I get error if tenant selector is empty. 3) When adding item I select one tenant, but created item is in another tenant. 4) It is not possible to see tenantid in item in admin interface, have to open postgres and select data manualy.

I didn't experience the issues you describe, but I have a custom setup locally for my project and I'm not using their example.  I am also using tenant domains to access each tenant (eg. subdomain.localhost -> tenant subdomain) with either super-admin or a tenant admin and it works perfectly fine. I can only reproduce your case 1) if I'm logging in on localhost as no tenant is initially selected.

**Comment by bcanfield** [comment]
I'm also running into this issue with the multi tenant example and postgres

**Comment by SVronskiy** [comment]
After upgrading to 3.21.0 I'm not able to start my projects with multi-tenant plugin at all. The same with multi-tenant example on postgres. May be you can ideas how to fix it?

```

/Users/user/next/node_modules/payload/dist/fields/config/sanitize.js:23
        if (fieldAffectsData(field) && field.name.includes('.')) {
                            ^
 
 
TypeError: Cannot read properties of undefined (reading 'includes')
    at sanitizeFields (webpack-internal:///(rsc)/./node_modules/payload/dist/fields/config/sanitize.js:40:94)
    at sanitizeCollection (webpack-internal:///(rsc)/./node_modules/payload/dist/collections/config/sanitize.js:53:104)
    at sanitizeConfig (webpack-internal:///(rsc)/./node_modules/payload/dist/config/sanitize.js:172:122)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildConfig (webpack-internal:///(rsc)/./node_modules/payload/dist/config/build.js:17:16)
```

**Comment by SVronskiy** [comment]
After upgrading to 3.22.0 old error "field.name.includes" was resolved.  
Have new errors, may be you can ideas how to fix it?

1) Seed error both in mongodb and postgres:
```
[00:25:06] INFO: Dropping database.
[00:25:06] INFO: Reading migration files from /Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/src/migrations
[00:25:06] INFO: Migrating: seed
[00:25:07] ERROR: Error running migration seed. Rolling back.
    err: {
      "type": "QueryError",
      "message": "The following path cannot be queried: tenants.tenant",
      "stack":
          QueryError: The following path cannot be queried: tenants.tenant
              at validateQueryPaths (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/database/queryValidation/validateQueryPaths.ts:91:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at findOperation (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/collections/operations/find.ts:169:7)
              at ensureUniqueUsername (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/src/collections/Users/hooks/ensureUniqueUsername.ts:18:30)
              at <anonymous> (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/promise.ts:277:29)
              at promise (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/promise.ts:274:7)
              at async Promise.all (index 1)
              at traverseFields (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/traverseFields.ts:81:3)
              at beforeValidate (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/index.ts:40:3)
              at createOperation (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/collections/operations/create.ts:170:12)
      "data": [
        {
          "path": "tenants.tenant"
        }
      ],
      "isOperational": true,
      "isPublic": false,
      "status": 400,
      "name": "QueryError"
    }
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

QueryError: The following path cannot be queried: tenants.tenant
    at validateQueryPaths (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/database/queryValidation/validateQueryPaths.ts:91:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at findOperation (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/collections/operations/find.ts:169:7)
    at ensureUniqueUsername (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/src/collections/Users/hooks/ensureUniqueUsername.ts:18:30)
    at <anonymous> (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/promise.ts:277:29)
    at promise (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/promise.ts:274:7)
    at async Promise.all (index 1)
    at traverseFields (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/traverseFields.ts:81:3)
    at beforeValidate (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/fields/hooks/beforeValidate/index.ts:40:3)
    at createOperation (/Users/a123/repos/Payload/payload-multi-tenant-mongodb-2/node_modules/payload/src/collections/operations/create.ts:170:12) {
  data: [ { path: 'tenants.tenant' } ],
  isOperational: true,
  isPublic: false,
  status: 400,
  [cause]: [ { path: 'tenants.tenant' } ]
}

``` 

2) admin panel error both in mongodb and postgres:

```
 ⨯ [Error: There are multiple relations with name "tenants" in table "users_tenants"] {
  digest: '1417063495'
}
```

**Comment by SVronskiy** [comment]
May be it will help somebody, adding code to Users collection resolved issue 2 from previous post:
```
const defaultTenantArrayField = tenantsArrayField({
  tenantsCollectionSlug: 'tenants', // this is missing in the example
  tenantsArrayFieldName: 'tenants', // this is missing in the example
  tenantsArrayTenantFieldName: 'tenant', // this is missing in the example
  arrayFieldAccess: {},
  tenantFieldAccess: {},
```
