### ISSUE TITLE
GraphQL schema issue when a collection graphQL configurations is set to false.

### ISSUE THREAD

**Issue by amrsaud** [payloadcms/payload#9893]
### Describe the Bug

I have a collection name CustomerRequests and anther collection name Customer of auth type, I defined a relation between the two:
```ts
{
              name: 'customer',
              type: 'relationship',
              relationTo: 'customers',
              required: true,
              admin: {
                readOnly: true,
              },
              access: {
                update: () => false,
              },
            },
```
for security reasons I don't want to allow auth  graphQL endpoint for Customer collection because of overriding the default RESTfull endpoints, so for the Customer collection I set graphQL field to false as mention in the docs, but I still need it for CustomerRequests, but I get this error:
```bash
 TypeError: Cannot destructure property 'type' of 'graphqlResult.collections[relationTo].graphQL' as it is undefined.
    at relationship (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+graphql@3.2.2_graphql@16.8.1_payload@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_re_2onvt2z3ganpdhqzadvcs2oxr4/node_modules/@payloadcms/graphql/dist/schema/buildObjectType.js:285:20)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+graphql@3.2.2_graphql@16.8.1_payload@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_re_2onvt2z3ganpdhqzadvcs2oxr4/node_modules/@payloadcms/graphql/dist/schema/buildObjectType.js:705:24)
    at Array.reduce (<anonymous>)
    at fields (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+graphql@3.2.2_graphql@16.8.1_payload@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_re_2onvt2z3ganpdhqzadvcs2oxr4/node_modules/@payloadcms/graphql/dist/schema/buildObjectType.js:698:28)
    at resolveObjMapThunk (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/definition.js:504:40)
    at defineFieldMap (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/definition.js:766:20)
    at GraphQLObjectType._fields (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/definition.js:691:26)
    at GraphQLObjectType.getFields (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/definition.js:710:27)
    at collectReferencedTypes (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/schema.js:387:51)
    at collectReferencedTypes (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/schema.js:388:9)
    at new GraphQLSchema (/Users/osx/Documents/work/agillo/fitting/fitting-payload/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/type/schema.js:179:7)
    at configToSchema (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+graphql@3.2.2_graphql@16.8.1_payload@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_re_2onvt2z3ganpdhqzadvcs2oxr4/node_modules/@payloadcms/graphql/dist/index.js:101:20)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_next@15.0.0_react-dom@19.0.0-rc-65_thuhuskbxwhezen25znrjkqmke/node_modules/@payloadcms/next/dist/routes/graphql/handler.js:80:89)
    at new Promise (<anonymous>)
    at getGraphql (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_next@15.0.0_react-dom@19.0.0-rc-65_thuhuskbxwhezen25znrjkqmke/node_modules/@payloadcms/next/dist/routes/graphql/handler.js:79:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.2.2_graphql@16.8.1_monaco-editor@0.52.0_next@15.0.0_react-dom@19.0.0-rc-65_thuhuskbxwhezen25znrjkqmke/node_modules/@payloadcms/next/dist/routes/graphql/handler.js:103:7)
```

This is probably because setting graphQL field to false prevent generating graphQL Schema but it should generate the graphQL schema types and not allow queries/mutation for the Customer collection and not include it to the graphQL schema for CustomerRequests.

Any suggestions to how to solve this or make an improvement of this problem? Thanks

### Link to the code that reproduces this issue

pnpx create-payload-app@latest -t blank

### Reproduction Steps

Create two collections, then make one of them has relationship to the other, disable the graphQL for the one the collection that is the relation to, then try to make graphQL query from the one that has it not disabled.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
> fitting-backend@1.0.0 payload /Users/amrsaud/Desktop/Work - Agillo/fitting-backend
> cross-env NODE_OPTIONS=--no-deprecation payload "info"


Binaries:
  Node: 22.3.0
  npm: 10.8.3
  Yarn: N/A
  pnpm: 9.13.0
Relevant Packages:
  payload: 3.2.2
  next: 15.0.0
  @payloadcms/db-mongodb: 3.2.2
  @payloadcms/db-postgres: 3.2.2
  @payloadcms/email-nodemailer: 3.2.2
  @payloadcms/graphql: 3.2.2
  @payloadcms/next/utilities: 3.2.2
  @payloadcms/payload-cloud: 3.2.2
  @payloadcms/richtext-lexical: 3.2.2
  @payloadcms/translations: 3.2.2
  @payloadcms/ui/shared: 3.2.2
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
```

**Comment by gor3a** [comment]
Same issue with me!
I was shared for it from 3 minutes ago
My app in last phase to production and I stuck on it
@jmikrut Can you help on this?

**Comment by jmikrut** [comment]
Hey @gor3a and @amrsaud - I just added a feature that will do what you need.

Check out the PR here:

https://github.com/payloadcms/payload/pull/10265

When it merges, you will be able to use these new controls.
